### ISSUE TITLE
"Jurisdikcija" lauko pakeitimai

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#1017]
Puslapyje **Organizacijos** filtre "Valdymo sritis" viena iš sričių yra "Savivaldybės". Šis įrašas gali būti keičiamas/pridedamas per administracinę aplinką prie kiekvienos organizacijos, pvz. Pradinis -> Organizations -> Organizations -> Akmenės rajono savivaldybės administracija -> Jurisdikcija. Šiame lauke (Jurisdikcija) galima/leidžiama įrašyti bet ką laisvu tekstu. 

Vieša aplinka:

![Image](https://github.com/atviriduomenys/katalogas/assets/101550789/8be9c5ce-e4e0-440c-9a7a-7e195d380e60)

 Administracinė aplinka:

![Image](https://github.com/atviriduomenys/katalogas/assets/101550789/d6b7b562-29db-4355-ad56-6a38193479f7)

Pasirinkti valdymo srities "Savivaldybės" ne per administracinę aplinką, o organizacijos redagavimo formoje nėra galimybės, nes tokio pasirinkimo nėra arba nebuvo pridėtas. Vietoje to, pateikiamos ministerijos, tik kelios savivaldybės ir dar valdymo sritys tokios kaip "Verslas" ar Nevyriausybinės organizacijos.

**Pavyzdys**
Administracinėje aplinkoje Pradinis -> Organizations -> Organizations pasirinkus Visagino savivaldybės administraciją, "Jurisdikcija" laukelyje taip pat įrašyta Visagino savivaldybės administracija. Toks įrašas atsiranda ir **Organizacijos** puslapyje prie Valdymo srities filtro. Jeigu čia vietoje Visagino savivaldybės administracijos "Jurisdikcija" įrašysime bet kokį kitą tekstą, pvz. "Ketvirtadienis", tai atsidurs ir prie Valdymo sričių viešoje aplinkoje.

![Image](https://github.com/atviriduomenys/katalogas/assets/101550789/5926d4ae-db8b-45b9-8ac7-bd524d96eff6)

**Comment by Grigorjeva11** [comment]
Šiuo atvėju tai nėra "bug'as", tai yra funkcionalumo dalis, kuri veikia tesingai pagal tai, kokia buvo idėja, tiesiog nuo pat pradžiu idėja buvo bloga. 

Bus vykdoma analizė dėl pakeitimo.

**Comment by Grigorjeva11** [comment]
Papildomi reikalavimai iš #1044 : 
**Duomenų rinkiniai** ir **Poreikiai ir pasiūlymai** puslapyje kairėje pusėje prie kiekvieno filtro norėtųsi funkcijos "Išskleisti/Suskleisti" paliekant 10 pirmų įrašų sąraše, kaip tai yra pvz. "Organizacijos" puslapyje. Šiuo metu yra įgyvendinta taip, kad rodoma 10 pirmų įrašų, bet jeigu norima pažiūrėti visas valdymo sritis, reikia eiti per "Organizacijos" puslapį arba spausti ant grafiko ikonos, kuri veda į švieslentes. Ten pateikiamas visas sąrašas.


Šiame puslapyje dar reikėtų kairėje pusėje kur filtrai, sukeisti "Organizacija" su "Valdymo sritis", kaip tai yra padaryta su puslapiais "Organizacijos" ir "Duomenų rinkiniai".

**Comment by Grigorjeva11** [comment]
Parengta techninė užduotis pakeitimams atlikti
[Technine užduotis KATALOGAS 1017.docx](https://github.com/user-attachments/files/17572175/Technine.uzduotis.KATALOGAS.1017.docx)

**Comment by JuliusLADP** [comment]
Tik vienas papildymas dėl privalomo lauko Organizacijos formoje ir sąrašo papildymas Nepriskirta [Technine.uzduotis.KATALOGAS.1017.docx](https://github.com/user-attachments/files/17661201/Technine.uzduotis.KATALOGAS.1017.docx)

**Comment by Grigorjeva11** [comment]
Galutinė versija (atlikta daugiau pakeitimų)

[Technine.uzduotis.KATALOGAS.1017 GALUTINĖ.docx](https://github.com/user-attachments/files/17661549/Technine.uzduotis.KATALOGAS.1017.GALUTINE.docx)

**Comment by Grigorjeva11** [comment]
@Tadas-Stankevicius papildomai:
Puslapyje https://data.gov.lt/requests/submitted/ taip pat yra valdymo sričių filtras, kuri reikia pakoreguoti pagal šiuos reikalavimus:

a.	Užtikrinti, kad visos diagramos veiktu teisingai atsižvelgiant į anksčiau atliktus pakeitimus (jeigu atlikti pakeitimai susiję su diagramų veikimu).
b.	Realizuoti funkciją "Išskleisti/Suskleisti" prie kiekvieno šiame puslapyje esančio filtro. Nustatyti, kad „by default“ atvaizduotu tik 10 pirmų įrašų sąraše, kaip tai yra pvz. "[Organizacijos](https://test.data.gov.lt/organizations/)" puslapyje, atskleidus sąrašą būtų matomos visos reikšmės, o suskleidus, vėl tik 10.
c.	Pakeisti, kad LT puslapio versijoje sąraše atsivaizduotų valdymo sričių sąrašas iš  valdymo_sritis.pavadinimas_lt.
d.	Pakeisti, kad EN puslapio versijoje sąraše atsivaizduotų valdymo sričių sąrašas iš  valdymo_sritis.pavadinimas_en.

**Comment by adp-atea** [comment]
Ištestuota. Pridedama testavimo ataskaita.
[Klaidu-patikra-1125.pdf](https://github.com/user-attachments/files/17900505/Klaidu-patikra-1125.pdf)
