### ISSUE TITLE
Koordinatoriaus prenumeratos

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1031]
Vyriausias koordinatorius turi gauti pranešimą tik atvejais, kai registruotas Poreikis, kuriam nėra priskirta organizacija. Visais kitais atvejais   vyr. koordinatoriui prenumeratos uždedamos tik jo indiviudualiu pasirinkimu.

**Comment by adp-atea** [comment]
Panašu, kad buvo jau sutvarkytas, nes veikia, kaip numatyta.
