### ISSUE TITLE
Kodėl Poreikių filtre "Duomenų rinkinio būsena" reikšmė - nepriskirti?

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1036]
Poreikių puslapyje filtre "Duomenų rinkinio būsena" pasirinkus reikšmę - nepriskirti https://test.data.gov.lt/requests/submitted/?selected_facets=dataset_status_exact%3AUNASSIGNED  atidarius detalų aprašymą, matoma, kad poreikis turi priskirtus rinkinius: ![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/826ee247-a470-4881-8195-22877e7dc230)

**Comment by ATEAanalyst** [comment]
Duomenų rinkinys turi reikšmę "Nepriskirta" , kadangi čia pridėtas ne vienas duomenų rinkinys, vienas iš jų turi būti būsenos "Nepriskirta". Tai nesusiję su priskyrimu duomenų rinkinių prie poreikių.
