### ISSUE TITLE
Funkcionalumas "Priskirti organizaciją"

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#1045]
Gamybinėje aplinkoje neveikia duomenų rinkinio funkcionalumas "Priskirti organizaciją": lauke "Priskyrimo rūšis" nerodo iškleidžiamo sąrašo pasirinkimų.
Jungtasi superuserio teisėmis.
Pvz. https://data.gov.lt/datasets/1002/attribution/add/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9cd72dd1-a840-47f4-8a5d-a0b771b8c9ec)

Testinėje aplinkoje veikia: lauke "Priskyrimo rūšis" rodo pasirinkimą "Contributor".
Jungtasi organizacijos koordinatoriaus teisėmis.
Pvz. https://test.data.gov.lt/datasets/2490/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f2a76f72-0c06-452a-957a-20fe784bd5bb)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/53a7b4ff-4581-4fa6-b3e4-d4c8b9c65fcd)

@JuliusLADP:
- laukas "Priskyrimo rūšis" turėtų būti papildyta ir kitomis pozicijomis: https://www.w3.org/TR/vocab-dcat-3/#qualified-forms?
- lauko "Priskyrimo rūšis"pozicijos turėtų būti nurodytos lietuvių kalba ir pagal galimybes pateikiamas paaiškinimasar nuoroda į anglišką paaiškinimą? 
- gamybinės aplinkos administracinėje aplinkoje reikia sukurti atitinkamus atributus: https://data.gov.lt/admin/vitrina_datasets/attribution/

**Comment by Grigorjeva11** [comment]
@IngaIVPK @JuliusLADP Prašau patikslinti ar klaida vis dar aktuali (egzistuoja), nes labai sena

**Comment by IngaIVPK** [comment]
Neaktuali.
