### ISSUE TITLE
Kuriant naują duomenų rinkinį per poreikį, jis yra sukuriamas, tačiau neišsaugomas prie poreikio iš kurio buvo sukurtas

### ISSUE THREAD

**Issue by ATEAanalyst** [atviriduomenys/katalogas#1049]
Kuriant naują duomenų rinkinį per poreikį jis yra sukuriamas ir matomas per duomenų rinkinių skiltį, tačiau prie poreikio nėra atvaizduojamas. Atsirasti gali tik tą rinkinį priskyrus. 

![Image](https://github.com/atviriduomenys/katalogas/assets/165259473/bde8a2b3-e9ca-4674-9749-2e45c99e75c1)

![Image](https://github.com/atviriduomenys/katalogas/assets/165259473/2d241581-13f3-4220-b7df-1fafa8d1bf6c)

Taip pat prie duomenų rinkinio nėra atvaizduojamas poreikis iš kurio buvo sukurtas duomenų rinkinys

![Image](https://github.com/atviriduomenys/katalogas/assets/165259473/11c3fa52-9f85-4582-a700-f8499822b490)

**Comment by ATEAanalyst** [comment]
[Aprašymas_#1049.docx](https://github.com/atviriduomenys/katalogas/files/15218751/Aprasymas_.1049.docx)

**Comment by JuliusLADP** [comment]
Epizodo aprašymui pastabų neturiu.

**Comment by ATEAanalyst** [comment]
Darbus (programavimą, analizę, testavimą ir diegimus) vertiname 18h. Ar patvirtinate vertinimą ir galime pradėti vykdyti užduotį?

**Comment by JuliusLADP** [comment]
18 val užduoties vykdymui tvirtinu
