### ISSUE TITLE
Organizacijos priskyrimo Valdymo srities grupei pataisymas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1063]
Patikslinti Duomenų rinkiniai Valdymo srities filtro algoritmo veikimą, kad Valdymo srities grupės atstovas būtų surandamas filtro paieškoje, jeigu tenkina šias sąlygas: 
1. Pavaldi organizacija turi būti viešinama, 
2. Bent viena pavaldi organizacija turi būti viešinama ir turėti bent vieną Inventorintą, Atvertą arba Planuojamą duomenų rinkinį. 
3. Tėvinė, kaip šiuo atveju "Savivaldybė" turi turėti bent vieną pavaldžią organizaciją.
4. vaikinės organizacijos saugojimo metu, jeigu pasikeičia organizacija kuriai yra ji pavaldi, tai automatiškai atliekami ir atitinkami sąryšyje esantys pakeitimai (išrankos). T.y. duomenų rinkiniai ir poreikiai yra automatiškai susiejami su nauja valdymo sritimi (ne diegimo ar duomenų rinkinio ar poreikio redagavimo metu, o organizacijos saugojimo metu), kai yra pakeičiama organizacija, kuriai yra pavaldi redaguojama organizacija.

**Comment by ATEAanalyst** [comment]
Darbus (programavimą, analizę ir testavimą) vertiname 12 val.

**Comment by JuliusLADP** [comment]
Tvirtinu užduotį 12 val.
