### ISSUE TITLE
Įgyvendinti LADP naudotojų informavimą apie galimus trikdžius naujinimų metu

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1075]
Įgyvendinti LADP naudotojų informavimą, pateikiant perspėjantį pranešimą, kuris rodomas naudotojui atidarius LADP puslapius. Pranešime nurodomas laiko intervalas, kurio metu tikėtini trikdžiai

**Comment by ATEAanalyst** [comment]
Pidedamas aprašymas. 

[Aprašymas_1075.docx](https://github.com/user-attachments/files/16013981/Aprasymas_1075.docx)

**Comment by JuliusLADP** [comment]
Kur galima redaguoti formuoti pranešimo tekstą?

**Comment by ATEAanalyst** [comment]
Redaguoti galima tik tiesiai per DB.
