### ISSUE TITLE
Rūšiuoti naujienas pagal paskelbimo datą

### ISSUE THREAD

**Issue by ATEAanalyst** [atviriduomenys/katalogas#1084]
Naujienos turi būti rūšiuojamos pagal paskelbimo datą. Viršuje rodomos naujausios paskelbtos naujienos. Paredagavus naujieną ji nėra keliama į viršų kaip naujai paskelbta.

**Comment by JuliusLADP** [comment]
Klaidos aprašymas tinkamas

**Comment by ATEAanalyst** [comment]
Išsiaiškinta, tai ne klaida.
