### ISSUE TITLE
Spinta klaidos

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#1150]
bandant kelti bet kokį rinkinį į TEST spintą pateikiamos kitokios klaidos
![image](https://github.com/user-attachments/assets/204beac4-09ca-4772-ba1a-d2810f0972e7)

Pabaigoje pateikiama tokia klaida
HTTPError: 502 Server Error: Bad Gateway for url: https://put-test.data.gov.lt/auth/token
Patikrinau, tai šis adresas nepasiekiamas net per naršyklę, kažkas pagriuvo ne RC pusėje
 
![image](https://github.com/user-attachments/assets/e24b683d-ddac-460a-b9f9-c5fc8a0fb018)

Duomenų gavimas taip pat neįmanomas
 
![image](https://github.com/user-attachments/assets/1624b700-3a2f-466d-9339-a40d94bd776b)

**Comment by JustinasKen** [comment]
Kiek meginau atidaryti https://get-test.data.gov.lt/datasets/gov/rc/ar/gragatve/GraGatve, atrodo, kad jau veikia
