### ISSUE TITLE
Pagerinti ADP portalo matomumą

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1156]
Reikia pakoreguoti katalogo kodą, kad jis atitiktų standartus pagal kuriuos web paieškos serveriai suranda puslapius ir padidintų ADP surandamumą ir matomumą internete. 

Tam gali pagelbėti:

- https://seositecheckup.com/seo-audit/data.gov.lt

data.gov.lt SEO Report | SEO Site Checkup
 View a detailed SEO analysis of data.gov.lt - find important SEO issues, potential site speed optimizations, and more.
 

- Panagrinėti [Dataset Search (google.com)](https://datasetsearch.research.google.com/) projektą

- Ką daryti, kad įtrauktų. [Rašo](https://blog.google/products/search/discovering-millions-datasets-web/):

If you have a dataset on your site and you describe it using schema.org, an open standard, others can find it in Dataset Search. If you know that a dataset exists, but you can't find it in Dataset Search, ask the provider to add the schema.org descriptions and others will be able to learn about their dataset as well.

**Comment by Tadas-Stankevicius** [comment]
Įtraukimui į [Dataset Search (google.com)](https://datasetsearch.research.google.com/) reikalingas schema.org elementas  duomenų rinkinio html. 

Siūlau pagrindiniame duomenų rinkinio puslapyje (`https://data.gov.lt/datasets/<dataset_id>/`) pridėti schema.org elementą. 

# Test rezultatas.
```   
<script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "Dataset",
            "name": "TAAR pirminiai duomenys (raw data) apie skolininkus (skolininkai juridiniai asmenys)",
            "description": "Turto arešto aktų registro nuasmeninti duomenys (RAW DATA) apie skolininkus, kai skolininkai juridiniai asmenys, jų teisinę formą ir kilmės šalį, turto arešto aktų jų statusus, įregistravimo / išregistravimo datas, areštuojančią instituciją.",
            "url": "/datasets/2233/",
            "license": "https://creativecommons.org/licenses/by/4.0/deed.lt",
            "creator": {
                "@type": "Organization",
                "name": "Valstybės įmonė Registrų centras"
            },
            "keywords": ["areštas", "registras", "Registrų centras", "skola", "skolininkas", "TAAR"],
            "distribution": [{
                    "@type": "DataDownload",
                    "encodingFormat": "CSV",
                    "contentUrl": "https://127.0.0.1:8000/datasets/gov/aaa/atlieku_tvarkymas/AtliekuSusidarymasTvarkymas?format(csv)"
                }, {
                    "@type": "DataDownload",
                    "encodingFormat": "JSON",
                    "contentUrl": "https://127.0.0.1:8000/datasets/gov/aaa/atlieku_tvarkymas/AtliekuSusidarymasTvarkymas?format(json)"
                }, {
                    "@type": "DataDownload",
                    "encodingFormat": "JSONL",
                    "contentUrl": "https://127.0.0.1:8000/datasets/gov/aaa/atlieku_tvarkymas/AtliekuSusidarymasTvarkymas?format(jsonl)"
                }, {
                    "@type": "DataDownload",
                    "encodingFormat": "ASCII",
                    "contentUrl": "https://127.0.0.1:8000/datasets/gov/aaa/atlieku_tvarkymas/AtliekuSusidarymasTvarkymas?format(ascii)"
                }, {
                    "@type": "DataDownload",
                    "encodingFormat": "RDF",
                    "contentUrl": "https://127.0.0.1:8000/datasets/gov/aaa/atlieku_tvarkymas/AtliekuSusidarymasTvarkymas?format(rdf)"
                }
            ],
            "datePublished": "2023-07-24 12:43:42.878632+00:00",
            "isAccessibleForFree": true
        }
<  / script >
```
# Google "rich result" kodo patikra:
Patikrinus puslapio kodą su ([google-rich-result-test](https://search.google.com/test/rich-results)). 
Išsami google paieška randa tinkamą elementą ir jį apdoroja - [rich-results](https://search.google.com/test/rich-results/result/r%2Fdatasets?id=gHwoY6xnp4Crc8s5d_TLYw)
Google crawler bot aptikęs tokį elementą įtrauktu duomenų rinkinį į [Dataset Search (google.com)](https://datasetsearch.research.google.com/)
![image](https://github.com/user-attachments/assets/4b07b142-1171-488b-a3b8-4eeb94a3ce4f)

Tokiu atveju, kai prie duomenų rinkinio nėra duomenų, `"distribution"` nustatomas į `null`.

**Comment by JuliusLADP** [comment]
Vienas pastebėjimas: turi būti matomi tik "Atverti" būklės rinkiniai t.y. tie kurie viešai publikuojami. Jie matomi tik "vidiniams" naudotojams

**Comment by Tadas-Stankevicius** [comment]
Į išsamia google paiešką įtraukiami tik tie puslapiai, kuriuos `googlebot` gali pasiekti viešai. Papildomai apsaugai, pridėjau patikrinimą -> `schema.org` elementas pridedamas tik jeigu duomenų rinkinio parametras nustatytas į viešą `is_public = true`.

**Comment by Tadas-Stankevicius** [comment]
Norint pridėti `sitemap.xml` failą, reikia apsispręsti, kokia informacija jame bus pateikta. Įdiegus `sitemap`, trečiųjų šalių paieškos sistemų „crawleriai“ gaus struktūrizuotą nuorodų rinkinį, o tai padidins tikimybę, kad visi puslapiai bus tinkamai indeksuoti ir lengviau pasiekiami per paieškos variklius.

Kaip galėtų atrodyti naujas sitemap.xml resursas (https://data.gov.lt/sitemap.xml):
**Pagrindinis sitemap  https://data.gov.lt/sitemap.xml**
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
 <sitemap>
  <loc>https://data.gov.lt/sitemap-root.xml</loc>
 </sitemap>
 <sitemap>
  <loc>https://data.gov.lt/sitemap-datasets.xml</loc>
 </sitemap>
 <sitemap>
  <loc>https://data.gov.lt/sitemap-organizations.xml</loc>
 </sitemap>
 <sitemap>
  <loc>https://data.gov.lt/sitemap-models.xml</loc>
 </sitemap>
 <sitemap>
  <loc>https://data.gov.lt/sitemap-more.xml</loc>
 </sitemap>
</sitemapindex>
```
**https://data.gov.lt/sitemap-root.xml** 
Pagrindinio puslapio nuoroda su aukščiausiu prioritetu. 
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
 <loc>https://data.gov.lt/</loc>
  <changefreq>monthly</changefreq>
  <priority>1.0</priority>
 </url>
</urlset>
```
**https://data.gov.lt/sitemap-datasets.xml**
Duomenų rinkinių, nuorodos į viešus duomenų rinkinius.
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
 <url>
 <loc>https://data.gov.lt/datasets/1/</loc>
  <lastmod>2023-07-28</lastmod>
  <changefreq>hourly</changefreq>
  <priority>0.8</priority>
 </url>
 <url>
  <loc>https://data.gov.lt/datasets/2/</loc>
   <lastmod>2023-07-28</lastmod>
   <changefreq>hourly</changefreq>
   <priority>0.8</priority>
 </url>
 <url> ...  </url>
```
**https://data.gov.lt/sitemap-organizations.xml**
Nuorodos į viešai prieinamas organizacijas.
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
 <url>
  <loc>https://data.gov.lt/orgs/1/</loc>
   <lastmod>2023-07-28</lastmod>
   <changefreq>daily</changefreq>
   <priority>0.6</priority>
 </url>
 <url>
  <loc>https://data.gov.lt/orgs/2/</loc>
   <lastmod>2023-07-28</lastmod>
   <changefreq>daily</changefreq>
   <priority>0.6</priority>
 </url>
 <url> ...  </url>
```
**https://data.gov.lt/sitemap-models.xml**
Nuorodos į viešai atvertus modelius.
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
 <url>
  <loc>https://data.gov.lt/datasets/2361/models/ChemNaudotojai/</loc>
  <changefreq>daily</changefreq>
  <priority>0.7</priority>
 </url> 
 <url>
  <loc>https://data.gov.lt/datasets/2233/models/AtliekuSusidarymasTvarkymas/</loc>
  <changefreq>daily</changefreq>
  <priority>0.7</priority>
 </url>
 <url> ...  </url>
```
**https://data.gov.lt/sitemap-more.xml**
Papildomos nuorodos iš pasirinkimo daugiau. 
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
 <url>
  <loc>https://data.gov.lt/more/about/</loc>
   <changefreq>yearly</changefreq>
   <priority>0.3</priority>
 </url>
 <url>
  <loc>https://data.gov.lt/more/regulation/</loc>
   <changefreq>yearly</changefreq>
   <priority>0.3</priority>
 </url>
 <url> ...  </url>
```

**Comment by adp-atea** [comment]
Ištestuota. Pridedama testavimo ataskaita.
[Klaidu-patikra-1121.pdf](https://github.com/user-attachments/files/17842598/Klaidu-patikra-1121.pdf)
