### ISSUE TITLE
Diagramų koregavimas

### ISSUE THREAD

**Issue by Grigorjeva11** [atviriduomenys/katalogas#1262]
Šiuo metu visos diagramos (pvz. https://data.gov.lt/dataset/stats/jurisdiction/?indicator=model-count ) su visais filtrais veikia principu, kad sumuoja reikšmės su anksčiau buvusiom reikšmėm (pvz. atsisiuntimų diagramoje su metiniu periodiškumu už 2024 metus rodo suma atsisiuntimų visus praejusius metus (nuo 2019 iki 2023) + 2024 metų). Reikia, kad diagramoje atsivaizduotu tik atsisiuntimus už nurodyta laikotarpį, nesumuojant.

Pakeitimas turi buti atliktas su visais filtrais. 

Rušiavima "didžiausias rodyklis" ir "mažiausias rodyklis" galima trinti, kadangi neturi jokios logikos. Nebent apsvarstyti filtro pavadinimo pakeitimą, kad būtų aišku ką jis atlieka.

Stulpelinių diagramų galima nekeisti, kadangi jos atvaizduoja būtent bendra sumą (atsisiuntimų, duomenų rinkinių itt.)

**Comment by adp-atea** [comment]
Ištestuota. Pridedama testavimo ataskaita.
[Klaidu-patikra-1125.pdf](https://github.com/user-attachments/files/17900505/Klaidu-patikra-1125.pdf)
