### ISSUE TITLE
Organizacijos tvarkytojo rolė

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#1290]
Šiuo metu organizacijos tvarkytojų/koordinatorių sąraše, gali būti tik naudotojai, su galimybe įtraukti kitos organizacijos atstovus, kaip tvarkytojus.

Tačiau, tai nepatogu, kai išorinė organizacija, turi daug atstovų ir jie gali keistis.

Tokiais atvejais patogiau, jei visa organizacija galėtu būti priskirta, kaip tvarkytojas, suteikiant teisę, visiems jos atstovams tvarkyti kitų organizacijų rinkinius, prie kurių organizacija yra priskirta, kaip tvarkytojas.

`can_manage(user, object)` funkcija, turėtu patikrinti, ar naudotojas yra organizacijos atstovas, kuri (organizacija) yra įtraukta, kaip kitos organizacijos ar rinkinio tvarkytojas.

Kitaip sakant `Representative` gali būti ir kita organizacija, ne tik naudotojas.

Kad tai veiktu, organizacijos ir rinkinio tvarkytojų sąraše, reikia padaryti galimybę, įtraukti organizaciją, ne `can_manage(user, object)` funkciją, kuri patikrintu, ar ne tik ar naudotojas yra organizacijos/rinkinio reprezentative, bet patikrinti ar naudotojas representative organizacijos, kuri pati yra reprezentative.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/1269
- https://github.com/atviriduomenys/katalogas/issues/171

**Comment by adp-atea** [comment]
Ištestuota. Testavimo ataskaita prisegama. [Klaidu-patikra-0108.pdf](https://github.com/user-attachments/files/18345149/Klaidu-patikra-0108.pdf)
