### ISSUE TITLE
remove group from category classifier CMS

### ISSUE THREAD

**Issue by Tadas-Stankevicius** [atviriduomenys/katalogas#1292]
Remove `groups` attribute from the admin site change form for the category:
`/admin/vitrina_classifiers/category/<int>/change/`

**Comment by adp-atea** [comment]
Ištestuota. Prisegama ataskaita.
[Klaidu-patikra-1217.pdf](https://github.com/user-attachments/files/18161857/Klaidu-patikra-1217.pdf)

**Comment by JuliusLADP** [comment]
Iš esmės pasinaudoti galima, bet tobulintina: 
Path turėtų pasiūlyti pagal hierarchiją arba automatiškai- o dabar pridedant Reljefas prisiėjo "sufantazuoti"  reikšmę kaip ir Depth (reikėtų versti į Hierarchinis lygmuo), kuris taip pat turėtų būti priskiriamas automatiškai pagal pasirinktą priklausymą aukštesnei kategorijai.  Nes be jų neleidžia išsaugoti.

**Comment by adp-atea** [comment]
Ištestuota. Testavimo ataskaita prisegama. [Klaidu-patikra-0108.pdf](https://github.com/user-attachments/files/18345149/Klaidu-patikra-0108.pdf)
