### ISSUE TITLE
Pasikeitusių nuorodų peradresavimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#144]
Įgyvendintas pasikeitusių nuorodų peradresavimas, kad portalo naudotojai išsisaugoję senas nuorodas, patektų ten, kur nuorodos vesdavo anksčiau.

---

Reikia peržiūrėti esamas nuorodas data.gov.lt ir test.data.gov.lt svetainėse ir padaryti peradresavimus, taip, kad senos nuorodos veiktų, jei senos nuorodos keitėsi, tada reikia peradresuoti į naują vietą.

Pavyzdžiai:

- `/usecases/examples` -> `/projects/`
- `/usecases/applications` -> `/projects/`
- `/usecase` -> `/projects/add/`
- `/dataset/<slug>/` -> `/datasets/<id>/`
- ...

Taip pat reikėtų pataisyti nuorodas, kurios neatitinka standartinės formos:

- `/requests/` - sąrašas visų objektų
- `/requests/add/` - naujo objekto pridėjimas
- `/requests/<id>/` - vieno objekto peržiūra
- `/requests/<id>/update/` - objekto forma
- `/requests/<id>/remove/` - objekto trynimas
- `/requests/<id>/orgs/` - susijusių objektų peržiūra

### Epic

- https://github.com/atviriduomenys/katalogas/issues/54

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/94
- https://github.com/atviriduomenys/katalogas/issues/285

### Resursai

- https://docs.djangoproject.com/en/3.2/ref/contrib/redirects/#via-the-python-api

**Comment by sirex** [comment]
Radau tokias nuorodas internetuose: https://data.gov.lt/datasets?q=&organization_id=50

Jei jos neperadresuojamos, tai reikėtų peradresuoti.

**Comment by Faustasm** [comment]
> Radau tokias nuorodas internetuose: https://data.gov.lt/datasets?q=&organization_id=50
> 
> Jei jos neperadresuojamos, tai reikėtų peradresuoti.

Su redirect objektu query parametrų dinamiškai paduoti negalima, jei norim perdaryt query parametrus reikia panaudot šį kodą nebent žinai kita būdą. https://github.com/atviriduomenys/katalogas/pull/287/files#diff-bf7ad6e1030637bc24e43ef82abdfe879984529f4239e1c7bb5a51b8787056a3R77

**Comment by sirex** [comment]
Peradresavimasv is dar neveikia:

https://data.gov.lt/datasets?q=&organization_id=269 pakeitus į test.data.gov.lt nepakeičia URL.

https://data.gov.lt/dataset/atviru-duomenu-katalogo-api pakeitus į test.data.gov.lt nepakeičia URL.

**Comment by sirex** [comment]
Klaidingai peradresuoja šiuos URL:

| senas | naujas (teisingas) |
| --- | --- |
| `https://data.gov.lt/datasets?q=&organization_id=269` | `https://test.data.gov.lt/orgs/269/datasets/?selected_facets=organization_exact:269` |
| `https://data.gov.lt/requests/2b6f55f8-cbc9-4e77-a4e8-31c21da12420` | `https://test.data.gov.lt/requests/194/` |
