### ISSUE TITLE
Pataisyti Dataset.public managerį

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#149]
Modifikuotas `PublicDatasetManager` filtravimas atrenkant tuos duomenų rinkinius, kurie yra matomi viešai.

---

Šiuo metu `PublicDatasetManager` nedaro jokio filtravimo, nors turėtu atrinkti tik tuos duomenų rinkinius, kurie yra matomi viešai.

Pavyzdžiui dabar atrenkama 2006 rinkiniai, nors data.gov.lt rodo 1782.

**Comment by adp-atea** [comment]
This task did not change anything with migrations, if they do not work it is not because of this task.

**Comment by sirex** [comment]
This might be caused by a merge from devel, anyway, I can't test it until migrations are fixed.

**Comment by adp-atea** [comment]
As I understood the migration issue should be fixed with task #119
