### ISSUE TITLE
Kategorijų sąrašas tituliniame

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#150]
Modifikuotas "featured kategorijų" sąrašas su paveiksliukais tituliniame lape su galimybe juos įkelti per Django admin, paveiksliukai atvaizduojami su [sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail).  Perkelta Category nuo AL_Node į MP_Node ir parašyta duomenų migraciją.

---

Padaryti kategorijų sąrašą, su paveiksliukais, tokį, koks yra dabar tituliniame lape:

https://data.gov.lt/

- [x] Turėtu būti rodomos tik featured kategorijos.

- [ ] Kategorijos paveiksliukai turi būti įkeliami per Django admin, paveiksliukai atvaizduojami su [sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail).

- [ ] Įkeliant paveiksliukus reikėtų patikrinti ar jų matmenys vienodi.

- [x] Rūšiuojam pagal abėcėlę.

- [x] Dokumentuoti (prie model property help_text) arba įdėti drop down `icon` pasirinkimui.

- [x] Perkelti Category nuo AL_Node į MP_Node ir parašyti duomenų migraciją.

**Comment by adp-atea** [comment]
Need further clarification on the process that is needed to be done to convert from AL_Node to MP_Node

**Comment by sirex** [comment]
> Need further clarification on the process that is needed to be done to convert from AL_Node to MP_Node

Unfortunately there is [no documented way how to migrate from AL to MP](https://github.com/django-treebeard/django-treebeard/issues/244). Library [author suggests](https://github.com/django-treebeard/django-treebeard/issues/125#issuecomment-762164502) using [dump_bulk()](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.dump_bulk) and [load_bulk()](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.load_bulk).

Personally I would try to reconstruct fields used by [MP_Node](https://github.com/django-treebeard/django-treebeard/blob/master/treebeard/mp_tree.py).

```python
class MP_Node(Node):
    path = models.CharField(max_length=255, unique=True)
    depth = models.PositiveIntegerField()
    numchild = models.PositiveIntegerField(default=0)
```

So basically we need to reconstruct `path`, `depth` and `numchild`.

`depth` and `numchild` is easy, `path` is more complicated, because you need to reverse engineer, how it is encoded.

```python
    steplen = 4
    alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

    @classmethod
    def numconv_obj(cls):
        if cls.numconv_obj_ is None:
            cls.numconv_obj_ = NumConv(len(cls.alphabet), cls.alphabet)
        return cls.numconv_obj_

    @classmethod
    def _int2str(cls, num):
        return cls.numconv_obj().int2str(num)

    @classmethod
    def _get_basepath(cls, path, depth):
        """:returns: The base path of another path up to a given depth"""
        if path:
            return path[0:depth * cls.steplen]
        return ''

    @classmethod
    def _get_path(cls, path, depth, newstep):
        """
        Builds a path given some values
        :param path: the base path
        :param depth: the depth of the  node
        :param newstep: the value (integer) of the new step
        """
        parentpath = cls._get_basepath(path, depth - 1)
        key = cls._int2str(newstep)
        return '{0}{1}{2}'.format(
            parentpath,
            cls.alphabet[0] * (cls.steplen - len(key)),
            key
        )
```

It is not completely obvious to me how it is encoded, but it looks, that the structure ir pretty simple (`.` symbol is added for readability):

```
0000
0000.0000
0000.0001
0000.0002
0000.0002.0000
0000.0002.0001
0001
0001.0000
...
```

So you need to run schema migration, to add `path`, `depth` and `numchild`. Then you need to run data migration and calculate `path`, `depth` and `numchild`, by traversing existing tree.
