### ISSUE TITLE
Šaltinio forma

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#154]
Modifikuotas duomenų rinkinio peržiūros langas, pridedant mygtuką „Naujas šaltinis“, kuris atidaro naujo šaltinio formą. Lango funkcionalumas konfigūruojamas dinamiškai, priklausomai nuo vartotojo rolės ir teisių.

--- 

- [ ] - [x] Duomenų rinkinio [details puslapyje](#68), duomenų šaltinių lentelės viršuje pridėti mygtukus „Naujas šaltinis“, kuris atidaro naujo šaltinio formą.
- [x] Nuorodos ir failo įkėlimo formas turi būti viena, jei užpildyta nuoroda, rodoma, kaip nuoroda, jei įkeltas failas, rodoma, kaip failas. Gali būti užpildytas tik failas arba tik nuoroda, bet ne abu.
- [x] Naujo šaltinio forma turėtu atitikti dabartinę šaltinio formą.
- [x] Teisės:  `user.is_staff`, `dataset.organization == user.organization` ir `dataset.manager = user`.
- [x] Šaltinių sąraše, prie kiekvieno šaltinio pridėti mygtuką „Keisti“, mygtuką rodyti jei naudotojas turi reikiamas teises. Mygtukas atidaro šaltinio keitimo formą.
- [x] Šaltinių sąraše, prie kiekvieno šaltinio pridėti mygtuką „Trinti“, jį paspaudus ištrinamas šaltinis. Mygtukas rodomas turint reikiamas teises. Rodom config dialogą (gali būti js alert).

**Comment by adp-atea** [comment]
Nėra prieigos prie dabartinės šaltinio formos, kaip ji tiksliai turėtų atrodyti?

**Comment by sirex** [comment]
> Nėra prieigos prie dabartinės šaltinio formos, kaip ji tiksliai turėtų atrodyti?

Duomenų rinkinio [details puslapyje](https://github.com/atviriduomenys/katalogas/issues/154#68), duomenų šaltinių lentelės viršuje pridėti mygtukus „Naujas šaltinis“, kuris atidaro naujo šaltinio formą.

**Comment by adp-atea** [comment]
Su mygtuku viskas aišku, neaišku kokie laukai turi būti pačioje formoje, nes nežinau kokia yra dabartinė forma.

**Comment by sirex** [comment]
![image](https://user-images.githubusercontent.com/297583/193828870-261a3b22-d29e-4ae9-af4b-90c7901f2e75.png)

![image](https://user-images.githubusercontent.com/297583/193828969-c87fdad7-1309-4ce9-84b8-81f9c6259d66.png)
