### ISSUE TITLE
Registracijos puslapyje nerodo sąlygų

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#172]
Registracijos puslapis papildytas nuoroda į sąlygų puslapį, kuris redaguojamas per Django CMS.

---

Registracijos puslapyje nerodo nuorodos į sąlygų puslapį. Sąlygų puslapis turi būti redaguojamas per Django CMS.

![Image](https://user-images.githubusercontent.com/297583/192574383-2fc96457-247b-4d3c-9179-066026b3ec36.png)

**Comment by adp-atea** [comment]
Patikrina ant devel šakos, sąlygos yra rodomos. Ši klaida buvo dėl jquery importavimo į template. Pataisyta su #93.
