### ISSUE TITLE
Sutvarkyti žymių lauko atvaizdavimą

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#199]
Pataisytas žymių lauko atvaizdavimas, kai žymės netelpa į vieną eilutę, laukas prasiplečia, kas sutalpintu visas žymes ir jos neišliptų iš lauko ribų.

---

https://github.com/atviriduomenys/katalogas/pull/165#discussion_r993158751

**Comment by adp-atea** [comment]
Nepavyko išsiaiškinti kodėl atvaizdavimas nėra korektiškas, sukūriau pull request su minimaliais atliktais pakeitimais.
