### ISSUE TITLE
Pritakymas neįgaliesiems

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#204]
Pritaikyti katalogo funkcionalumą ir išvaizdą neįgaliesiems remiantis pritaikymo neįgaliesiems tyrimo ataskaita.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/514

**Comment by adp-atea** [comment]
Sutvarkytos visos error ir alert tipo klaidos kurias parodė WAVE įrankis. 
Liko šios klaidos kurios turi būti pataisytos administratorius live tinklalapio versijoje:

/opening-tips/data-opening-tools/
	Alerts:
		(visos klaidos yra django cms editable tekste)
		Redundant link: (nuoroda nukreipia atgal į sarašą, o ta nuoroda yra po kaire panelyje)
		Justified text 26x:
/more/regulation/regulation_legal/
	Alerts:
		(visos klaidos yra django cms editable tekste, daug empty laukų, possible list naudoti numberable list, o ne ranka surašytus skaičius)
		Possible list:
		Justified text: (3 tušti text laukai apačioj lango.)
/more/regulation/regulation_strat/
	Alerts:
		(tvarkyti tekstą su django cms)
		Possible list
		Justified text x41
/more/reports/
	Alerts:
		(Nuorodos kaip ir logiškos, tačiau kartojasi,
		"title" ir "skaityti daugiau" identiškos nuorodos,
		turi būti viena, redaguoti adminui su django cms)
		Redundant links: (x25)
/blog/
	Alerts:
		(Tas pats kas "more/reports" skilty)
		Redundant links: (x11)

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).

**Comment by aurjas** [comment]
Padaryta su užduotimi #1064
