### ISSUE TITLE
Pasiruošimas projektui

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#211]
Parengta projekto infrastrūktūra: sukurtos kūrimo ir testavimo aplinkos, parengta įgyvendinimo strategija ir organizacinis planas, paskirti resursai.

---

Pasiruošimas projektui, užduočių koordinavimas.

**Comment by JuliusLADP** [comment]
Parengta projekto infrastrūktūra: sukurtos kūrimo ir testavimo aplinkos, parengta įgyvendinimo strategija ir organizacinis planas, paskirti resursai.
