### ISSUE TITLE
Duomenų rinkinio naudojimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#239]
Įgyvendintas projektų sąrašas, kuriuose naudojamas duomenų rinkinys, taip pat padaryta galimybė pridėti naują projektą prie duomenų rinkinio.

---

- [x] Panašiai, kaip https://github.com/atviriduomenys/katalogas/issues/191, reikia padaryti projektų sąrašą duomenų rinkinio details puslapyje, kur rodomas tabas „Projektai“ ir projektų sąraše rodomi visi projektai, kurie yra susieti su duomenų rinkiniu. Sąraše paspaudus ant projekto nuorodos patenkama į projekto peržiūros puslapį.

- [x] Duomenų rinkinio tvarkytojas ar koordinatorius ar is_(staff|superuser) turi teisę pridėti ir pašalinti projektus į sąrašą.

- [x] Jei naudotojas yra sukūręs bent vieną projektą, jam rodomas mygtukas pridėti projektą, paspaudus šį mygtuką, pateikiamas visų to naudotojo projektų sąrašas, sąraše, paspaudus ant projekto nuorodos, projektas pridedamas į sąrašą.

- [x] Projekto autorius, taip pat gali pašalinti projektus iš sąrašo, tačiau tik tuos, kurių autorius yra.

**Comment by adp-atea** [comment]
Implemented in task #233
