### ISSUE TITLE
Paskutinio atnaujinimo laikas nepertraukiamai atnaujinamiems duomenims

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#250]
Patikslintas paskutinio atnaujinimo datos laikas, nepertraukiamai atnaujinamiems duomenų rinkiniams.

---

Tais atvejais, kai duomenų atnaujinimo periodiškumas yra „Nepertraukimai“, tada paskutinio atnaujinimo laikas nebetenka prasmės, todėl paskutinio atnaujinimo laikas turėtu rodyti dabartinį laiką, o ne paskutinį metaduomenų atnaujinimo laiką. Arba turėtu rodyti „realiu laiku“.

![Screenshot from 2022-12-15 15-02-07](https://user-images.githubusercontent.com/297583/207866740-439d177d-9429-467f-bc4e-d9bce9c2e4b4.png)

**Comment by adp-atea** [comment]
This is fixed in #251
