### ISSUE TITLE
Poreikio gauti duomenis filtrai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#271]
Įgyvendinti poreikio gauti duomenis filtrai, kurie bus naudojami suvestinių parametrų funkcionalumui įgyvendinti ir padės vykdyti paiešką tarp pateiktų poreikių.

---

Poreikių sąraše https://test.data.gov.lt/requests/submitted/ padaryti filtrą, tokį pat, kaip ir duomenų rinkinių sąraše https://test.data.gov.lt/datasets/.

Reikalingo tokie filtrai:

- Poreikio būsena
- Rinkinio būsena
- Organizacija
- Valdymo sritis
- Kategorija **(išmesti)**
- Duomenų grupė**(išmesti)**
- Žymė (išmesti**(išmesti)**
- Registravimo data

Taip pat reikia padaryti paiešką.

Filtrus ir paiešką įgyvendinti analogiškai taip, kaip tai yra padaryta duomenų rinkinių sąraše, naudojant paieškos indeksą.

### Epic

- https://github.com/atviriduomenys/katalogas/issues/19

**Comment by aurjas** [comment]
Geraldai, gali šitą pažiūrėt? Patikrinau, tai filtrai yra tiek testinėje tiek ir gamyboje, tai kaip ir įgyvendinta užduotis, bet ar nėra kur užsilikę kode kokių likučių, kad nepadeployint į gamybinę ar kažko panašaus?
