### ISSUE TITLE
Galimybė saugoti daugiau nei vieną organizaciją prie poreikio

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#273]
`Request` lentelėje padaryti galimybę saugoti daugiau nei vieną organizaciją prie vieno `Request`. Padaryti schemos ir duomenų migracijas.

**Comment by JuliusLADP** [comment]
Pastaba. Jeigu poreikį organizacija nukreipė įgyvendinti kitai, sau nepasilikdama, tokiu atveju šio poreikio statusas pirmosios organizacijos  atžvilgiu yra Įvertintas (vietoje dabartinio "Patvirtintas"), bet tiksliau reikėtų įvardinti dabar neesančiu statusu "Perduotas"
Todėl reikalinga, kad atitinkamai veiktų Organizacijos filtras formoje https://test.data.gov.lt/requests/submitted/
