### ISSUE TITLE
Statistika pagal kategorijas ir institucijų grupes priklausančias ministrų (ministerijų) valdymo sritims

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#278]
Įgyvendinta statistika, pagal duomenų rinkiniams priskirtas kategorijas.

---

Pavyzdžiai iš duomenų atvėrimo pažangos ataskaitos:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/1fb15135-7c7c-4e0f-9033-ab423788a1a2)

Įgyvendinimas turi būti analogiškas kaip tai padaryta su [statistika pagal valdymo sritis](https://github.com/atviriduomenys/katalogas/issues/252).

Atsidarius peržiūrą pagal kategorijas, turi išlikti visi filtrai, o taip pat rodoma filtrų juosta, tokia pati, kaip ir duomenų rinkinių sąraše, išskyrus kategorijų filtrą.

**Comment by JuliusLADP** [comment]
Tituliniame lape prie Kategorijų ikonų būtų galima rodyti atvertų rinkinių skaičių . Aplinka (XXX)
