### ISSUE TITLE
Lankomumo statistika

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#282]
Padaryti integraciją su lankomumo statistikos sekimu, pavyzdžiui naudojant Google Analytics ar naudojant kitą analitikos paslaugų teikėją, pavyzdžiui Matomo.

**Comment by adp-atea** [comment]
Deployinant po poetry install, tikriausiai reikes padaryt migrate. Bent jau pas mane lokaliai reikejo, kai isirasiau django-extra-settings, atsirado migraciju lib`o viduj (turbut), bet commite nesimato sito.
