### ISSUE TITLE
Prašymų, rinkinių ir komentarų sekimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#29]
Kiekvienas registruotas portalo naudotojas, turi galimybę užsisakyti visus arba tam tikrus paklausimus dėl duomenų ir gauti informaciją apie naujus duomenų rinkinius. Užsisakant tokius pranešimus, turi būti nurodoma, kokie paklausimai domina:

- Pranešimai apie naujus duomenų rinkinius
- Pranešimai apie naujos prašymus atverti
- Pranešimai apie naujus komentarus

Papildomai turi būti pobūdžio pranešimus norima gauti:

- Pranešimai apie tam tikros kategorijos duomenų rinkinius
- Pranešimai adresuoti tam tikrai organizacijai ar valdymo sričiai

Kiekvieną kartą sukūrus naują duomenų rinkinį, prašymą gauti duomenis ar komentarą, naudotojas užsisakęs pranešimus gauna laišką su informacija apie naują duomenų rinkinį, prašymą ar komentarą.

Pavyzdžiui tam tikros įstaigos, kaip VDA gali užsisakyti visus pranešimus.

Tokie pranešimai keliauja į naudotojo užduočių sąrašą ir siunčiami nurodytu el. pašto adresu, kuris turi būti patvirtintas.

### Prenumeratos forma

Į prenumeratos formą patenkama iš

- Organizacijos
- Rinkinio
- Poreikio

peržiūros puslapių, paspaudžiant mygtuką „Prenumruoti“:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/9db3ec79-1f17-4aa7-986a-60f9256835f9)
-- https://test.data.gov.lt/orgs/269/

Paspaudus mygtuką „Prenumeruoti“ atidaroma forma, kurioje rodomas radio buttons sąrašas, su tokiais variantais:

- Nauji rinkiniai
- Nauji poreikiai ir pasiūlymai
- Nauji komentarai

Formoje, paspaudus „Prenumeruoti“, naudotojas įtraukiamas į prenumeratorių sąrašą ir gauna pranešimus, apie įvykius, kuriuos pažymėjo.

Kai prenumerata užsakyta, prenumeruojamo objekto peržiūros puslapyje mygtukas pasikeičia į „Atsisakyti prenumeratos“. Paspaudus „Atsisakyti prenumeratos“, prenumerata atšaukiama parodant config dialogo langą.

Jei pažymėta „Nauji komentarai“, tada siunčiami pranešimai tik apie rinkinius, jei pažymėta „Nauji rinkiniai“ ir apie poreikius, jei pažymėta „Nauji poreikiai“. Jei pažymėta tik „Nauji komentarai“ ir nepažymėta nei „Nauji rinkiniai“, nei „Nauji poreikia“, tada jokie pranešimai nesiunčiami ir tikriausiai reikėtu mesti klaidą, kad jei pasirinko komentarus, tai turi pasirinkti ir rinkinius ir/arba poreikius.

Jei prenumerata išsakyta iš organizacijos, kuri turi pavaldžių organizacijų, tada prenumerata galioja ir visoms pavaldžioms organizacijoms.

Absoliučiai visų organizacijų prenumeratą gali sukurti tik super administratorius, per Django admin aplinką, sukuriant prenumeratos įrašą rankiniu būdu, nurodant konkretų naudotoją, bet nenurodant nei organizacijos, nei rinkinio, nei poreikiu, tokiu atveju, tas naudotojas gaus pranešimus apie absoliučiai visus įvykius.

### Prenumeratų valdymas

Naudotojo profilyje:

https://test.data.gov.lt/user/profile/385/

Atsiranda kontekstinis meniu, su tokiais meniu punktais:

- Informacija - rodo profilio duomenis
- Prenumeratos - rodo prenumeratų sąrašą

Pasirinkus „Prenumeratos“ meniu punktą, rodomas sąrašas visų naudotojo prenumeratų, nurodant:

- Prenumeratos objekto pavadinimą (Organizacijos, Rinkinio ar Poreikio) pavadinimą.
- Trys žyminčios kas prenumeruojama (rinkinia, poreikiai, komentarai. Jei prenumerata aktyvi, tada rodomas žalios spalvos [fa-check-circle](https://fontawesome.com/v4/icon/check-circle), jei neaktyvi, tada rodoma pilkos spavlos [fa-minus-circle](https://fontawesome.com/v4/icon/minus-circle).
- Mygtukas „Atsisakyti“.

Paspaudus „Atsisakyti“, prenumerata panaikinama, prie pasirinkto objekto.

Jei naudotojas turi visų įvykių prenumeratą, kurią gali sukurti tik administratorius, tada naudotojo profilio prenumeratų puslapyje, tokia prenumerata nerodoma, ją gali panaikinti tik administratorius.

### Užduočių sąrašas

Jei atsitinka įvykis, kurį prenumeruoja naudotojas, sukuriamas įrašas naudotojo užduočių sąraše ir išsiunčiamas laiškas el. paštu.

Šiuo metu užduočių sąraše yra tokie tipai:

- Komentaras
- Prašymas
- Klaida

Atsiranda naujas tipas:

- Duomenų rinkinys

Dabar paprasti naudotojai, automatiškai prenumeruoja komentarus, jei  sukuria Poreikį ar užregistruoja klaidą. Greičiausiai dabar tai įgyvendinta ne kaip prenumerta, bet gal verta tai padaryti, kaip prenumeratą? Apjungimą matyt verta padaryti, kad naudotojas negautų dvigubų pranešimų, jei ir prenumeruoja ir buvo automatiškai sukurta prenumerata.

Užduočių sąraše, kiekvienai užduočiai, prenumeratos įvykio atveju, sukuriamos tokių tipų užduotys:

- Duomenų rinkinys - jei buvo sukurtas naujas duomenų rinkinys
- Prašymas - jei buvo sukurtas naujas prašymas
- Komentaras - jei buvo parašytas komentaras prie rinkinio ar poreikio

Jei naudotojas sukuria poreikį arba parašo komentarą, jis automatiškai prenumeruoja savo sukurto poreikio komentarus ir savo sukurto komentaro atsakymus. Tokios automatinės prenumeratos, naudotojo prenumeratų sąraše nerodomos ir jų atsisakyti negalima.

Užduotys atėjusios iš prenumeratos, neturi termino, todėl nereikia rodyti ar užduotis vėluoja.

###  Susiję

- https://github.com/atviriduomenys/katalogas/issues/42

**Comment by adp-atea** [comment]
Pašalinti šia dalį prenumeratos lange 

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/7a074343-f8e0-46ae-90a2-b1a27ae9f82a)
