### ISSUE TITLE
Statistika pagal atsisiuntimų skaičių

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#297]
Rodyti statistiką, pagal duomenų atsisiuntimų skaičių. Duomenų atsisiuntimus priimti per API, kurie būtų perduodami iš Saugyklos.

API, kuris priimtų atsisiuntimų statistiką, galėtu atrodyti taip:

```http
POST /partner/api/1/downloads HTTP/1.1

{
  "source": "get.data.gov.lt",
  "model": "datasets/example/Data",
  "format": "csv",
  "time": "2023-05-03 11:00",
  "requests": 10,
  "objects": 1000,
}
```

Atsisiuntimų duomenys pateikiami agreguoti, nurodant kiek buvo padaryta skaitymo užklausų ir kiek buvo atsisiųsta objektų, per valandą, kiekvienam modeliui, nurodant kokiu formatu duomenys buvo siunčiami.

`source`, `model`, `format` ir `time` (valandos tikslumu) turi būti unikalūs. Jei duomenys pateikiami su `source`, `model`, `format` ir `time` reikšmėmis, kurios jau buvo pateiktos anksčiau, esamas įrašas atnaujinamas, su naujais duomenimis.

Jei `requests` yra `0`, tada duomenys iš vis nesaugomi, o jei toks įrašas buvo, jis ištrinamas.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/298

**Comment by sirex** [comment]
Šis API turi būti apsaugotas su `ApiKey`, taip, kaip tai daroma kitose vietose. Turėtu būti praleidžiamas tik toks ApiKey, kurio naudotojas yra is_staff arba is_admin.

**Comment by sirex** [comment]
https://github.com/atviriduomenys/katalogas/blob/70c206231771db42dfda3ace7cffdec5fdc190be/vitrina/api/views.py#L599-L604

Ant visų šių laukų reikia uždėti `unique_together` constraint, priešingu atveju, gali būti sugadintas duomenų vientisumas ir statistikos publikavimas bus labai lėtas. Turint pakankamai daug duomenų statistikos lentoje, serveris turės dideles apkrovas publikuojant statistikos atnaujinimą.

Šioje vietoje paprasčiau naudoti [update_or_create](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update-or-create) funkciją.

Nors, kad greičiau veiktų, siūlyčiau, daryti tiesiog `create`, o gavus `IntegrityError`, pakartoti lėtesnį `update_or_create` variantą.

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
