### ISSUE TITLE
Saugyklos užklausų žurnalo skaitymas ir teikimas per katalogo API

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#298]
Padaryti scriptą, kuris skaitytų [Saugyklos žurnalo failus](https://spinta.readthedocs.io/en/latest/manual/accesslog.html#log-message-format) ir publikuotu agreguotus duomenis per Katalogo API (#297).

Skriptas turėtų veikti taip:

    python downloadstats.py -s get.data.gov.lt logs/accesslog-*.jsonl

Skriptas, turėtų įsidėmėti, kuriuos failus jau skaitė ir kiek eilučių iš kiekvieno failo jau nuskaityta. Paleidus tokią pačią komandą dar kartą, turėtų būti skaitomos tik tos failų eilutės, kurios dar nebuvo skaitytos.

Būsenos failas, turėtų būti saugomas `~/.local/share/vitrina/state.json` faile, kuris galėtų atrodyti taip:

```json
{
  "files": {
    "/path/to/file.jsonl": {
      "size": 1000,
      "line": 100,
      "offset": 1000,
    }
}
```

Čia `size` nurodo koks failo dydis, baitais, jei jis nepasikeitė, tada šio failo antrą kartą neskaitome. `line` nurodo eilutės numerė, kuris buvo paskutinį kartą skaitytas. `offset` nurodo baitų skaičių, ties kuriuo buvo baigtas skaitytas paskutinį kartą. Šie duomenys leis tęsti skaitymą, nuo tos vietos, kur buvo baigta paskutinį kartą, neskaitant viso failo iš naujo.

Skaitant žurnalo failus, turėtų būti pašalinamos užklausos, kurios yra darytos botų.

Tai galima padaryti taip:

```python
import user_agents

def parse_user_agent(agent):
    if isinstance(agent, str):
        return user_agents.parse(agent).browser.family

bots = {
    'SemrushBot',
    'BLEXBot',
    'Googlebot',
    'PetalBot',
    'crawler',
    'Googlebot-Image',
    'BingPreview',
    'bingbot',
    'archive.org_bot',
    'DataForSeoBot',
    'Adsbot',
}
```

Iš žurnaluose pateiktos `agent` informacijos, apie HTTP User-Agent antraštę, galima nustatyti agento šeimą `parse_user_agent` funkcijos pagalba ir toliau skaitant duomenis, ignoruoti visus įrašus, kurių `agent.family` yra viena iš `bots`.

Botų sąrašas turėtu būti pateikiamas konfigūraciniame faile `~/.config/vitrina/downloadstats.json`, kuris galėtų atrodyti taip:

```json
{
  "bots": ["SemrushBot", ...]
}
```

Papildomai, `~/.local/share/vitrinata/downloadstats.json` faile turėtų būti saugoma informacija, apie tai, kiek yra botų:

```json
{
  "agents": {
    "SemrishBot": 1000,
    "Firefox": 100
  }
}
```

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/297
- https://github.com/atviriduomenys/katalogas/issues/492

**Comment by sirex** [comment]
Parašiau testus, nes jų nebuvo:
- https://github.com/atviriduomenys/katalogas/pull/636

Parašius testsu patebėjau tokius trūkumus:
- Nenufiltruoja botų.
- Neteisingai nustato formatą
- Negrūpuojami kas valandą ir daromas siuntimas į Katalogo API, kiekvienam žurnalo įrašui, ko pasekoje, Kataloge išsaugomas tik paskutinis tos valandos įrašas, nes ankstesni perrašomi naujausio žurnalo įrašo duomenimis.
- https://github.com/atviriduomenys/katalogas/issues/297#issuecomment-1742432301

**Comment by adp-atea** [comment]
Agregacija vykdoma API pusėje.
Autorizacija kol kas užkomentuota, nes dar nėra implementuota.

**Comment by sirex** [comment]
Būtų gerai, kad agregacija vyktų skripto pusėje, nes kiekvienai žurnalo eilutei daryti po HTTP užklausą, kurios metu vėliau katalogo pusėje daryti agregaciją yra labai lėtas dalykas.

Be to, jei žurnalo skriptuose atsiranga klaida, kuri pataisoma ir reikia iš naujo perskaityti ir atnaujinti visus duomenis. Kaip tai padaryti, kai katalogo pusėje vyksta agregacija?

**Comment by sirex** [comment]
Matau, kad testai būvo atitaisyti, kad nebūtų daromas agregavimas kas valandą, nors testai buvo teisingi, agregavimas turi būti daromas kas valandą, o Katalogo pusėje API turėtu perrašyti statistiką, gautą iš konkretaus `source`.

Reikia atstatyti testus, taip, kaip jie buvo padaryti pradžioje ir pataisyti kodą, kad praeitų testai.

Skaitant žurnalo įrašus reikia agreguoti:

- pagal `txn`, kad būtų apjungti request ir response įrašai, kurie žurnale pateikiami atskirose eilutėse ir nebūtinai eina vienas paskui kitą, gali būti taip, kad response dalies nebus, jei užklausos apdorojimas baigėsi klaida
- pagal `time`, `format` ir `model`, kur `time` imama tik valandinė (YYYY-MM-DDTHH) dalis, kuri imama iš `response` dalies, jei `response` nėra, tada naudojam `request`, formuojant valandinę statistiką, skaitant žurnalą ir prieš siunčiant užklausą į katalogo API. Šioje valandos grupėje sumuojami `objects` ir `requests`.

Darant grupavimą, naudojame duomenų buferiavimą atmintyje, tokiu principu:

- `txn` atveju, atmintyje laikome iki 1000 žurnalo eilučių - buferis, jei atsiranda antroji `txn` pora, tada sutampanti `txn` eilutė iš buferio pašalinama, jei buferis pasiekia daugiau nei 1000 eilučių, tada prieš pridedant naują eilutę, seniausia yra pašalinama. Jei visos žurnalo eilutės turi iš eilės einančias `txn` poras, tada buferis visada bus tuščias, tiksliau į buferį bus pridedma request eilutė ir iš karto sekančios eilutės skaitymo metu, radus sutampančią response, buferis bus tuščias.
- `time`, `format` ir `model` atveju, buferyje agreguotas valandos trukmės grupes, grupę siunčiame tada, kai prasideda žurnalo eilutės, kurios yra 00:01 laiko, t.y. reikia duoti 60 sekundžių tolerancijos laiką, kadangi į žurnalą rašo skirtingi workeriai, kurie gali laiką žymas surašyti su tam tikru vėlavimu, todėl ir siūlau naudoti 60 sekundžių vėlavimų tolerancijai. Kai jau pradeda ateiti sekandčios valandos 00:01 antra minutė, tada darom užklausą į katalogo API ir išsiunčiam praeitos valandos statistiką pagal format ir model.

Dėl pačio katalogo API, siūlau perrašyti statistiką, pagal `source`, `time`, `format` ir `model`, darant prielaidą, kad skriptas daro agregavimą pagal `time`, `fromat` ir `model`. Tokiu atveju, jei skriptas bus taisomas ir reikės iš naujo perkrauti visą statistiką, tada katalogas gavęs naujus skaičius `source`, `time`, `format` ir `model` grupei, tiesiog perrašys naujus skaičius.

**Comment by adp-atea** [comment]
- Buferiavimas atmintyje, ko šiuo metu trūksta? Nuskaitoma 1000 eilučių ir txn'ai dedami į dictą, radus response jie iš dicto šalinami, o įrašas agreguojamas kitame dictionary, kurio įrašai vėliau postinami į API.

- Kaip tolerancija turėtų veikti? Kas turima omenyje, post'inti tik radus eilutę su 00:01 minute.

**Comment by sirex** [comment]
> Buferiavimas atmintyje, ko šiuo metu trūksta? Nuskaitoma 1000 eilučių ir txn'ai dedami į dictą, radus response jie iš dicto šalinami, o įrašas agreguojamas kitame dictionary, kurio įrašai vėliau postinami į API.

Tada lyg ir nieko netrūksta.

> Kaip tolerancija turėtų veikti? Kas turima omenyje, post'inti tik radus eilutę su 00:01 minute.

Kadangi daromas grupavimas kas valandą, o grupavimui reikalingas eiliškumas pagal grupę, tai logo faile, nors įrašai į žurnalą rašomi iš eilės, tačiau įrašus į žurnalą daro keli skirtingi workeriai vienu metu, todėl gali būti taip, kad vienas workeris įrašą padarys 00:01, o kitas užvėlavęs įrašą padarys 00:59. Jei nebus atsižvelgta, kad įrašai žurnale ražomi ne iš eilės, o su tarkim minutės vėlavimu, tada grupavimas veiks klaidingai. Tarkime bus tokios grupės:

- 00:59
- 00:01
- 00:59

Šioje vietoje, trečia grupė, perrašys pirmą ir gausim klaidingus duomenis.

Išbandžiau skriptą:

    scripts/downloadstats.py --target https://data.gov.lt get.data.gov.lt accesslog.json

Gavau tokią klaidą:

```python
Traceback (most recent call last):
  File "scripts/downloadstats.py", line 278, in <module>
    run(main)
  File "scripts/downloadstats.py", line 60, in main
    os.makedirs(os.path.dirname(state_file))
  File "os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
```

**Comment by sirex** [comment]
- [ ] Bandoma siųsti duomenis į serverį, bet visiškai ignoruojamas serverio atsakymas, šiuo atveju, serveris reikalavo autorizacijos, bet klaidos buvo ignoruojamos ir bandoma toliau siųsti duomenis, nepaisant to, kad niekas nenusisiunčia.

    Žiūrėti [Response.raise_for_status](https://docs.python-requests.org/en/latest/user/quickstart/#response-status-codes).
    https://github.com/atviriduomenys/katalogas/blob/70c206231771db42dfda3ace7cffdec5fdc190be/scripts/downloadstats.py#L272

- [ ] Šiuo metu nėra autorizuojamas klientas, kliento raktas turėtu būti saugomas `~/.config/vitrina/downloadstats.json` faile.

- [ ] Neišskleidžiamas namų katalogas, todėl konfigūracija ir duomenų failai skaitomi ir rašomi į `"~"` katalogą, žiūrėti [os.path.expanduser()](https://docs.python.org/3/library/os.path.html#os.path.expanduser) funkciją.

    https://github.com/atviriduomenys/katalogas/blob/70c206231771db42dfda3ace7cffdec5fdc190be/scripts/downloadstats.py#L59

- [ ] Taip pat, skaitant duomenis, gaunu tokią klaidą:

    ```python
    Traceback (most recent call last):
      File "scripts/downloadstats.py", line 286, in <module>
        run(main)
      File "scripts/downloadstats.py", line 118, in main
        find_transactions(name, d, final_stats, bot_status_file, bots_found, temp, transactions)
      File "scripts/downloadstats.py", line 154, in find_transactions
        txn = entry['txn']
    KeyError: 'txn'
    ```

**Comment by sirex** [comment]
https://github.com/atviriduomenys/katalogas/blob/6abf34714d9f1d811e38843e8608dc7b6cc1f035/scripts/downloadstats.py#L49

ApiKey turėtu būti skaitomas iš `~/.config/vitrina/downloadstats.json` failo.

Kiek suprantu, `temp` kintamasis niekada neatlaisvinamas:

https://github.com/atviriduomenys/katalogas/blob/6abf34714d9f1d811e38843e8608dc7b6cc1f035/scripts/downloadstats.py#L58

Negalima viso log failo nuskaityti į atmintį, nes log failas yra apie 20G, serveryje galim baigtis RAM atmintis. Galima turėtu buferį, bet nereikėtu voso log failo laikyti atmintyje.

**Comment by adp-atea** [comment]
Raktas skaitomas iš failo 90 eilutėje.
Skaitoma tik po 1000 eilučių, į temp dedamos agreguotos tranksakcijos, kurios baigus skaityt postinamos į API.
