### ISSUE TITLE
Duomenų struktūros keitimo istorija

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#3]
Kataloge turėtu matytis duomenų struktūros keitimo istorija. Tarkim, jei kažkas pageidauja pridėti naują lauką, tada struktūros keitimo istorijoje turėtu matytis, ar tas laukas buvo pridėtas ir kada jis buvo pridėtas. Šiuo metu tokios galimybės nėra ir net, jei kažkas buvo pridėta, nėra jokių pėdsakų ar įrodymų, kad tai buvo pridėta ir kada.

Duomenų struktūros keitimo istorija turėtu atitikti duomenų struktūros aprašo specifikaciją:

https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#strukturos-keitimas

**Comment by adp-atea** [comment]
Testuota rinkinyje: https://test.data.gov.lt/datasets/2090/ 
Istorija atvaizduojama nenuosekliai, pvz. Esu skiltyje "Informacija" ir paspaudžiu skiltį "Istorija":


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/5635b85e-ebf7-443d-9879-4bf5e82ea357)

Pridedu naują modulį, iš skilties "Struktūra" paspaudžiu skiltį "Istorija":


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/76034c92-1e24-4c27-b04e-c79939df909c)

Atvaizduojamas paskutinis padarytas veiksmas, o grįžus į "Informacija" -> "Istorija", naujo istorijos įrašo neatvaizduoja. 
Turėtų būti bendras sąrašas su visais pakeitimo įrašais.

**Comment by adp-atea** [comment]
1.. Padaryti, kad matytusi navigacija kaip pvz matosi čia: 


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/490f70f0-2ebe-4d38-9caf-7e622380eb4d)

Nes dabar neaišku kokio elemento istorija matosi

2.. Padaryti, kad paspaudus antrą karta ant istorijos tab'o atidarytų bendrą istoriją

3.. Sutvarkyti navigacija visuose tabuos'e

**Comment by adp-atea** [comment]
1.. Naviguojant iš skilčių Projektai, Planai į Istorija neprisideda navigacijos punktas (Projektai arba Planai)
2.. Pridedu naują planą -> atidarau istoriją (atvaizduoja atliktą pakeitimą, OK) -> spaudžiu istorija dar kartą (neatidaro bendros istorijos). Taip pat nerodo plano pridėjimo bendroje istorijoje.

**Comment by adp-atea** [comment]
1. Fixed
2. Manau galimai sutvarkytas ? Neatkartoju klaidos
3. Taip pat susirasinejant su Mantu, jis paminejo dar viena pastaba, t.y. naviguojant is "Planai" -> "Istorija", nerode sitos juostos
 

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/abbd3513-b84c-45e6-a31e-4823c9d10e66)

**Comment by adp-atea** [comment]
1.. nepataisyta
2.. paclickinus 2kart ant istorijos bendra istorija neatsidaro, nepataisyta
3.. Juosta rodo, bet informacijos kad buvo naviguota iš tab'o "Planai" nerodo (1 punktas)

**Comment by adp-atea** [comment]
> 1.. Naviguojant iš skilčių Projektai, Planai į Istorija neprisideda navigacijos punktas (Projektai arba Planai)

Su planais pataisyta, o su projektais nėra atskiros istorijos, t. y. einant iš Projektai į Istorija, atidaroma bendra duomenų rinkinio istorija, todėl navigacijos punkto nėra.
