### ISSUE TITLE
Struktūros aprašų sinchronizacija su GitHub

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#302]
Reikia struktūros aprašus sinchronizuoti tarp [atviriduomenys/manifest](https://github.com/atviriduomenys/manifest/) ir [data.gov.lt](https://data.gov.lt/).

Sinchronizavimas turi būti dvipusis:

1. Turi būti galimybė importuoti/anaujinti struktūros aprašus iš [atviriduomenys/manifest](https://github.com/atviriduomenys/manifest/) į [data.gov.lt](https://data.gov.lt/).
2. Ir turi būti galimybė eksportuoti struktūros aprašus iš [data.gov.lt](https://data.gov.lt/) į [atviriduomenys/manifest](https://github.com/atviriduomenys/manifest/).

Kad sinchronizacija veiktų reikia pasidaryti lentelę, kuri susieja duomenų rinkinius, pagal duomenų rinkinio kodinį pavadinimą.

Duomenų rinkinių lentelės pavyzdys:

| name | id |
| --- | --- |
| datasets/gov/rc/savivaldybe | 1286 |
| datasets/gov/vmi/gyventoju_pajamos | 1181 |

Čia `id` yra duomenų rinkinio unikalus identifikatorius data.gov.lt duomenų bazėje.

Dalis duomenų rinkinių jau turi struktūros aprašus, todėl dalį šių lentelių reikšmių galima gauti iš data.gov.lt duomenų, tačiau ne visi rinkiniai turi struktūros aprašus, o net jei ir turi, ne visi struktūros aprašai sutampa su tuo, kas yra GitHub.

Pirmiausiai reikėti padaryti eksportą iš data.gov.lt, taip, kad kiekvieno duomenų rinkinio struktūros aprašas, būtų išsaugotas atskirame faile, kurio katalogas ir pavadinimas sutampa su struktūros apraše įrašytu rinkinio kodiniu pavadinimu.

Dalis struktūros aprašų yra nestandartinės formos, pavyzdžiui pateikti, kaip PDF ar XLSX failai, dalis pateikti, kaip CSV failai, bet naudojant kabliataškius, reikšmėms atskirti. Visus tokius atvejus reikėtų pataisyti, taip, kad vėliau struktūros aprašus būtų galima suimportuoti be klaidų.

Galiausiai, padarius eksportą ir turin aukščiau minėtas lenteles, kur organizacijos ir duomenų rinkiniai yra susieti su kodiniais pavadinimais, reikia padaryti duomenų importą, kurio metu struktūros aprašai iš GitHub būtų importuojami į data.gov.lt, perrašant duomenų rinkinius, kurie anksčiau buvo GitHub ir atnaujinant organizacijų ir duomenų rinkinių kodinius pavadinimus.

### Susiję

- https://github.com/atviriduomenys/spinta/issues/239

**Comment by sirex** [comment]
Patikslinimas:

1. Reikia iš test.data.gov.lt ištraukti visus struktūros aprašus ir juos užkelti ant https://github.com/atviriduomenys/manifest/, taip kad struktūros aprašų failai būtų išsaugoti `datasets/gov/<org>/<dataset>.csv` pavadinimu, perrašant tai, kas yra GitHub.
2. Tada reikia sukurti naują branch https://github.com/atviriduomenys/manifest/ ir sutvarkyti visus struktūros aprašus, jei juose yra klaidų.
3. Sutvarkius visus struktūros aprašus juos supušinti ir sumerginti su master šaka.
4. Tada padaryti atvirkštinį dalyką iš GitHub visus struktūros aprašus išstumti į test.data.gov.lt, kur visi struktūros aprašai esantys katalogo db, bus perrašyti su tuo, kas yra GitHub.
5. Galiausiai reikia katalogo db esančius struktūros aprašų failus suimportuoti kaip atskirus Mode, Property, ... objektus.

Tam reikalingas skriptas arba keli skriptai, kurie bus leidžiami atnaujinant duomenis test.data.gov.lt. Tai reiškia deploy mentu bus daroma kažkas panašaus į tai:

- `./script/manifest-export.py path/to/manifest/repo`
- rankiniu būdu sutvarkoma, kas neveikia, būtų gerai, kad skriptas atsimintu, kas jau buvo sutvarkyta ir paliktu github versiją, vietoj to, kad perrašytu su netvarkinga katalogo db versija.
- `find datasets -iname "*.csv" | xargs spinta check` - patikrinama ar nėra klaidų, jei yra taisoma
- `./scripts/manifest-import.py path/to/manifest/repo` - importuojami sutvarkyti struktūros aprašai atgal į katalogą, perrašant viską, kas yra kataloge ir tuo pačiu struktūros aprašai importuojami ir kaip Mode, Property, ... objektai.

Toks dalykas, bus kartojamas daug kartų, duomenys gali keistis tiek github repo, tiek katalogo db ir jie bus nuolat atnaujinami, kol prieisim galutinio veikiančio varianto, nebeliks jokių klaidų ir bus galima pakeisti seną katalogo versiją su nauja.

**Comment by sirex** [comment]
Dar vienas patikslinimas.

### manifest-export skriptas

Skripto komandos pavyzdys:

    ./scripts/manifest-export.py path/to/manifest/repo

Kur `path/to/manifest/repo` yra kelias iki https://github.com/atviriduomenys/manifest/ Git repozitorijos klono.

Skriptas jungiasi tiesiogiai prie Katalogo duomenų bazės ir eksportuoja tokius dalykus:

#### orgs.csv

Eksportuojama organizacijų trumpinių lentelė, kuri atrodo taip:

id | name | title
--- | --- | ---
269 | ivpk | Informacinės visuomenės plėtros komitetas |

- `id` - Katalogo `Organization` id.
- `name` - struktūros apraše naudojamas organizacijos kodinis pavadinimas (trumpinys), jei tokio lauko nėra kataloge prie `Organization`, tai reikia jį pridėti.
- `title` - Organizacijos pavadinimas.

Eksportuojam tik tas organizacijas, kurios turi bent vieną duomenų rinkinį. Jei organizacija neturi nei vieno duomenų rinkinio nei Kataloge, nei Github, tokios organizacijos šioje lentelėje neturėtu būti.

Darant pakartotinį atnaujinimą, jei `orgs.csv` failas jau yra repozitorijoje, tada neperrašom lentelės, bet išlaikom tai, kad įrašyta į `name` stulpelį, nes `name` stulpelis bus pildomas rankomis, jei organizacijos kodinis pavadinimo nebus įmanoma nustatyti iš kataloge esančio struktūros aprašo.


#### datasets.csv

Eksportuojam duomenų rinkinių sąrašą, lentelė atrodo taip:

id | name | title | org | checksum
--- | --- | --- | --- | ---
1223 | datasets/gov/ivpk/adp/catalog | Atvirų duomenų katalogo duomenys | Informacinės visuomenės plėtros komitetas | 12eb3eb806b9fa5cbf39cf09f8675191b025b836

- `id` - Katalog `Dataset` id.
- `name` - pilnas duomenų rinkinio kodinis pavadinimas įrašytas struktūros aprašo `dataset` stulpelyje
- `title` - Duomenų rinkinio pavadinimas
- `org` - Duomenų rinkinio organizacijos pavadinimas (padės geriau suprasti, kas per rinkiniai ir kam priklauso)
- `checksum` - Išsaugom struktūros aprašo įkelto į Katalogą SHA1 sumą, kad žinotume, ar struktūros aprašas kataloge pasikeitė nuo paskutinio atnaujinimo.

Šioje lentelė turi atsirasti duomenų rinkinių sąrašas, tiek iš Katalogo, tiek iš  Github repozitoriume esančių failų. Jei Github faile `dataset` stulpelyje esantis pavadinimas sutampa su Katalogo struktūros aprašo `dataset` stulpelyje esančiu pavadinimu, tada lentelėje turi būti viena eilutė.

Jei nesutampa, tada saugom eilutę, bet Katalogo `id` arba bet Github `name`, tokius atvejus reikės tvarkyti rankiniu būdu.

Eksportuojam tik tuos duomenų rinkinius, kurie turi, bent vieną duomenų rinkinį arba kurie yra Github repo.

Darant atnaujinimą, jei `datasets.csv` failas Github repo jau yra, tada jo neperrašome, o atnaujiname išlaikydami rankiniu būdu padarytą susiejimą, atnaujinam tik `checksum`, jei jis pasikeitė.

Jei pasikeitė `checksum` į ekraną išvedam informaciją, koks failas pasikeitė.


#### datasets/gov/{org}/{dataset}.orig

Eksportuoja Kataloge saugomus struktūros aprašus ir vadovaujantis `datasets.csv` faile esančia informacija išsaugo struktūros aprašą taip, kaip nurodyta `datasets.csv` lentelės `name` stulpelyje, pridedant `.orig` galūnę.

Kadangi Kataloge struktūros aprašai gali būti saugomi nebūtinai CSV formatu, naudojame `.orgi` galūnę, o ne `.csv`. `.csv` galūnė pridedama tik standartinio formato struktūros aprašams, nes jie yra tikrinami naudojant `**/*.csv` glob.

Saugome originalų failą, kuris yra kataloge, jis nebus keičiamas ir nebus traukiamas į Git repo.


#### datasets/gov/{org}/{dataset}.csv

Originalūs struktūros aprašai `datasets/gov/{org}/{dataset}.orig` taip pat išsaugomi ir `datasets/gov/{org}/{dataset}.csv` pavadinimu, bet tik tuo atveju, jei `datasets/gov/{org}/{dataset}.csv` failas neegzistuoja, jei toks failas egzistuoja, jo neperrašome, tačiau išvedame į ekraną informaciją, jei pasikeitė šio failo `checksum` iš `datasets.csv` lentelės.

Github repo yra naujausi ir teisingiausi struktūros aprašų failai, todėl jei failas tokiu pavadinimu egzistuoja, jis turi būti paliekamas.

Jei toks failas neegzistuoja, tada sukuriam failą, tačiau gali būti, kad failą reikės taisyti, gali būti, kad pateiktas ne CSV, o PDF, arba paprastas tekstinis failas, gali būti, kad pateiktas CSV failas, bet nestandartinės struktūros, barba standartinės struktūros CSV failas, bet CSV atskirtas ne kableliais, o kabliataškiais ir pan. Visus tokius failus reikia sutaisyti rankiniu būdu, kad praeitu [Github CI](https://github.com/atviriduomenys/manifest/blob/master/.github/workflows/spinta.yml).



Eksportuoja kataloge saugomus struktūros aprašų failus, kiekvienas duomenų rinkinys turi po atskirą struktūros aprašo failą saugomą `datasets/gov/{org}/<dataset>.csv` pavadinimu, kur `{org}` yra organizacijos trumpinys ([organizacijų trumpinių sąrašas](https://github.com/atviriduomenys/manifest/tree/master/datasets/gov)), `{dataset}` yra duomenų rinkinio kodinis pavadinimas, tiek `{org}`, tiek `{dataset}` kataloge ir github yra saugomi struktūros aprašo lentelės `dataset` stulpelyje, pavyzdžiui [aaa/atlieku_tvarkymas](https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/aaa/atlieku_tvarkymas.csv) atveju `dataset` stulpelyje įrašyta `datasets/gov/aaa/atlieku_tvarkymas`, tai `{org}` yra `aaa`, o `{dataset}` yra `atlieku_tvarkymas`.


### manifest-import skriptas

Skripto komandos pavyzdys:

    ./scripts/manifest-import.py path/to/manifest/repo

Kur `path/to/manifest/repo` yra kelias iki https://github.com/atviriduomenys/manifest/ Git repozitorijos klono.

Šis skriptas daro tokius dalykus:

- Katalogo duomenų bazėje atnaujina `Organization` modelio kodinius pavadinimus, pagal tai, kaip nurodyta `orgs.csv` faile. Jei `Organization` modelis neturi organizacijos kodinio pavadinimo, reikia jį pridėti.
- Katalogo duomenų bazėje atnaujina `Dataset` modelio kodinius pavadinimus, pagal tai, kaip nurodyta `datasets.csv` faile. Jei `Dataset` modelis neturi kodinio pavadinimo lauko, reikia jį pridėti.
- Kataloge kiekvienam duomenų rinkiniui vadovaujantis `datasets.csv` faile nurodytu `id` įkeliame struktūros aprašai iš Github repo esančių `datasets/gov/{org}/{dataset}.csv` failų, perrašant, jei struktūros aprašas yra arba įkeliant struktūros aprašą, jei jo nebuvo.
- Kataloge, kiekvienam duomenų rinkiniui, struktūros aprašai įkeliami ne tik kaip failai, bet ir kaip duomenyus, t.y. atliekant pilną struktūros aprašo import į DB, žiūrėti https://github.com/atviriduomenys/katalogas/issues/290.

Šis skriptas gali būti leidžiamas daug kartų.

**Comment by sirex** [comment]
```
$ poetry run python scripts/manifest_export.py --manifest-path ../manifest
django.db.utils.ProgrammingError: column organization.name does not exist
LINE 1: ...anization"."image_id", "organization"."provider", "organizat...
```

Gaunu tokią klaidą, panašu, kad trūksta migracijų?

**Comment by sirex** [comment]
Ar ši klaida jau pataisyta?

**Comment by adp-atea** [comment]
Taip, migracija pridėta vakar.
