### ISSUE TITLE
Naudotojų informavimas apie struktūros pasikeitimus

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#31]
Duomenų naudotojai, kurie norėtu būti informuoti apie duomenų struktūros pasikeitimus, turėtu būti užsiregistravę portale ir užregistravę savo projektą, kuriame naudoja duomenis ir nurodę, kokius duomenis naudoja. Tai padarius, kai keičiama duomenų struktūra, visi projektai bus informuoti apie planuojamus pakeitimus, jei projekte yra naudojami keičiami laukai.

Projektai turėtu būti registruojami panaudojimo atvejų skiltyje.

Projektas gali užsisakyti informacijos siuntimą apie pasikeitimus arba jos atsisakyti.

### Priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/37

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/42
- https://github.com/atviriduomenys/katalogas/issues/37

**Comment by adp-atea** [comment]
Gal galite patikslinti kaip tiksliai viskas turėtų atrodyti?

**Comment by sirex** [comment]
Sukūrus naują versiją

- https://github.com/atviriduomenys/katalogas/issues/37

Sukuriama Užduotis ir išsiunčiamas laiškas visiems Panaudojimo atvejo autoriams, kurių Panaudojimo atvejai yra susieti su duomenų rinkiniu, kurio nauja struktūros versija yra sukurta.

Užduotyje ir laiške, turi būti pateikta nuoroda į naujos versijos peržiūros puslapį.
