### ISSUE TITLE
Kelių organizacijų apjungimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#32]
Turi būti galimybė apjungti kelias organizacijas į vieną, panaikinant kitas organizacijas ir paliekant vieną. Apjungimo metu, turi būti perkeliami visi duomenų rinkiniai iš kitų organizacijų į vieną.

Toks funkcionalumas reikalingas, kai per klaida sukuriamos kelios organizacijos, kai organizacijos dubliuojamos iš skirtingų katalogų arba, kai organizacijos reorganizuojamos ir apjungiamos.

**Comment by adp-atea** [comment]
Komentaras neauktualus
