### ISSUE TITLE
DataService

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#320]
Dalis funkcionalumo susijusio su `DataService` turėtu būti įgyvendinta https://github.com/atviriduomenys/katalogas/issues/332 užduoties apimtyje. Ši užduotis tik apie tai, ko trūksta iki pilno DataService įgyvendinimo.

Data Service duomenų rinkinio peržiūros puslapyje nerodome distribucijų (Duomenų šaltinių), kadangi Data Services jų neturi.

### Duomenų šaltinis

Duomenų šaltinio formoje

![image](https://github.com/atviriduomenys/katalogas/assets/297583/cf00758e-b80e-4a8c-bad0-1865d8ef7cbb)

Rodykle pažymėtoje vietoje turi atsirasti `DataService` select list pasirinkimas, kuriame rodomi `DataService` objektai, kurie yra priskirti duomenų rinkiniui (žiūrėti #332). Šis laukas turėtu būti neprivalomas. Laukas atitinka [dcat:accessService](https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_access_service).

### Priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/332

### Resources

- https://www.w3.org/TR/vocab-dcat-3/#Class:Data_Service
- https://www.api.gov.uk/nd/#nhs-digital
- https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.1/usageguide-dataset-distribution-dataservice.md

### Epic

- https://github.com/atviriduomenys/katalogas/issues/21

**Comment by adp-atea** [comment]
1. Gal reikėtų pervadinti lauką į lieuvių kalbą?
2. Nėra reikšmių lauke, tiksliau nežinau kaip priskirti dataservice objektus, kad patikrinti

@sirex priskiriu jums, kadangi nežinau ar tikrai klaidos čia

**Comment by sirex** [comment]
> Gal reikėtų pervadinti lauką į lieuvių kalbą?

Kurį lauką, gal galite pateikti nuorodą, kur žiūrite?

> Nėra reikšmių lauke, tiksliau nežinau kaip priskirti dataservice objektus, kad patikrinti

Kuriame lauke? Gal galite pateikti nuorodą, jei nėra nuorodos, nežinau apie kalbate, nes nematau to, ką matote savo ekrane.

**Comment by adp-atea** [comment]
1. Išvesri į lt kalbą lauką DataService

DataService lauką duomenų šaltinio pridėjimo lange

https://test.data.gov.lt/resource/14242/change


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/fc142b19-4f6e-461c-99b4-89a4a8faaff6)

2. Dėl 2 punkto, matau buvo registruota klaida [#395](https://github.com/atviriduomenys/katalogas/issues/395), tai kaip ir aišku.

**Comment by adp-atea** [comment]
Abu pataisyti prie #395.
