### ISSUE TITLE
Netrumpinti teksto filtruose

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#329]
Šiuo metu filtruose pavadinimai yra trumpinami

![image](https://github.com/atviriduomenys/katalogas/assets/297583/02b5d9b4-621c-4bfa-a9b8-519ad95bdf53)

Dėl to sunku naudotis filtru, nes nesimato pilno pavadinimo.

Todėl filtruose, pavadinimų nereikėtų trumpinti:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/87bb28be-70ed-481b-9d03-dc548b875caa)

### Epic

- https://github.com/atviriduomenys/katalogas/issues/55

**Comment by adp-atea** [comment]
Panašu, kad tai jau padaryta su stiliaus pakeitimais.
