### ISSUE TITLE
Prašymo adresavimas ministerijos sričiai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#33]
Teikiant prašymus, pirmiausia reikėtų pasirinkti  ministerijų sritį, o tik po to instituciją. Jei pasirinkti tik ministerijų sritis, tada pranešimas apie prašymą siunčiamas ministerijos koordinatoriui ir ministerijos koordinatorius suranda, kuriai įstaigai priskirti prašymą.

## Priklauso nuo

- #58

**Comment by adp-atea** [comment]
Formoje turi atsirasti papildomas laukas - ministerija?
Ar leisti pasirinkti vieną iš dviejų variantų: ministerija ir organizacija, ar galimi abudu pasirinkimo variantai?

**Comment by sirex** [comment]
Jau įgyvendinta.
