### ISSUE TITLE
Histogramos atvaizdavimas kiekybiniams ir datos laukams

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#340]
Kiekybiniams ir datos laukams rodomas paprasta stulpelinė diagrama (histograma), kur duomenys gaunami iš [Summary for numeric and date types](https://github.com/atviriduomenys/spinta/issues/452) užduotyje įgyvendinto API.

Tokia vizualizacija taikoma šiems tipams:

- `boolean`
- `integer`
- `number`
- `string` (tik jei yra `enum`)
- `datetime`
- `date`
- `time`
- `money`
- `ref` (rodom tik top 10 reikšmių)

Duomenys turi `bin` ir `count` atributus. `bin` atvaizduojam X ašyje, o `count` Y ašyje.

`bin` reikšmė priklauso nuo duomenų lauko tipo ir tai yra histogramos reikšmių grupės vidurinioji dalis. Pavyzdžiui jei histogramos grupės dydis yra 100, tai `bin` reikšmė 50, reiškia, kad tai yra grupė nuo 0 iki 100. Grupės dydis paskaičiuojamas automatiškai, priklausomai nuo reikšmių pasiskirstymo.

Viso grąžinama 100 grupių.

Jei duomenų laukas yra `date` arba `datetime`, tada X ašyje atvaizduojama laiko juosta.

Pavyzdys, kaip tai turėtu atrodyti:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/25a887d9-c917-4f87-9102-a347518a4910)

https://www.chartjs.org/docs/latest/getting-started/usage.html

Jei duomenų laukas turi `enum` arba `boolean`/`ref` atveju, rodome horizontalią stulpelinę diagramą, kur `enum`/`boolean`/`ref` reikšmės rodomos kairėje, Y ašyje, o objektų skaičius su tokia `enum`/`boolean`/`ref` reikšme rodomas X ašyje. Gal būt galima padaryti kažką kaip čia?

![image](https://github.com/atviriduomenys/katalogas/assets/297583/e9656e1d-042b-4ffa-b8ea-96168b20da49)

Tada bus išlaikytas didesnis vientisumas? Bet tai galioja tik `enum`/`boolean`/`ref` atveju. Kitais atvejais, geriau rodyti standartinę stulpelinę diagramą, kuri dažniausiai naudojama histogramose.

### Nice to have

Būtų geria padaryti nuorodą, kur paspaudus ant konkretaus bucket, būtų atidaromas modelio duomenų peržiūros puslapis, su filtru, kuris atfiltruoja tik to bucketo duomenis, ant kurio buvo paspausta.

### Susiję

- https://github.com/atviriduomenys/spinta/issues/452
- https://github.com/atviriduomenys/katalogas/issues/293

### Epic

- https://github.com/atviriduomenys/katalogas/issues/52

**Comment by adp-atea** [comment]
Pastebėjimai iš spintos summary veikimo:
1. jei yra integer tipas ir priskirtos enum reikšmės, summary grąžina ne galimas enum reikšmes, o apskaičiuotus vidurkius, pvz. https://get.data.gov.lt/datasets/gov/bpc/pagalbos_skambuciai/IvykiuKoordinates/:format/json?summary(%27menuo%27) ar taip ir turi būti?
2. ref tipui grįžta sutrumpinti uuid, ar tai gerai?

Nuorodos į duomenų peržiūrą kol kas nedarytos.

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
