### ISSUE TITLE
Duomenų šaltinio puslapis

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#342]
![image](https://github.com/atviriduomenys/katalogas/assets/297583/abddd6e0-7c32-49b3-9a1d-d37d5457bf18)

Iš Duomenų rinkinio puslapyje esančio Duomenų šaltinių sąrašo, paspaudus ant šaltinio pavadinimo patenkama į duomenų šaltinio puslapį. Jei duomenų šaltinis neturi pavadinimo rodome „(pavadinimas nenurodytas)“, kad veiktų nuoroda, jei šaltinis neturi pavadinimo.

Atidarius duomenų šaltinio puslapį „Informacija“ yra pažymėtas, kaip aktyvus meniu punktas, viršutiniame puslapio meniu. Paspaudus ant „Informacija“ iš duomenų šaltinio puslapio, patenkama atgal į duomenų rinkinio informaciją.

Duomenų šaltinio puslapyje rodome:

- Mygtukas, redaguoti duomenų šaltinį, rodomas tik rinkinio tvarkytojams ar aukštesnes teises turintiems naudotojams.
- Duomenų atsisiuntimo nuoroda ir bendra informacija, tokia kaip teritorija, periodo pradžia ir pabaiga, dydis, formatas, kada publikuota ir kada paskutinį kartą atnaujinta, aprašymas.
- Parametrų sąrašas, jei šaltinis turi parametrus ir mygtukas, naujam parametrui pridėti. Mygtuką rodome tik tvarkytojams, koordinatoriams ar administratoriams.
- Duomenų šaltinio modelių sąrašas ir mygtukas, naujam modeliui sukurti, tame šaltinyje. Mygtukas rodomas tik tvarkytojui, koordinatoriui ar administratoriui.
- Komentarai, rodomi tik šaltinio komentarai.  Galimybė pateikti naują komentarą, konkrečiam šaltiniui.

Duomenų šaltinio formoje atsiranda tokie nauji laukai:

- `name` - Duomenų šaltinio kodinis pavadinimas, neprivalomas, strukūtors apraše atitinka `resource`, jei nenurodytas, generuojamas automatiškai `resource{n}`, kur `{n}` yra duomenų šaltinio numeris duomenų rinkinyje, pradedant nuo 1. Norint gauti sekanti numerį, imamas didžiausias numeris ir prie jo pridedamas 1.
- `access` - Prieigos lygmuo, neprivalomas, atitinka `resource.access`, select list su tokiomis galimomis reikšmėmis: https://atviriduomenys.readthedocs.io/dsa/access.html.

### Epic

- #52

**Comment by adp-atea** [comment]
Komentaras nebeaktualus
