### ISSUE TITLE
Parametrizacija

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#344]
Parametrizacija naudojama, kai duomenų šaltinis (`resource`) arba modelis (`model`) turi parametrų. Ar šaltinis arba modelis turi parametrų, nurodoma šaltinio arba modelio formoje, pažyint checkbox, kad šaltinis ar modelis yra parametrizuoti.

Jei šaltinis ar modelis yra parametrizuoti, tada peržiūros puslapiuose rodomas naujas sąrašas su galimais parametrais, prie sąrašo rodomas mygtukas „Naujas parametras“.

Naujo parametro formoje rodomi tokie laukai:

- `name` - Parametro kodinis pavadinimas, privalomas, taikomos tokios pat taisyklės kaip ir [duomenų lauko forms](https://github.com/atviriduomenys/katalogas/issues/333) `name` laukui.
- `source` - Šaltinis, neprivalomas, paprastas tekstinis laukas, atitinka `param.source`, nurodomas duomenų šaltinis arba naudojamas kaip pirmas argumentas funkcijai, nurodytai `param.prepare` lauke.
- `prepare` - Formulę, privalomas, nurodoma formulė, tikrinama ar formulė teisinga, verčiant ją į AST.
- `title` - Pavadinimas, neprivalomas, nurodoma parametro pavadinimas „žmonių kalba“.
- `description` - Aprašymas, neprivalomas, nurodomas išsamesnis parametro aprašymas, Markdown formatu.

### Epic

- https://github.com/atviriduomenys/katalogas/issues/52

### Informacija

- https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#parametrai

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/334

### Priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/342

**Comment by adp-atea** [comment]
Komentaras nebeaktualus
