### ISSUE TITLE
Švieslentės organizacijų ir poreikių puslapiuose

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#350]
Padaryti analogiškas švieslentes organizacijų ir poreikių dalyse, kaip padaryta duomenų rinkinių sąraše. Tik organizacijų sąraše atskaitos taškas yra viena organizacija, o poreikių sąraše, atskaitos taškas yra vienas poreikis.

Prie organizacijų valdymo sričių švieslentės papildomai atsiranda du papildomi rodikliai:

- Koordinatorių skaičius valdymo srities organizacijose.
- Tvarkytojų skaičius valdymo srities organizacijose.

Įgyvendinama alternatyvaus rodiklių (organizacijų sk/koordinatorių sk./tvarkytojų sk.) pasirinkimo ir grafinio atvaizdavimo galimybė pagal valdymo sritis

Prie poreikių, vietoj duomenų rinkinių būsenos, rodoma poreikio būsena.

### Epic

- #19

**Comment by adp-atea** [comment]
1.. Prie organizacijos valdymo sryčių trūksta rodiklių:

- Koordinatorių skaičius valdymo srities organizacijose.
- Tvarkytojų skaičius valdymo srities organizacijose.

2.. O prie poreikių tik registravimo datos yra, taip ir tūrėtų būti?

**Comment by JuliusLADP** [comment]
Dabar Poreikiuose  filtrai yra bet neveikia grafikai

**Comment by adp-atea** [comment]
Gal galite surašyti, kokie reikalingi rodikliai Organizacijų ir Poreikių atvejais?

**Comment by sirex** [comment]
### Organizacijos

- Valdymo sritis
  - Organizacijų skaičius (pavaldžių)
  - Koordinatorių skaičius
  - Tvarkytojų skaičius


### Poreikiai

- Poreikio būsena
  - Poreikių skaičius
  - Poreikių skaičius (neatsakytų) - nei viena organizacija nėra pakeitusi būsenos
  - Poreikių skaičius (vėluojančių)

- Duomenų rinkinio būsena - manau galima nukreipti į [/datasets/stats/status/?indicator=request-count](https://test.data.gov.lt/datasets/stats/status/?indicator=request-count)

- Organizacija
  - Poreikių skaičius
  - Poreikių skaičius (neatsakytų) - konkreti organizacija nepakeitė būsenos
  - Poreikių skaičius (vėluojančių)

- Valdymo sritis
  - Poreikių skaičius
  - Poreikių skaičius (neatsakytų) - nei viena organizacija nėra pakeitusi būsenos
  - Poreikių skaičius (vėluojančių)

- Pateikimo data
  - Poreikių skaičius
  - Poreikių skaičius (neatsakytų) - nei viena organizacija nėra pakeitusi būsenos
  - Poreikių skaičius (vėluojančių)

Poreikių skaičius (neatsakytų) skaičiajami poreikiai, kurių statusas yra „Pateiktas“.

Poreikių skaičius (vėluojančių) - skaičiuojami poreikiai, kurie įtraukti į planą ir plano užduoties terminas jau pasibaigęs. Jei bent vienos užduoties susietos su poreikius terminas pasibaigęs ir užduotis nėra uždaryta, laikoma, kad poreikis vėluoja.

**Comment by adp-atea** [comment]
Praleista: 
Duomenų rinkinio būsena - manau galima nukreipti į [/datasets/stats/status/?indicator=request-count](https://test.data.gov.lt/datasets/stats/status/?indicator=request-count)

**Comment by adp-atea** [comment]
Ar čia yra racijos dėti šią nuorodą? Nes iš poreikių puslapio bus nueitą į duomenų rinkinių puslapį. @sirex
