### ISSUE TITLE
Modelio kodinio pavadinimo prefiksas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#362]
![image](https://github.com/atviriduomenys/katalogas/assets/297583/ffb0fb73-e4aa-40a6-a4d7-a69d4bb4cf50)

Modelio formoje, nurodžis kodinį pavadinimą `Table`, saugant modelio pavadinimas turi būti konstruojamas su duomenų rinkinio prefiksu. Dabar taip nėra:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/060dccb0-4432-4af6-b699-8536302ca184)

Pilnas modelio kodinis pavadinimas turėtu būti ne `Table`, o `datasets/gov/org/dataset/Table`, kur `datasets/gov/org/dataset` yra duomenų rinkinio kodinis pavadinimas.

Kad tai veiktų duomenų rinkinio kodinis pavadinimas turi būti pateikiamas duomenų rinkinio formoje.

Redaguojant modelį, formoje modelio kodinis pavadinimas turi būti rodomas be duomenų rinkinio prefikso.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/326
- https://github.com/atviriduomenys/katalogas/pull/361

**Comment by adp-atea** [comment]
Užklausa vis dar sudaroma be prefikso 

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/3032d3e0-a025-48c5-9107-2a388a8a175c)

**Comment by adp-atea** [comment]
Ar buvo redaguotas duomenų rinkinys ir pridėtas "Kodinis pavadinimas"? Nes lokaliai kaip ir viskas veikia.
