### ISSUE TITLE
Klaidų pranešimų suvienodinimas

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#365]
Kuriant naują naudotoją į akis krenta, tai, kad neužpildžius privalomus laukus rodomi pranešimai anglų kalba (jei klientui tinka galima palikti) Tokie patys pranešimai anglų kalba yra ir kituose languose.

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/d7bfb927-6a06-4316-8a08-8c962b49f9a7)

Taip pat nekaip atrodo, kai vieni pranešimai surašyti lietuvių kalba, o kiti anglų kalba, reikia suvienodinti.

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/192aa21b-b763-4163-91e8-d2b46d56a843)

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/a3fccc59-2fd0-4e9b-884c-95585d891ce1)

Taip pat vieni laukai yra apvedami raudonu rėmeliu, o kiti ne (matosi pirmoje foto)

**Comment by adp-atea** [comment]
Viskas ok, tik reikėtų angliškus vertimus padaryti 

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/c7a93f62-9763-4dd0-8561-cb98f0529bcd)

**Comment by adp-atea** [comment]
Galbūt geriau būtų visus vertimus daryti pabaigoje ir tam sukurti atskirą užduotį? Nes neatrodo logiška versti vis po kelias frazes konkrečioms užduotims.

**Comment by sirex** [comment]
Siūlyčiau vertimus daryti iš karto, tai nėra labai sudėtinga. Problema yra tame, kad neaišku kas yra tiesiog neišversta, o kas iš vis net nėra pažymėta vertimui. Testavimo metu, tokius nepažymėtus vertimui atvejus galima išgaudyti tik tuo atveju, jei viskas kas verčiama yra išversta.

Todėl siūlyčiau vis dėl to padarius užduoti iš karto ir išversti viską, kas nėra išversta. Arba vertimą daryti reguliariai, karą per savaitę?
