### ISSUE TITLE
Vertimai

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#367]
Naujo naudotojo kūrimo lange, kai kurie klaidų pranešimai yra neišversti

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/0cfa96fd-3d70-4081-9c03-e2b3c9fbe2a9)

Atidarius naudotojo profilį jo informacija rodoma anglų kalba, nors kalba pasirinkta LT

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/a5179fec-d5b3-4b3c-b042-30941d13e873)

____________________________________________________PAPILDYMAS 07-11

VIISP prisijungimo lange

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/061271af-d945-492f-bb82-364dbe0d5039)

**Comment by adp-atea** [comment]
Dabar pakeitus į anglų kalbą lieka lietuviškai šios vietos

**Comment by adp-atea** [comment]
Nes nėra padaryti vertimai, bet siūlyčiau juos daryti visus bendrai su atskira užduotimi.

**Comment by sirex** [comment]
https://github.com/atviriduomenys/katalogas/issues/365#issuecomment-1684028901

**Comment by sirex** [comment]
Reikia peržiūrėti visus vertimus ir išversti į Anglų kalbą:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/83d7ba76-4dca-4c00-bc47-ac3cff5774c4)

Čia tik keli pavyzdžiai.
