### ISSUE TITLE
Struktūros pasikeitimų valdymas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#37]
Pačioje Saugykloje, duomenų struktūra gali keistis, net ir nesuderinama atgaline tvarka, tačiau Saugykla duomenų struktūros aprašus ima iš Katalogo. O į Katalogą turi būti leidžiama įkelti tik atgaline tvarka suderinamus struktūros aprašus. Tačiau, gali būti įvesti ir atgaline tvarka nesuderinami pakeitimai struktūroje, tik jie turėtu įsigalioti po tam tikro numatyto laikotarpio, tarkime po 3 ar 6 mėnesių.

Tai veiktų taip, kad jei reikia ištrinti kokį nors lauką, ar pakeisti kokį nors pavadinimą, pirmiausiai keičiami dalykai turi būti pažymimi, kaip keičiami, tačiau toks pažymėjimas atsispindi tik metaduomenyse, pati struktūra realiai nesikeičia.

Nuo pasikeitimo pažymėjimo datos praėjus 3 ar 6 mėnesiams, nurodyti keitimai realizuojami ir realiai pažymėti laukai yra ištrinami ar pavadinimai pakeičiami.

Per 3 ar 6 mėnesius, visi projektai, kurie yra užsisakę [informaciją apie pasikeitimus](#31), bus informuoti ir turės per nurodyta laiką, prisitaikyti prie pakeitimų.

### Nuorodos

- https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#strukturos-keitimas
- https://atviriduomenys.readthedocs.io/atverimas/atverimas.html#strukturos-pasikeitimu-valdymas
- https://github.com/atviriduomenys/vadovas/issues/4

**Comment by adp-atea** [comment]
Gal galite patikslinti kaip tiksliai viskas turėtų atrodyti?

**Comment by sirex** [comment]
Versijavimo principas yra dokumentuotas čia:

- https://github.com/atviriduomenys/vadovas/issues/4

Iš duomenų saugojimo pusės preliminariai atsiranda tokie pasikeitimai:

- `Version` - nauja lentelė, kurioje saugoma:
  - `dataset: Dataset` - privalomas, ryšys su duomenų rinkiniu, kiekvienas duomenų rinkinys turi savo atskirą versiją.
  - `version: int null` - neprivalomas, versijos numeris, skaičiuojamas kiekvienam rinkiniui atskirai
  - `created: datetime autoadd` - privalomas, kada buvo sukurta versija
  - `released: date null` - neprivalomas, data, kada ši versija yra išleista, arba kada planuojama išleisti, gali būti data ateityje
  - `description: text` - pasikeitimų versijoje aprašymas
  - `deployed: datetime null` - neprivalomas, nurodo laiką, kada versija buvo įkelta į saugyklą.
  - `dataset` ir `version` turi būti unique together
- `Metadata` - pasipildo naujais laukais:
  - `version: Version null` - neprivalomas, saugoma paskutinė versija
  - `draft: bool` - privalomas, nurodo ar metaduomuo keitėsi nuo to laiko, kai buvo priskirtas versijai
- `MetadataVersion` - nauja lentelė, kurioje saugoma:
  - nesu įsitikinęs ar imti visus laukus iš `Metada` ar tiesiog visus saugoti viename JSON tipo lauke? Bet esmė ta, kad reikia išsaugoti ankstesnės versijos metaduomenis.
  - `version: Version` - privalomas, nurodo metaduomenų versiją.
  - `metadata: Metadata` - privalomas, nurodo kokių metaduomenų senesnė versija išsaugota
  - `metadata` ir `version` turi būti unique together

`Metadata` lentelėje, kaip ir dabar, bus saugoma aktuali versija, su kuria ir dirbama ADP kataloge.

Jei `Metadata.version` ir `None`, tada `Metadata.draft` turi būti `True`.

Priskyrus `Metadata` versijai, `draft` turi būti `False`, bet jei po priskyrimo versijai, keičiasi metaduomuo, tada `draft` nustatomas į `True`, nepaisant to, kad metaduomuo jau buvo priskirtas versijai.

`draft` turi būti keičiamas visais atvejais, kai keičiasi metaduomenis, įskaitant ir tada, kai importuojami metaduomenis iš CSV failo.

### Naujos versijos forma

Naujos versijos forma pasiekiama iš Struktūros puslapio:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/e817effb-82c8-4554-af67-60eaac56411c)
-- https://test.data.gov.lt/datasets/1906/models/

Formos laukai:

- `released` - Įsigalioja - privalomas, nurodo datą, kada ši versija įsigalioja, negalima nurodyti atgalinės datos, bet galima nurodyti šiandien arba ateities datą, laukas žinoma turi turėti date picker, tas yra by default naršyklėse nurodžius tinkamą input type.
- `description` - Pasikeitimų apibūdinimas - aprašymas, kas keitėsi versijoje.

Žemiau formos rodomas metaduomenų checkbox sąrašas, kurie turi `draft=True` su checkbox prie kiekvieno, nurodant, kas turi būti įtraukta į versiją.

Virš sąrašo turėtu būti mygtukas „Pažymėti visus“ ir „Nežymėti nieko“, kuriuos paspaudus, pažymimi arba pašalinamas pažymėjimas nuo visų checkbox.


### Keitimų žurnalas

Struktūros puslapyje

![image](https://github.com/atviriduomenys/katalogas/assets/297583/c3680921-6165-49a0-b285-11b0bdacd043)
-- https://test.data.gov.lt/datasets/1906/models/

Rodome naują skyrių „Keitimų žurnalas“, kuriame rodoma paskutinio galiojančio keitimo įrašas, rodoma keitimo data ir aprašymas.

Žemiau paskutinio keitimo, rodoma nuoroda į pilną keitimų sarašą, kuraiem rodomos dvi sekcijos:

- Numatyti keitimai - rodomas keitimų sąrašas, kurie dar neįkelti į saugyklą `Version.deployed is null`.
- Galiojantys keitimai - rodomas `Version.deployed is not null` sąrašas.

Sąraše rodoma `Version.released` data ir `Version.description` ištrauka.

Sąrašas surūšiuotas pagal `Version.released` mažėjimo tvarka.

### Keitimo peržiūra

Keitimų sąraše, paspaudus ant keitimo, rodomas keitimo peržiūra, kur rodoma `Version.released`, `Version.description` ir sąrašas metaduomenų, kurie buvo įtraukti į versiją.

### Metaduomens keitimo rodymas

Metaduomenų keitimai, kurie yra rodomi tiek naujos versijos formoje, tiek versijos peržiūroje turėtu būti rodomi taip:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/925fd92e-12ee-49d0-a12a-704e06c23a35)

Rodomas sąrašas modelių ir savybių, kurie keitėsi ir parodoma sena versija raudonai ir nauja versija žaliai. Paspaudus ant modelio ar savybės pavadinimo naujame lange atidaroma modelio ar savybės peržiūra.

### Kas įtraukiama į versiją

Į naują versiją įtraukiami tokie pasikeitimai, kurie turi įtakos duomenų saugojimui ar integracijai, nepilnas sąrašas tokių metaduomenų:

- `dataset`, `model`, `property` kodiniai pavadinimai
- `base` - modelio bazė
- `model.ref` - modelio pirminis raktas
- `property.type` - duomenų lauko tipas
- `property.ref` - duomenų lauko sąsaja su vienetais ar kitais modeliai
- `model`, `property` `level` - brandos lygis, nuo to priklauso tiek duomenų pateikimas, tiek saugojimas
- `property.access` - prieigos lygis
- `enum.prepare` arba `enum.source`, jei `prepare` nenurodytas - keičiasi klasifikatoriaus reikšmės.

Jei keičiasi kiti metaduomenys, neišvadinti aukščiau, tokie kaip `title` ar `description`, jie neskaitomi kaip pasikeitimas,kuris traukiamas į versiją.

### Versijos atvaizdavimas prie metaduomenų

![image](https://github.com/atviriduomenys/katalogas/assets/297583/9f2c25a9-5175-4a65-b68e-f99ba6733e85)

Prie kiekvieno metduomens atvaizduoja jo versija ir ar tai yra draft (raudona spalva).

**Comment by adp-atea** [comment]
1.. Keitimo versijos nepereina į galiojančių skiltį (Galiojantys keitimai) 
https://test.data.gov.lt/datasets/1670/version/


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/9e115c36-7287-4c5f-940f-02e4b147b737)



2.. Rodo, kad buvo atliktas keitimas "ref" nors keitimas nebuvo atliktas
https://test.data.gov.lt/datasets/1670/version/add/

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/49f5800a-d188-4a33-a297-53a328306562)

**Comment by adp-atea** [comment]
1.  Daryta pagal `deployed` atributą, o ne pagal datą, kaip ir parašyta užduotyje:

> Numatyti keitimai - rodomas keitimų sąrašas, kurie dar neįkelti į saugyklą Version.deployed is null.
Galiojantys keitimai - rodomas Version.deployed is not null sąrašas.

**Comment by IngaIVPK** [comment]
https://test.data.gov.lt/datasets/1193/

1. Keitimo versijos: versija gali įsigalioti ne anksčiau nei po 2 savaičių, nuo jos sukūrimo, t. y. jeigu versija sukuriama 2023-12-11, tai skiltyje "Įsigalioja" anksčiausia pasirenkama data iš kalendoriaus turi būti  2023-12-25. Šiuo metu galima pasirinkti einamąją datą ir vėlesnes.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/1504df3f-535b-47b4-bfb7-36959916dc66)

2. Versijų datos turi būti nuoseklios, t.y. negali būti kad v1 įsigalioja vėliau, nei v2.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9682801e-81f3-43b7-b842-bea8c3f8d3b4)

3. Naujoje versijoje nenuskaito pakeitimo `property.ref` - duomenų lauko sąsaja su vienetais ar kitais modeliai.
T. y. jeigu papildomas **TIK** ryšys, pvz. `realiz_turto_verte` buvo pridėtas `ref=U`, tačiau keitimuose nerodo šio pakeitimo, todėl negalima įtraukti į versijos formavimą.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9c7af3d7-145a-4441-938a-8a6df77b9c2b)

Jeigu atliekama daugiau lauko pakeitimų, kaip pvz. `property=turtas_apskaitytas`, pakeitimuose rodo.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/43e5cc87-1cee-4749-acfb-857da87acfb2)

**Comment by IngaIVPK** [comment]
https://test.data.gov.lt/datasets/2433/#info

1. Versijos turi būti rikiuojamos pagal versijos numerį, pvz. nuo v1.
https://test.data.gov.lt/datasets/2433/version/

2. `access` turi rodyti žodines reikšmes (private, protected, public, open) (1), o ne skaitines koduotas (2).
(1)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9fedc3c6-7274-4286-be2a-20b81a64a960)

(2)
https://test.data.gov.lt/datasets/2433/version/26/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/92299f18-bdcf-41da-a08c-f7014a73f846)

**Comment by IngaIVPK** [comment]
Kaip galimą keitimą leidžia įtraukti tokį atvejį:

property=donuojamu_priemoniu_aprasymas buvo testuota prieigos lygis, t. y. 
pirminis variantas buvo open, 
tada pasirinkta private ir išsaugota, bet neįtraukta į naują versiją
tada pasirinkta protected ir išsaugota, bet neįtraukta į naują versiją
tada pasirinkta public ir išsaugota, bet neįtraukta į naują versiją
tada vėl pasirinkta open ir išsaugota.

Nors joks pakeitimas realiai nepadarytas, kaip buvo open, taip ir palikta open.
Tokį pakeitimą leido įtraukti į naują versiją, nors praktiškai šio property prieigos lygio pakeitimas nepadarytas
https://test.data.gov.lt/datasets/2433/version/39/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/bce170fa-2cbc-4bdb-bf39-330b24ded68b)

Atsižvelgiant į tai, matyt tokie atvejai neturėtų būti laikomi galimais keitimais ir "Naujos versijos" formoje skiltyje "Įtraukimas į versiją" neturėtų būti siūlomi.
https://test.data.gov.lt/datasets/2433/version/add/
