### ISSUE TITLE
Neveikia kalbų perjungimas

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#373]
Atidarius portalą ir pajunginėjus kalbą LT/EN nematau jokio skirtumo, viskas rodoma lietuvių kalba.

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/8c021b3c-76d0-4893-98d1-49bd7897e245)

**Comment by adp-atea** [comment]
Ar [test.data.gov.lt](https://test.data.gov.lt/) yra sugeneruoti `*.mo` failai su `compilemessages`? Nes lokaliai sugeneravus `*.mo` failus, kalba pasikeičia.

**Comment by sirex** [comment]
Kategorijų vertimas priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/268

**Comment by sirex** [comment]
Meniu punktai išversti, bet jų nerodo:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/ccb9ccf1-f6dc-4d92-ba4e-19aa837ad6d3)


![Image](https://github.com/atviriduomenys/katalogas/assets/297583/f6ae678c-81e7-40a9-b363-c464f136d963)

**Comment by sirex** [comment]
> Ar [test.data.gov.lt](https://test.data.gov.lt/) yra sugeneruoti *.mo failai su compilemessages? Nes lokaliai sugeneravus *.mo failus, kalba pasikeičia.

`.mo` failai sutvarkyti.

**Comment by adp-atea** [comment]
**Išversti meniu punktus:**

Duomenų atvėrimas - Opening data
Atvirų duomenų saugykla - Open Data Repository
Duomenų atvėrimo vadovas - Open Data Guide
Duomenų struktūros aprašas - Data Structure Profile
Įrankiai duomenų atvėrimui - Tools for opening data
Mokymo medžiaga - Training materials
Dažnai užduodami klausimai - Frequently Asked Questions
Reglamentacija - Reglamentatioin
Nuorodos - References 
Sąvokos - Concepts 
Kiti AD portalai - Other OD portals?
Ataskaitos - Reports 
Šablonai - Templates

**Comment by adp-atea** [comment]
Šių puslapių vetimas turėtų būti daromas administratoriaus.

**Comment by sirex** [comment]
Patikrinau, puslapių vertimai veikia.
