### ISSUE TITLE
Paieška poreikių ir pasiūlymų sąraše

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#379]
1. Neveikia paieška
2. Neveikia registravimo datos filtras, taip pat nėra aišku kaip atfiltruoti sąrašą, jeigu mygtukas "Filtruoti rezultatus" yra skirtas datos filtrui, tuomet jis turėtų būti perkeltas prie datos filtravimo laukų: 

![Image](https://user-images.githubusercontent.com/107176624/252287200-6e265251-1733-45ee-b7c2-236d99766ab6.png)

**Comment by adp-atea** [comment]
2. Dabar veikia, tik manau turėtų imti ir ribines reikšmes, pvz jei poreikis buvo sukurtas 2023-08-03 ir nurodau, kad rodyti reikšmes iki šios datos, sąraše turėtų būti reikšmės su šia registravimo data, ta pati padaryti ir nuo filtre

**Comment by adp-atea** [comment]
Nelabai aišku, ką daryti, nes poreikių filtrai buvo perdaryti ir yra klaidų.

Kaip suprantu situacija yra tokia:
1. Poreikis turėjo dataset lauką, kad būtų galima susieti su duomenų rinkiniu.
2. Su #335 buvo padaryta, kad poreikį būtų galima susieti su įvairiais objektais (duomenų rinkiniu, modeliu, properčiu ir pan.). Tam buvo panaudotas GenericForeignKey ir dataset laukas pašalintas.
3. Su #41 buvo padaryta, kad tą patį poreikį būtų galima susieti su keliais objektais. Tam sukurtas RequestObject modelis, su kuriuo įgyvendintas ManyToMany ryšys ir GenericForeignKey laukas perkeltas iš Request į RequestObject modelį.
4. Sumerge'intas #311 pull request. Jame panašu, kad buvo atliekami pakeitimai, kai dar buvo dataset laukas. Prie Request modelio vėl atsirado dataset ir jis naudojamas paieškos indekse ir kai kur kode, kai tai jau turėtų būti nebenaudojama, nes duomenų bazėje lauko jau nebėra. Dėl to indeksuojant gaunama klaida. Susiję duomenų rinkiniai turėtų būti paimami per RequestObject.

Taip pat dėl pačių filtrų: su pakeitimais prisidėjo papildomi filtrai, vienas iš jų yra "Pateikimo data", kuris filtruoja pagal created lauką, tą patį daro ir "Registravimo data" filtras, vienintelis skirtimas, kad "Registravimo data" filtras leidžia nurodyti tikslų datos intervalą, o "Pateikimo data" pateikta metais, ketvirčiais ir pan. Tai turbūt vienas iš jų yra nereikalingas.

**Comment by sirex** [comment]
Teisingai, anksčiau poreikį buvo galima susieti tik su vienu duomenų rinkiniu ir viena organizacija.  Dabar poreikį galima susieti su keliais rinkiniais, modeliais, laukais ir pan., taip pat poreikį galima nukreipti daugiau nei vienai organizacvijai, papildomai prie poreikio buvo prijungtas planavimo modulis.

Filtravimui ir paieškai reikėtu naudoti naujai pridėtą funkcionalumą, jei taip nėra tada tai yra klaida. Nes teoriškai poreikių filtrai jau turėtu būti padaryti, juos darė @Faustasm.

@Faustasm, gal gali pakomentuoti?

**Comment by Faustasm** [comment]
Taip, reikia pataisyti, kad naudotų naują funkcionalumą, patys filtrai padaryti. Galiu užsiimti.

**Comment by Faustasm** [comment]
Pakeista: vietoj dataset naudojamas RequestObject, pašalinta registravimo data, paieška veikia.

**Comment by adp-atea** [comment]
Įrašant nepilną reikšmę neveikia:


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/08b6fb9c-8c71-45c4-83b5-2305415636fe)

**Comment by Faustasm** [comment]
Atsikartoja ir duomenų rinkinių paieškoje

**Comment by Faustasm** [comment]
Code review:
Jei įvesti mažiau nei ~5 simboliai, darom starts_with, jei daugiau contains.
