### ISSUE TITLE
VIISP prisijungimas neveikia

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#381]
![Image](https://user-images.githubusercontent.com/107176624/252701201-a273ead7-bce2-47f1-83da-8246f03e158d.png)

**Comment by Faustasm** [comment]
Klaida rodoma, nes serverio ip nėra whitelistintas https://www.epaslaugos.lt/portal/content/1257.

**Comment by Faustasm** [comment]
Pataisyta.
P.S: Elektroninių valdžios vartų testinėje aplinkoje, prisijungimas veikia tik su seb, nordea ir tapatybės kortele.

**Comment by adp-atea** [comment]
Pratestuoti iš IVPK ofiso arba prisijungus prie vpn.

**Comment by JuliusLADP** [comment]
Pabandžiau per VPN kaip naujas duomenų teikėjas 


![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/93a21ebd-b4fe-4e8b-a763-e9fafaeecf7e)


prisijungti ir išmetą tą pačią klaidą 
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/ed6a8d6f-63e6-45c2-a757-eaed452b88f6)
