### ISSUE TITLE
Duomenų rinkinio peržiūra

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#383]
Prie šių laukų neturėtų būti pagalbinio pranešimo užvedus pelę?

![Image](https://user-images.githubusercontent.com/107176624/252898255-8df9965b-acc1-435c-802a-a669852898ed.png)

**Comment by adp-atea** [comment]
Vis dar nėra

**Comment by adp-atea** [comment]
Reikia, kad atnaujinant test.data.gov.lt, būtų atnaujinti ir stiliai.

**Comment by sirex** [comment]
> Reikia, kad atnaujinant test.data.gov.lt, būtų atnaujinti ir stiliai.

Stiliai atnaujinami, jei konkrečiau daroma taip:

```
poetry run python manage.py collectstatic --no-input --clear
(cd webpack && npm install)
(cd webpack && npm run build)
```

**Comment by adp-atea** [comment]
Panašu, kad šiuo atveju nebuvo atnaujinti, lokaliai pažiūrėjus per inspect bundle.css failą, jame yra su tooltip susiję stiliai, o test.data.gov.lt jų nėra.

**Comment by sirex** [comment]
Dar kartą patikrinau statinius failus, panašu, kad viskas su jais gerai:

```
(cd webpack && npm run build)
poetry run python manage.py collectstatic --no-input --clear
sha1sum var/static/{js,css}/bundle.* | sort
#| 6128d00ac28b647a4dc2d8e6ed4243a4db7920e7  var/static/css/bundle.css
#| b70f61f0b950d5066082c2e4a0ef68b324a86505  var/static/js/bundle.js

http -b -d https://test.data.gov.lt/static/css/bundle.css -o /tmp/bundle.css
http -b -d https://test.data.gov.lt/static/js/bundle.js -o /tmp/bundle.js
sha1sum /tmp/bundle.* | sort
#| 6128d00ac28b647a4dc2d8e6ed4243a4db7920e7  /tmp/bundle.css
#| b70f61f0b950d5066082c2e4a0ef68b324a86505  /tmp/bundle.js
```

Kokių konkrečiai stilių trūksta, gal jie nėra įtraukti į webpack?

Dabar, tai ką sugeneruoja webpack ir tai, kas yra servinama test.data.gov.lt yra identiški failai.

**Comment by sirex** [comment]
Sorry, dar kartą parefreshinau su ctrl+f5, tada atsinaujino, tooltipai atsirado.
