### ISSUE TITLE
Susiejimas su duomenų rinkiniu

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#385]
Lauke ryšio tipas nėra reikšmių, bet nežinau ar tai klaida

![Image](https://user-images.githubusercontent.com/107176624/254205221-c3d5b5be-4ae2-4af6-ac8d-eff5c0684567.png)

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/332

**Comment by adp-atea** [comment]
Pirmiausia turėtų būti pridėtos reikšmės administravimo dalyje /admin/vitrina_datasets/relation/.

**Comment by sirex** [comment]
Pridėta.
