### ISSUE TITLE
Duomenų rinkinio struktūros klaidos, pastebėjimai

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#386]
1. Importuojant strukūros failą klaidos pranešimas atvaizduojamas kaip komentaras, gal reikėtų padaryti, kad atvaizduotų kaip klaidos pranešimą, kuris nėra išsaugomas kaip komentaras? Komentarus mato ir neprisijungęs vartotojas

![Image](https://user-images.githubusercontent.com/107176624/254221223-c7080573-6e0d-4d05-af5a-a47fb628e53e.png)

2. Sukūrus naują modelį, struktūros peržiūros lange atvaizduojamas modelio įvertinimas, ar jis nėra perteklinis eementas?

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/34c95c0d-bd3f-4f3c-b64b-3ad3329bea2c)

**Comment by adp-atea** [comment]
Daryta su #288 užduotimi. Pagal ją klaidos ir turi būti rodomos kaip komentarai ir modelių sąraše taip pat turi būti atvaizduojamas įvertinimas.

**Comment by sirex** [comment]
Taip ir turėtu veikti. Klaidos kuriamos kaip komentarai, nes klaidos gali būti pažymėtos ir struktūros aprašuose, todėl komentarai išlaikomi, kad veiktu importas/eksportas.

Taip klaidų komentarai turi būti  registruojami ir kaip užduotys, užduočių sąraše, žiūrėti https://github.com/atviriduomenys/katalogas/issues/42.

Dėl klaidų rodymo viešai, tikriausiai klaidų komentarus reikėtu rodyti, tik tvarkytojui/koordinatoriui, bet kol kas paliekam, taip kaip yra.
