### ISSUE TITLE
Instrukcija el. pašto pranešimuose

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#39]
Siunčiant el. laiškus rinkinių tvarkytojams turi būti nurodoma, per kiek laiko privaloma atsakyti ir kita instrukcija, ką reikia daryti, kokių veiksmų imtis gavus šį laišką.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/42

**Comment by sirex** [comment]
Buvo sutarta, kad neverta taisyti pačių laiškų, kode, o geriau peržiūrėti, visus siunčiamus laiškus ir padaryti, kad jie naudotų šablonus ir duomenų bazės:

https://github.com/atviriduomenys/katalogas/blob/3d45f775fe6ffb6ee3f64b5deb2434ca152a8f65/vitrina/messages/models.py#L10

Reikia, kad siunčiant laiškus iš db, pagal `identifier` paimtu laiško tekstą, pakeistu kintamas dalis ir siūstų, būtent pagal šabloną, kuris yra pateiktas duomenų bazėje.

Reikėtu README faile dokumentuoti, kokie yra naudojami `identifier`, kad būtų žinoma, kokius įrašus duomenų bazėje sukurti.

`EmailTemplate` turi būti matomas, per Django admin.

**Comment by sirex** [comment]
Gavau tokį laišką:

> Sveiki, portale užregistruotas naujas poreikis duomenų rinkiniui: { request.title }.

Nepakeistas `{request.title}`, bet to visuose laiškuose, reikia pateikti nuorodas į objektą, apie kurį rašoma laiške. Šiuo atveju `{request.title}` turėtu būti nuoroda į poreikį.

Dabar, kaip suprantu, laiškai siunčiami ascii formatu, kur negalima pateikti nuorodų. Siūlau, interpretuoti laiško šabloną, kaip markdown dokumentą, o tada iš markdown generuoti HTML, kurį prisegti prie laiško, tada veiks nuorodos.

README faile matau:

> 18. request-registered

Nurodytas šablono pavadinimas, bet nenurodyta, kokie konteksto kintamieji perduoti šablonui. Tai gal `request` išvis neperduodamas?

Dar vienas laiško pavyzdys:

> veiki, Jūsų poreikis duomenų rinkiniui atverti atmestas. <br><br>Priežastis:<br><br>

Šiuo atveju iš vis nenurodytas nei rinkinio pavadinimas, nei nuoroda, nei konteksto kintamieji prie `request-rejected`, tiklsiau prie `request-rejected` nurodytas komentaras, bet nenurodytas pats poreiko objektas. Kadangi absoliučiai nepateikta jokios informacijos, tai negaliu patikrinti ar priežasties nebuvo nurodyta ar tiesiog neįtraukta į laišką.

Na ir vėl HTML problema, nes amtosi HTML tagai. Siūlau naudoti markdown, kuris išspręs tiek HTML tagų problemą, tiek nuorodas.

Čia tik keli pavyzdžiai, bet prašau peržiūrėti dar kartą visus šablonus ir įsitikinti, kad kaip minimum yra perduotas objektas, su kuriuo yra susijęs laiškas. Kad šablonuose būtų galima nurodyti objekto pavadinimą ir nuorodą į jį.

Ir dar vienas svarbus dalykas, kad saugant šabloną, turėtu būti patikrinama ar teisingai perduoti konteksto kintamieji ir ar pats markdown neturi klaidų. Jei yra klaidų, neturėti leisti išsaugoti šablono ir turėtu parodyti klaidas.

> error-in-data, current keys ({0} - url, {1} - external object id, {2} - content type, {3} - external content type)

Ar nebūtų patogiau, jei šablone būtų naudojami vardiniai kintamieji, o ne argumento eilės numeris? Tarkim, vietoj `{0}` galėtu būti `{url}`.

Tuo labiau, jei būtų pridėti nauji argumentai, atsiranda dar viena problema, kad reikia išlaikyti argumentų tvarką, nes sukeitus argumentų tvarką, pasikeis ir eilės numeris.

Argumento eilės numeris, kaip šablono kintamasis yra sunkiai naudojamas, nes pats savaime eilės numeris nieko nesako ir atsiranda problema su argumentų eiliškumo išlaikymu.

Dar vienas pasiūlymas, README faile, gal būt galima šablonų sąrašą pateikti abėcėlės tvarką, o konteksto kintamųjų sąrašą atskirose eilutėse, nurodant argumento tipą ir trumpą paaiškinimą, kas tai yra? Pavyzdžiui:

- `request-rejected`
  - `current_keys: str` - apibūdinimas, kas yra `current_keys`, nes iš pavadinimo neaišku.
  - `request_komment: ?` - neaišku kokio tipo kintamasis, ar tai yra komentaro tekstas, ar komentaro `Comment` objektas?

**Comment by sirex** [comment]
Per klaidą, buvo padarytas laiškų siuntimas atidarius poreikio peržiūros puslapį ir iki ~70 žmonių galėjo gauti klaidingus laiškus. Pašalinau kodą, kuris siunčia laiškus čia:

- https://github.com/atviriduomenys/katalogas/pull/687

Prašau daugiau atidumo. Ačiū.

**Comment by adp-atea** [comment]
1. Del request.title fixed, buvo praleista migracijoje
2. As issivaizduociau, kad markdown turetu butu vedami paciame template, per admin puslapi
3. Ta pati manau, ir del nuorodu, paciam request title uzdesiu nuoroda, nu bet kitur as nezinau, ar tai turi buti nuoroda ar paprastas tekstas, Email template lentoj visi buvo tiesiog paprastas tekstas.
4. Pridejau saugojima apie laisku isiuntima/neissiuntima, duomenu bazeje 
5. Pakeiciau laisko contento siuntima į html
6. Del tu visu neaiskumu del raktu, perdarysiu, kad raktai bus saugomi list formatu duombazeje, tada bus galima ir patikrint, ar vartotojas gerai viska suvede ar ne, tai uztruks ilgiau, nu bet kitaip as nezinau, kaip ta padaryt.

**Comment by sirex** [comment]
Code review metu, radau labai daug klaidų, kurias surašiau prie kodo eilučių, kuriose yra klaidos, grąžinu atgal, taisymui.

- https://github.com/atviriduomenys/katalogas/pull/703#pullrequestreview-1795420181

**Comment by JuliusLADP** [comment]
Pradinis suvestinis pranešimų siuntimo sąrašas https://ivpk-my.sharepoint.com/:x:/g/personal/julius_belickas_vssa_lt/EdK6mafTkuFNpfSXkOeMDLwBwzHejPbIm_TLZoaX4Lhmgw?e=Eobdg0

**Comment by JuliusLADP** [comment]
įvertinti aktualumą (jei neišspręsta)

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
