### ISSUE TITLE
Pakeitus kalbą peršoka į pagrindinį langą

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#390]
Gal būtų patogiau vartotojui, jeigu pakeitus kalba liktu tame pačiame lange

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/710

**Comment by adp-atea** [comment]
Lokaliai pasirinkus kitą kalbą, liekama tame pačiame puslapyje. Manau, kad ši problema ateina iš `set_language` metodo. Jame iš `settings.py` imamas `ALLOWED_HOSTS` parametras. Pas mus šiuo metu yra leidžiami tik `localhost` ir `127.0.0.1` host'ai. 

Reikėtų testiniame serveryje pridėti `test.data.gov.lt` į `ALLOWED_HOSTS` sąrašą.

**Comment by sirex** [comment]
Sutvarkyta, problemos buvo dėl proxy nustatymų.
