### ISSUE TITLE
Rinkinio būsenos sutvarkymas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#396]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/0240e821-de80-4373-89fc-f354598caac5)
-- https://test.data.gov.lt/datasets/stats/status/?

- [ ] Pašalinti rinkinio būseną „Įkelta duomenų struktūra“ ir pridėti naują būseną „Planuojami atverti“.
- [ ] Pakeisti būsenos „Tik invertorinta“ pavadinimą į „Inventorinti“.

Galutinis būsenų sąrašas turėtu būti toks:

- Atverti duomenys
- Planuojami atverti
- Inventorinti

Nauja būsena „Planuojami atverti“ suteikiama jei tenkinamos tokios sąlygos:
- Duomenų rinkinys neturi nei vieno duomenų šaltinio (distribucijos arba `Resource`).
- Duomenų rinkinys įtrauktas į planą.

Būsena „Inventorinti“ suteikiama, jei tenkinamos tokios sąlygos:
- Duomenų rinkinys neturi nei vieno duomenų šaltinio.
- Duomenų rinkinys nėra įtrauktas į planą.

Atitinkami pakeitimai turėtu būti padaryti ir švieslentėje.

Atitinkamai pakeitimai turėtu būti padaryti ir Poreikių sąrašo filtre:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/57bc20ff-b0ac-4e62-a5d6-9c2214ea7662)
-- https://test.data.gov.lt/requests/submitted/

**Comment by sirex** [comment]
„Numatyta atverti“ statuso negalime sukurti, nes prašymai atverti duomenis nėra duomenų rinkiniai, vienas prašymas gali apimti daug rinkinių. Todėl siūlyčiau nepainioti prašymų ir duomenų rinkinių.

O „Įkelta duomenų struktūra“ ir „Tik inventorintas“ galima apjungti ir pavadinti „Numatyta atverti“?

**Comment by JuliusLADP** [comment]
Numatytų atverti rinkinių sąrašas ir apskaita galimi iš DB, kai joje duomenų teikėjai atsakydami į registruotus poreikius arba savo nuožiūra priima sprendimą įtraukti Inventorintą rinkinį, arba rinkinį, kuriam gautas paklausimas, į Numatytų atverti rinkinių sąrašą. 
Būklė "Tik inventorintas" nėra lygiareikšmė būklei "Numatytas atverti". Tik inventorintas būklė reiškia, kad toks rinkinys yra inventorintas, nes tokie duomenys yra galimi atverti, bet dar nėra numatyta konkrečiai atverti, ir gali būti atverti esant registruotam poreikiui. Kai duomenų valdytojas priima sprendimą atverti, poreikyje įvardintam duomenų rinkiniui automatiškai priskiriamas statusas. "Numatytas atverti" - reiškia, kad šis rinkinys yra vienoje ar kitoje atvėrimo eigos fazėje.

**Comment by JuliusLADP** [comment]
paskutinį  komentarą įkėliau į užduotį

**Comment by sirex** [comment]
_(originalus aprašymas)_

Reikalingi pakeitimai ![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/75068bba-02f9-4182-a179-4f0d0d046afd)
Galimos rinkinio būsenos https://test.data.gov.lt/datasets/stats/status/?:
- Atverti duomenys - šiai grupei priskiriami rinkiniai, kurie yra publikuoti (rinkinio apraše pateikiama pastaba (kaip parodyta iškarpoje), jeigu rinkinys yra vėluojamas laiku atnaujinti)
- Inventorinti - visi kurie turi bent pavadinimą ir aprašymą arba ir kitus metaduomenis (struktūros aprašą ir t.t.), bet patys duomenys dar nėra publikuoti
- Numatyti atverti, tai tie inventorinti rinkiniai dėl kurių institucija yra patvirtinusi, kad numato atverti. Dabartinė būsena "įkelta duomenų struktūra" panaikinama Numatytų atverti rinkinių sąrašas formuojamas iš duomenų rinkinio registracijos formos (metaduomenų), kai joje duomenų teikėjai atsakydami į registruotus poreikius arba savo nuožiūra priima sprendimą įtraukti Inventorintą rinkinį, arba rinkinį, kuriam gautas paklausimas, į Numatytų atverti rinkinių sąrašą. Daugiau apie planavimo duomenų procesą #474 
Būklė "Inventorintas" nėra lygiareikšmė būklei "Numatytas atverti". Tik inventorintas būklė reiškia, kad toks rinkinys yra inventorintas, nes tokie duomenys yra galimi atverti, bet dar nėra numatyta konkrečiai atverti, ir gali būti atverti esant registruotam poreikiui. Kai duomenų valdytojas priima sprendimą atverti, poreikyje įvardintam duomenų rinkiniui automatiškai priskiriamas statusas. "Numatytas atverti" - reiškia, kad šis rinkinys yra vienoje ar kitoje atvėrimo eigos fazėje.

Taip pat reikia sutvarkyti susijusį su Rinkinio būsena grafiko (švieslentės elemento) veikimą: 

Jį pasirinkus pateikiami "būsenų" kiekių diagrama, kurioje taip pat aktyvi, bet nelogišką galimybė pasirinkti nesusijusius rodiklius "Atsisiuntimų (užklausų) skaičius", "Projektų skaičius" ir pan. Kuri beje ir neveikia. Geriau apgalvoti pačią logiką ir pašalinti nereikalingus.

**Comment by sirex** [comment]
Rinkinio būsenos keitimo seka:

- nepriskirtas - kai rinkinys nepublikuotas
- inventorintas - kai rinkinys publikuotas
- suplanuotas - kai yra įtrauktas į planą
- atvertas - kai yra bent vienas šaltinis

Jei rinkinys atvertas, bet nepublikuotas, tada jo statusas „nepriskirtas“.

**Comment by sirex** [comment]
Sukūrus naują duomenų rinkinį, jo būsena lieka „Nepriskirta“:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/27ccb8fc-f12c-4e0e-800d-17319222476f)
-- https://test.data.gov.lt/datasets/2372/

**Comment by JuliusLADP** [comment]
"Nepriskirta" būsena nėra reikalinga, nes jeigu duomenų rinkinys turi bent pavadinimą ir aprašymą - toks rinkinys yra "Inventorintas" statuso. Tokį statusą jis turės iki tol kol bus įtrauktas į planą ir/arba turės publikuotus duomenis saugykloje. 
**Taip pat reikia pakeisti "Inventorintas" į "Tik inventorintas"**
