### ISSUE TITLE
Brandos lygio diagrama

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#397]
Švieslentė: Brandos lygis diagrama neįgyvendinta.  https://test.data.gov.lt/datasets/stats/level/?
Brandos lygis galėtų būti pasirenkamas rodiklis bet kurioje Valdymo srities, Kategorijų arba organizacijų išrankoje.

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/3dcf732d-fe47-4d5b-bedb-adbee7d5b282)

**Comment by sirex** [comment]
Dar nepadaryta, bet teoriškai tai turėtu pradėti veikti padarius:

- https://github.com/atviriduomenys/katalogas/issues/302

Kol kas uždarau, kaip duplikatą.
