### ISSUE TITLE
Bendrai dėl diagramų logikos

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#398]
Švieslentė:
Buvo įgyvendintas geras rinkinių atvėrimo progreso grafikas, kuriame pateikiama atvirų duomenų rinkinių kiekio augimas laiko ašyje: inventorintų rinkinių ir atvertų rinkinių kiekių augimo kreivė. Pvz.

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/8893cae9-6d13-4603-907f-43636e375dc9)

Reikėtų ją grąžinti ir naudoti kitais statistinių rodiklių pateikimo atvejais: išrankose pagal kategorijas, insititucijas ar kitas.
https://test.data.gov.lt/datasets/stats/status/?
Gal būt racionaliausias variantas būtų, kad pirmiausia išsirenkama pagal įvairius parametrus (Valdymo sritį, Kategoriją, arba organizaciją, žymę ir/arba laiko apibrėžtį) rinkinių aibė, o po to pasirenkamas norimas grafiškai atvaizduoti rodiklis arba jų grupė

Švieslentėse reikalinga pateikti statistinius duomenis tokiais trimis atvėrimo veiklos aspektais (temomis): 
- Atvėrimo pažanga (vietoje Portalo naudotojai)
- Duomenų naudojimas (vietoje Valdymo sritys
- Poreikis (vietoje Duomenų kategorijos)

Nuorodos į išvardintų temų statistinių duomenų grafines pateiktis įgyvendinimos pirmo puslapio bloke "Statistika", atitinkamai pakeičiant  dabartines rubrikas (Portalo naudotojai, Valdymo sritys, Duomenų kategorijos). 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/8ac7a004-6897-44c1-bd04-aee8cb7a9435)

Iš minėtų nuorodų patenkama į atitinkamai tematikai pritaikytas aplinkas kuriose pateikiami, pridedame faile išvardinti rodikliai, kurie atvaizduojami grafiškai pasirinktu variantu (LG/RG) pagal pasirinktas laiko ir kitų kriterijų apibrėžtis, kaip yra pateikiama pridedame faile "švieslentė".

**Comment by JuliusLADP** [comment]
[Švieslentė.xlsx](https://github.com/atviriduomenys/katalogas/files/12260104/Svieslente.xlsx)

**Comment by sirex** [comment]
Siekiant supaprastinti šią užduotį, yra pasiūlymas padaryti atskirą sąrašą, kuris būtų administruojamas per Django admin. Tituliniame lape:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/6b993f39-1ba6-4d66-a607-a6f4de80f3c2)

Būtų rodomi įrašai iš statistikos sąrašo.

Statistikos nuorodų lentelė turėtu tokius laukus:

- `title` - nuorodos į statistiką pavadinimas
- `description` - nuorodos į statistiką aprašymas
- `image` - paveiksliukas, kurį galima įkelti
- `url` - nuoroda į konkretų puslapį
- `featured` - boolean, jei true, tai įrašas rodomas tituliniame lape
- `order` - integer, skaičius, kuriuo galima nurodyti eiliškumą

Tituliniame lape rodom visus `featured = True` ir rūšiuojam pagal `order` ir papildomai rodome paveiksliuką.

Paspaudus „Rodyti daugiau >“, atsidaro `/stats/` puslapis, kuriame rodomas visas nuorodų sąrašas.

Paspaudus ant kiekvienos nuorodos, atidaroma `url` nuoroda.

**Comment by sirex** [comment]
https://test.data.gov.lt/admin/statistics/statroute/add/

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/e309277c-e643-4c11-b786-8536600eb826)

Turėtu būti ne pilnas URL, o URL path, migruojant duomenis tarp testinės ir gamybinės aplinkos hardodinti URL rodys ne ten kur reikia.
