### ISSUE TITLE
Švieslentė; Valdymo sritis

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#399]
500 klaida kai turėtų rodyti Valdymo sričių diagramas pagal pasirinktus Rodiklius https://test.data.gov.lt/dataset/stats/jurisdiction/?. Pasirenkami Valdymo sritis Rodikliai:
- Atvertų rinkinių kiekis, pasirinktam laiko periodui
- Inventorintų duomenų kiekis, , pasirinktam laiko periodui
- Numatomų atverti rinkinių kiekis,, pasirinktam laiko periodui
- Atsakytų/atsisakytų atverti  (Institucija, įrašė/pažymėjo kad nenumato atverti) rinkinių kiekis, pasirinktam laiko periodui
- Atvertų, pagal paklausimus, rinkinių kiekis, pasirinktam laiko periodui
- Sukurtų panaudos atvejų kiekis, pasirinktam laiko periodui
- Analogiški parametrai pagal kategorijas, pasirinktam laiko periodui

**Comment by sirex** [comment]
> 500 klaida kai turėtų rodyti Valdymo sričių diagramas pagal pasirinktus Rodiklius https://test.data.gov.lt/dataset/stats/jurisdiction/?

Jau pataisyta ir veikia.

> Atsakytų atverti rinkinių kiekis, pasirinktam laiko periodui

Nėra tokio statuso, kaip atsakytas atverti rinkinys, gal būt turėjote mintyje atsisakyta tenkinti prašymą atverti duomenis, kur būtent toks statusas ir yra? Žiūrėti https://github.com/atviriduomenys/katalogas/issues/350

> Atvertų, pagal paklausimus, rinkinių kiekis, pasirinktam laiko periodui

Yra rodiklis „Poreikių skaičius“, ar čia ir yra tai ko reikia?

Visi kiti rodikliai yra.

**Comment by JuliusLADP** [comment]
Patikslinau pradiniame tekste

**Comment by sirex** [comment]
Dubliuoja:

- https://github.com/atviriduomenys/katalogas/issues/460
