### ISSUE TITLE
Atvaizduoti rinkinio poreikius prie rinkinio

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#40]
Šiuo metu, prašymai gauti ar keiti rinkinį rodomi atskirai nuo rinkinio. Nors turėtu būti rodomi, prie pačio rinkinio, šalia mygtuko, teiki naują poreikį, kad prieš teikiant naują prašymą, būtų galimybė susipažinti, kokie prašymai jau buvo pateikti.

Pateikti prašymai turėtu būti apjungti pagal pageidaujamą keitimą.

**Comment by adp-atea** [comment]
Duomenų rinkinyje https://test.data.gov.lt/datasets/1748/ neesu nei koordinatorius nei tvarkytojas, bet prie duomenų rinkinio bandau pridėti mano sukurta poreikį https://test.data.gov.lt/requests/241/


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/fb9130f8-5698-4565-a329-46123a74e379)


Paspaudus mygtuką "Pridėti poreikį" gaunu klaidą:

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/5b3aa48f-9b4d-4d6f-9860-2c984c8c5c5b)

Turėčiau galėti pridėti poreikį, nes esu poreikio autorius,
