### ISSUE TITLE
Brandos lygis Duomenų rinkinių sąrašo puslapyje

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#402]
Įgyvendinti Duomenų rinkiniai puslapyje https://test.data.gov.lt/:

Neveikia brandos lygio filtras (Brandos lygis rodomas tik 5 rinkiniams iš visų 1324 rinkinių)

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/cd6afdba-dfce-496b-8869-1c0a79d114b4)

**Comment by sirex** [comment]
Labai daug skirtingų užduočių vienoje vietoje, būtų gerai, kiekvieną užduotį pateikti, kaip atskirą užduotį. Gal būt galima suskaidyti į atskiras užduotis? Jei ne, tada bandysiu komentuoti atskirai, kiekvieną punktą.

**Comment by JuliusLADP** [comment]
Išskaidžiau.

**Comment by sirex** [comment]
Dubliuoja https://github.com/atviriduomenys/katalogas/issues/397.

**Comment by JuliusLADP** [comment]
Brandos lygis vis dar neveikia
![image](https://github.com/atviriduomenys/katalogas/assets/69783864/80e077cb-c39c-4fd8-b5c1-e736edf0d9a5)

**Comment by sirex** [comment]
Dubliuoja:

- https://github.com/atviriduomenys/katalogas/issues/460
