### ISSUE TITLE
Sudaryti galimybę testuoti duomenų teikėjų aplinkas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#405]
Sudaryti galimybę testuoti Vyr.Koordinatoriaus, Ministerijos Koordinatoriaus, Organizacijos Koordinatoriaus, Tvarkytojo aplinkas

**Comment by sirex** [comment]
Tokia galimybė yra, reikia susikurti naudotojus skirtingomis rolėmis ir testuoti. Testuotojai tai jau daro. Tik yra viena klaida, kur neveikia naudotojų administravimas, ją pataisius, bus paprasčiau keisti naudotojų teises:

- https://github.com/atviriduomenys/katalogas/issues/431
