### ISSUE TITLE
Galimybė susieti poreikį su rinkiniu

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#41]
Tais atvejais, kai pateikiamas poreikis naujam duomenų rinkiniui, tačiau paaiškėja, kad toks duomenų rinkinys jau yra, tada toks poreikis turi būti susiejamas su esamu rinkiniu.

**Comment by adp-atea** [comment]
**Testavimo info (rinkinys: https://test.data.gov.lt/datasets/2090/)**

1..  Prie duomenų rinkio pridėjau poreikį -> tada tą poreikį iš duomenų rinkinio paalinau -> poreikis pašalintas iš poreikių sąrašo. Poreikis turėtų būti pašalintas tik iš duomenų rinkinio sąrašo



2.. Prie duomenų rinkio pridėjau poreikį "poreikis 2"


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/14e79600-03a2-4e73-bbc2-7f2ceb7edadd)

spaudžiu pašalinti poreikis 2, gaunu patvirtinimo langą su tekstu "Ar tikrai norite pašalinti "Jūrų laivų duomenys ed"?"


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/d24a590c-ef71-4515-bb40-70f997630c79)

Vietoje "Jūrų laivų duomenys ed" - kas yra rinkinio pavadinimas turėtų būti poreikio pavadinimas

**Comment by adp-atea** [comment]
1.. Pataisytas
2.. Reikia pataisyti
3.. Ištrynus poreiki ir vėl jį pridėjus, prisideda 2 poreikiai (pavyksta atkartoti tik su tam tikru poreikiu)
Duomenų rinkinys: https://test.data.gov.lt/datasets/2090/  Poreikis: https://test.data.gov.lt/requests/14316/



![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/f69c363d-6ee9-400d-9757-9e60294fccb8)

**Comment by adp-atea** [comment]
2. fixed
3. Paliekam kaip yra, nepavyko daugiau atkartot
