### ISSUE TITLE
Prašymas neatsiranda duomenų rinkinio poreikių sąraše

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#410]
Pateikus komentarą ir pažymėjus "Registruoti kaip prašymą":

https://test.data.gov.lt/datasets/1636/data/ActionType/b8972707-9229-433b-a48d-7ae4c1f88d1b/

Komentaras sukuriamas, poreikis taip pat sukuriamas:

https://test.data.gov.lt/requests/228/

Bet sukurtas poreikis, neatsiranda prie duomenų rinkinio poreikių sąrašo:

https://test.data.gov.lt/datasets/1636/requests/

**Comment by adp-atea** [comment]
Su esamais duomenimis neveiks, testuojant reikės sukurti naują prašymą objektui.
