### ISSUE TITLE
Svetainės naudotojų užduočių sąrašas (namų puslapis)

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#42]
Prisijungus prie data.gov.lt, kiekvienas naudotojas, pagal savo rolę, pirmiausia turėtu būti nukreipiamas į namų puslapį, kuris yra naudotojo užduočių sąrašas. Užduočių sąraše turėtu būti rodomos tokios užduotys:

Užduotys yra generuojamos automatiškai pagal tokius įvykius:

- Pateiktas prašymas atverti duomenis.
- Parašytas komentaras.
- Pateiktas naujas panaudojimo atvejis.
- Neveikia distribucijos nuoroda.
- Duomenų atnaujinimas neatitinka nustatyto periodiškumo.
- Pateiktas naujo koordinatoriaus prašymas.
- Automatiškai aptikta klaida metaduomenyse.
- Pasikeitimai rinkiniuose kuriuose seka naudotojas.
- Pasikeitimai rinkiniuose kurie įtraukti į panaudojimo atvejį (projektą).

Užduotys siejamos su:

- Organizacija
- Duomenų rinkiniu
- Duomenų šaltiniu
- Modeliu
- Duomenų lauku
- Duomenų objektu
- Prašymu
- Panaudojimo atveju
- Komentaru

Užduotys yra siejamos su objektais ir jei problema pašalinta pačiame objekte, užduotis automatiškai uždaroma. Pavyzdžiui, jei pateiktas atsakymas prašymui arba jei atsakyta į komentarą, arba jei nuoroda pradėjo veikti arba atsistatį atnaujinimo dažnumas ir pan., kai problema išsprendžiama užduotis automatiškai uždaroma. Tačiau turi būti galimybė uždaryti užduotį ir rankiniu būdu.

Taip pat užduoties terminas nustatomas automatiškai pagal objektą. Pagal nutylėjimą, terminas turi būti 5 darbo dienos (neįskaitant savaitgalių ir švenčių dienų), nuo užduoties sukūrimo datos. Tačiau tam tikri objektai gali pateikti kitą terminą, nors šiuo metu tokių objektų lyg ir nėra.

Užduotys rodomos tokia tvarka, pradedant nuo tvarkytojų ir įtraukiant vis daugiau akių:

- Pirmiausiai užduotis rodoma **tik** duomenų rinkinio tvarkytojui.
- Jei organizacija neturi duomenų rinkinio tvarkytojo, tada užduotis rodoma koordinatoriui.
- Jei iki užduoties termino liko 24 valandos, užduotis rodoma koordinatoriui (oranžinė spalva).
- Jei užduotis vėluoja, t.y. terminas jau baigėsi, užduotis rodoma valdymo srities organizacijai, t.y. aukštesnei organizacijai, pagal pavaldumo hierarchija ir vyriausiems koordinatoriams (super admin).

Užduočių sąrašas vėluojamas pagal terminą arba pagal sukūrimo datą, jei terminas nenurodytas.

Užduotis taip pat mato ir paprasti naudotojai, kurie sekan duomenų rinkinius arba yra užregistravę panaudojimo atvejus. Tačiau paprastų naudotojų atveju, užduotis neeskaluojama pagal pavaldumą, artėjant terminui.

### Užduočių sąrašas

![image](https://github.com/atviriduomenys/katalogas/assets/297583/cb675dd2-0487-4b6d-8a50-02a761231a41)

Pagal nutylėjimą rodome tik tas užduotis, kurios nėra uždarytos, bet jei iš filtro pasirenkama uždarytos užduotys, tada rodome tik uždarytas.

Pagal nutylėjimą rodome visas užduotis, bet jei pasirinkta „Mano užduotys“, tada rodome tik prisijungusiam naudotojui priskirtas užduotis.

Taip pat užduotys rodomos pagal eskalavimo lygmenis, žiūrėti aukščiau.

### Užduoties peržiūra

![image](https://github.com/atviriduomenys/katalogas/assets/297583/6556bf1b-ea30-49ff-bd4e-d60eeefad561)

### Komentarai

Užduotis galima komentuoti. Visi veiksmai atlikti su užduotimi, tokie kaip priskyrimas, uždarymas ir pan., turi būti pateikiami, kaip komentarai.

### Epic

- https://github.com/atviriduomenys/katalogas/issues/55

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/38
- https://github.com/atviriduomenys/katalogas/issues/31
- https://github.com/atviriduomenys/katalogas/issues/29

**Comment by sirex** [comment]
Sukūrus užduotį siunčiamas el. pašto laiškas.

**Comment by sirex** [comment]
Skriptas reikalingas šiai užduočiai priklauso nuo tqdm ir typer bibliotekų, kurios nėra įdiegiamos, nes yra `dev` paketų grupėje, reikia perkelti į pagrindinę grupę, kad šie paketai būtų įdiegti gamybinėje aplinkoje.

https://github.com/atviriduomenys/katalogas/blob/d58dceb35a006b2b4934290a4b069aa5100413e0/pyproject.toml#L63-L65

**Comment by adp-atea** [comment]
1.. Pasirinkus filtro punktą kuriame nėra reikšmių dingsta filtro punktai:


  ![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/5e5affcf-2168-4683-b7b4-dc33752abe9b)

   Reikėtų, kad filtrai liktų, kad būtų galimybė pasirinkti kitą reikšmę, kaip pvz yra padaryta prie organizacijos duomenų rinkinių:



   ![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/00cbcaa8-2d83-4111-a943-f58c203bbcf0)
