### ISSUE TITLE
Paieška tituliniame

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#425]
- Bendra paieška Duomenų rinkinių puslapyje turi veikti visų filtrų sąrašuose.

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/9fbaefd5-fada-41e4-a4ac-6758d67d60ab)
- Neaišku kokia klavišo "Filtro rezultatai"prasmė
- Neveikia rūšiavimo funkcija 

Neveikiančių/neįgyvendintų klavišų ir funkcijų nerodyti

**Comment by adp-atea** [comment]
Juliau, ar pirmame punkte turite omenyje, kad paieškos laukelis turi būti rodomas ir grafikų/statistikos puslapiuose?

**Comment by JuliusLADP** [comment]
Nemanau, kad grafikuose paieška reikalinga. Ji reikalinga susirandant pagal teksta  visuose rinkinių metadomenų laukuose, gal filtrų sąrašuose - nežinau, kokia realizacija yra optimalesnė.

**Comment by sirex** [comment]
Kaip suprantu, @JuliusLADP turi mintyje, kad paieška turi ieškoti, net tik pagal pavadinimą, bet ir pagal kitus atributus.

Taip pat svarbu, kad paieška pirmiausiai rodytu tuos duomenų rinkinius, kurie labiausiai atitinka paieškos žodžius:

https://django-haystack.readthedocs.io/en/master/boost.html

Siūlau taikyti tokias boost taisykles:

- Document boost:
  - Pirmiausiai rodomi duomenų rinkiniai, kurie susideda iš kitų duomenų rinkinių (duomenų rinkinių grupės), žiūrėti #332.
- Field boost:
  - title - 1.0
  - tags - 1.0
  - description - 0.9
  - (resource, model, property).title - 0.9
  - (request, project).title - 0.9
  - category.title - 0.8
  - organization.title - 0.8
  - (resource, model, property).description - 0.7
  - (request, project).description - 0.7
  - parent_category.title - 0.6
  - parent_organization.title - 0.6

**Comment by sirex** [comment]
Atidarius

https://test.data.gov.lt/datasets/?q=katalogo

Gaunu tokią klaidą:

```python
Internal Server Error: /datasets/
Traceback (most recent call last):
  File "django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "parler/templatetags/parler_tags.py", line 25, in render
    raise TemplateSyntaxError(f"Object '{object}' is not an instance of TranslableModel")
django.template.exceptions.TemplateSyntaxError:
    Object 'Atvirų duomenų katalogo duomenys' is not an instance of
    TranslableModel
```
