### ISSUE TITLE
Duomenų rinkinio narių sąrašas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#43]
Šiuo metu, [DCAT apibrėžia tokias standartines roles](https://www.w3.org/TR/vocab-dcat-2/#qualified-attribution):

- [dct:creator](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_creator),
- [dct:contributor](http://purl.org/dc/terms/contributor) ir
- [dct:publisher](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_publisher).

Visos kitos rolės apibrėžiamos per [prov:wasAttributedTo](https://www.w3.org/TR/prov-o/#wasAttributedTo).

Reikia įgyvendinti galimybę duomenų rinkiniams priskirti įvairias skirtingų organizacijų ar asmenų roles.

Visai tai daroma rinkinio narių sąraše. Apie duomenų rinkinio narius saugomi tokie duomenys:

- `user` - naudotojas, gali būti nenurodytas, jei narys yra organizacija.
- `organization` - organizacija, būtina nurodyti.
- `role` - kokia naudotojo ar organizacijos rolė su duomenų rinkiniu.
  - `creator` - duomenų rinkinio autorius.
  - `contributor` - duomenų rinkinio tvarkytojas.
  - `publisher` - duomenų rinkinio platintojas.
- `created` - kada narys buvo pridėtas.
- `contact` - ar šis narys yra rodomas rinkinio kontaktų sąraše.

URL:

- `/datasets/<orgs:Organization.kind>/<orgs:Organization.slug>/<datasets:Dataset.slug>/members/`

- [ ] Rinkinio tvarkytojų sąrašas pasiekiamas iš rinkinio kontekstinio meniu.
- [ ] Kol kas sąraše rodomas vienas tvarkytojas `datasets.Dataset.representative` arba `datasets.Dataset.manager`. Vėliau turės būti rodomi keli tvarkytojai iš `datasets:Managers` lentelės.

**Comment by adp-atea** [comment]
Ignore branch #145, check #177
