### ISSUE TITLE
Nesutampa skaičiai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#436]
Nesutampa skaičiai: 716+515+92=1323

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/c0b82ea6-587a-44a5-8fb7-1a276868bfcb)

**Comment by sirex** [comment]
Gal galima gauti nuorodą į konkretų puslapį, kuriame nesutampa skaičiai?

**Comment by JuliusLADP** [comment]
https://test.data.gov.lt/datasets/ pradiniame Duomenų rinkiniai puslapyje

**Comment by adp-atea** [comment]
Panašu, kad situacija susidaro, kai pridedami nauji duomenų rinkiniai. Pridėjus rinkinį joks statusas nesuteikiamas, todėl ir prie filtro neatsiranda. Dabar panaudojau reikšmę "Nepriskirta", kuri jau buvo pridėta prie galimų filtro reikšmių, bet nepanaudota.
Bet ar tinka toks variantas? Ar turėtų vis dėl to būti kažkoks statusas priskirtas?

**Comment by sirex** [comment]
Toks variantas netinka, tokios būsenos kaip „Nepriskirta“ nėra, jei duomenų rinkinys publikuojamas, jo būsena turėtu būti „Tik inventorintas“.

Čia problema tame, kad įgyvendinant #242 užduotį, buvo sukurta migracija, kad sutvarkyti rinkinių ir poreikių statusus, bet migracijos pagalba sutvarkomi tik istorinių rinkinių ir poreikių statusai, tačiau, sukūrus naują Rinkinį ar Poreikį, joks statusas nesuteikiamas.

Nuoroda į migraciją, kuri sukuria statusus istoriniams duomenims:

- https://github.com/atviriduomenys/katalogas/issues/242
- https://github.com/atviriduomenys/katalogas/pull/249/commits/9f820b7f2b39ba4a7c0172babcd3b8cd4cbb9856

Būtent iš to, kad nesuteikiami statusai, išplaukia eilė kitų problemų ir klaidų:

- https://github.com/atviriduomenys/katalogas/issues/396#issuecomment-1723297746
- https://github.com/atviriduomenys/katalogas/issues/540
- https://github.com/atviriduomenys/katalogas/issues/494

**Comment by adp-atea** [comment]
Vis dar nesutampa skaičiai

**Comment by adp-atea** [comment]
Kaip suprantu, jei panaikinam "Nepriskirta" būseną, o inventorintas duomenų rinkinys tampa tik jį publikavus, tai taip ir gali būti, kad skaičiai nesutaps, nes filtre prie statusų nepriskaičiuos nepublikuotų rinkinių, nes jie kol kas būsenos neturės.

**Comment by sirex** [comment]
„Nepriskirta“ būseną reikėtu rodyti tik koordinatoriui arba tvarkytojui, kuris Rinkinių sąraše mato ir nepublikuotus koordinatoriaus/tvarkytojo tvarkomus rinkinius. Visiems kitiems, būsenos „Nepriskirta“ nerodome, nes paprastiems naudotojams rodomi tik publikuoti duomenų rinkiniai, todėl tokių rinkinių kaip „Nepriskirta“ negali būti.

**Comment by adp-atea** [comment]
Grąžintas "Nepriskirta" statusas. Jei paprastas naudotojas mato "Nepriskirta", tai yra dėl to, kad yra duomenų rinkinių, kurie buvo pridėti prieš pataisymą ir vis dar neturi jokio statuso.

Reikės, kad būtų vėl paleidžiamos migracijos, kad sutvarkytų duomenis.
