### ISSUE TITLE
Paieška ilguose filtrų sąrašuose

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#437]
Įgyvendinti rinkinių sąrašo puslapyje paiešką ilguose filtrų sarašuose https://test.data.gov.lt/datasets/:

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/ece232e7-2130-482f-812c-7d656a04da56)

Pavaldumo srities, Kategorijų, Organizacijų ir kitus filtrų ilgų sąrašų paieška (dabar neveikia)

**Comment by sirex** [comment]
Dubliuoja https://github.com/atviriduomenys/katalogas/issues/424.
