### ISSUE TITLE
Chackbox pažymėjimas/atžymėjimas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#438]
Įgyvendinti duomenų rinkinių išrankos suformavimą, pažymint norimus pasirinkimus pagal Pavaldumo srities, Kategorijų, Organizacijų  ir kt. sąrašus, juos pažymint-nužymint "check box" . Ypač nepatogu, kad negalima spustelėjus pažymėtą chack box (jis automatiškai pasižymi paspaudus ant teksto) nuimti/nužymėti
https://test.data.gov.lt/datasets/ :

![Image](https://user-images.githubusercontent.com/69783864/260382979-b896314f-2d84-44c8-aa4c-db67830709e8.png)

**Comment by sirex** [comment]
Tiesiog reikia padaryti galimybę pašalinti filtrą, paspaudus ant aktyvaus filtro. Tarkime jei paspaudžiama ant „Atverti duomenys“, tai paspaudus ant jo dar kartą, filtras pagal „Atverti duomenys“ būsiena pašalinamas.
