### ISSUE TITLE
Duomenų rinkinio duomenų pateikimas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#440]
Įgyvendinti Duomenų rinkiniai puslapyje https://test.data.gov.lt/datasets/:

- rinkinio aprašymo turinį papildyti: kairėje pagal galimybę - kategorija, o dešinėje išvedant rinkinio perižiūrų, parsisiuntimu ir patikimo parametrus, taip kaip buvo suderinta dizaino eskize:
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/ea11420b-4050-44fe-9266-2009c5129c6b)

**Comment by sirex** [comment]
Patikslinu, kad kalba eina apie šias vietas pažymėtas paveiksliuke:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/d92577ce-8981-4104-b3c9-d4937c14e3e3)

**Comment by sirex** [comment]
@JuliusLADP šiuo metu, prie vieno duomenų rinkinio galima priskirti kelias kategorijas. Jei priskirtos kelios kategorijos, kurios kategorijos paveiksliuką rodyti?

**Comment by JuliusLADP** [comment]
Tikėtina, kad pirma priskirta kategorija ir yra pagrindinė, todėl ją ir reikėtų rodyti

**Comment by sirex** [comment]
Problema tame, kad nėra tokio dalyko, kaip pirma ar antra kategorija, jos visos lygiavertės.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/8ed6c4fa-07f5-4570-8263-f6a268d46fa8)

Kaip suprantu, kategorijas reikėtu rūšiuoti pagal pavadinimą ir pasirinkti pirmą pagal abėcėlę?

**Comment by JuliusLADP** [comment]
Tai tuomet pirma pagal sąrašą (abėcėlę).
