### ISSUE TITLE
Diagramos atskiruose puslapiuose

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#441]
Šių grafikų kol kas taupant laiką ir resursus nedaryti tik išlaikyti tą pačia išdėstymo logiką ir kituose (apatinis pav.) ![Image](https://github.com/atviriduomenys/katalogas/assets/297583/2abf9252-a924-4f3d-b1db-f95071457106)
-- https://test.data.gov.lt/datasets/stats/status/?

Viename puslapyje rodyti vieną diagramą, perjungimas iš vienos į kita atliekamas kontekstiniame meniu virš diagramos.

Šiame pavyzdyje būklių juostas reikėtų sukeisti vietomis:

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/123e71f5-8fe7-4b8c-b427-0be3b5183e6e)

**Comment by sirex** [comment]
Kaip suprantu, dabar padaryta, kad laiko ir stulpelinės diagramos yra rodomos viename puslapyje.

Jei būtų atskiri puslapiai, tada taip, galima įdėti dvi piktogramas. Nors asmeniškai palikčiau vieną piktogramą, o perjungimą padaryčiau pačiame diagramos puslapyje, kad filtro juosta būtų mažiau vizualiai apkrauta.

Susijusi užduotis:

- https://github.com/atviriduomenys/katalogas/issues/316

**Comment by JuliusLADP** [comment]
Geriausia realizacija: pasirinkimas tame pačiame puslapyje

**Comment by sirex** [comment]
Jau turime laiko diagramas, kuris įgyvendintos tame pačiame puslapyje, kaip ir stulpelinės diagramos. Todėl ši užduotis tampa nebeaktuali ir galima ją uždaryti?

**Comment by JuliusLADP** [comment]
Jau anksčiau rašiau, kad "Geriausia realizacija: pasirinkimas tame pačiame puslapyje" - kaip kad pats ir pasiūlei. Matyt duotoju momentu reikia tik pataisyti kad bent normaliai veiktų taip kaip padaryti (aprašinėju naujame trūkume grafikų problemas). O pasirinkimo galimybę tame pačiame puslapyje  nukelti vėliau, sutariant, kad tai nebus pakeitimas, o tik priimtinas vartotojui ir užsakovui. Abejų grafikų sukišimas į vieną langa visškai nelogiškas - niekas nežiūri iš karto dvejų grafikų, be to jie ir į vieną langą nesutelpa.

**Comment by sirex** [comment]
_(originalus aprašymas)_

Įgyvendinti Duomenų rinkiniai puslapyje https://test.data.gov.lt/datasets/:


- nuorodas  į diagramų tipus (jeigu bus realizuotas skirtingų diagramų "laiko/juostinių" atvaizdavimas skirtinguose languose) aktyvuoti iš ikonų prie filtro pavadinimo (kaip buvo suderinta dizaino projekte), o ne iš sąrašo elemento. Pvz.: 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/42be9012-aa95-40be-a1b2-a5ebcddcc3ce)
