### ISSUE TITLE
Panaudos atvejo registracija

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#444]
Panaudos atvejo registravimo formą papildyti galimybe susieti aprašomą panaudos atvejį su panaudotais ir ADP registruotais duomenų rinkiniais https://test.data.gov.lt/projects/add/ 

![Image](https://user-images.githubusercontent.com/69783864/260405053-963e8c09-8a14-414d-b728-58271061a898.png)

**Comment by sirex** [comment]
Dabar tokia galimybė yra, tik ji yra ne pačioje formoje, bet atsikrame sąraše, žiūrėti susijusias užduotis:

- https://github.com/atviriduomenys/katalogas/issues/4
- https://github.com/atviriduomenys/katalogas/issues/41

Dabar padaryta taip, kad poreikis priskiriamas rinkiniui, per rinkinio poreikių sąrašą. Taip padaryta todėl, kad duomenų rinkinių yra labai daug, todėl patogiau duomenų rinkinių paiešką atlikti duomenų rinkinių sąraše, o tada suradus konkretų duomenų rinkinį, galima jį priskirti prie poreikio, kurių yra nedaug, nes rodomi tik tie poreikiai, kuriuos sukūrė naudotojas.

https://test.data.gov.lt/datasets/2091/requests/

Tačiau iš koordinatoriaus/tvarkytojo perspektyvos, matyt patogiau priskyrimą daryti per poreikio rinkinių sąrašą, rodant tik tuos rinkinius, kuriuos tvarko naudotojas:

https://test.data.gov.lt/requests/14299/datasets/

Bet kokiu atveju, čia greičiau būtų naujas funkcionalumas, o ne trūkumas, todėl siūlyčiau šalinti šią užduoti iš trūkumų sąrašo.

**Comment by JuliusLADP** [comment]
Manau, kad trūkumas, nes sąlygose yra vartotojo sąsajos patogumo ir intuityvumo reikalavimas.
