### ISSUE TITLE
Užduočių langas

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#446]

**Comment by aurjas** [comment]
Užduočių lange https://test.data.gov.lt/users/160/tasks/ neaiškus užduoties turinys ir nėra nuorodos, kuri įvestų į veiklos kontekstą.

**Comment by sirex** [comment]
Užduočių puslapis buvo nemažai patobulintas su šia užduotimi:

- https://github.com/atviriduomenys/katalogas/issues/42

Ar po pataisymų trūkumai vis dar išliko?

**Comment by aurjas** [comment]
Klaida ištaisyta
