### ISSUE TITLE
Įtraukti į planą formos pakeitimai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#448]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/20475485-9a49-440d-b32d-bb4ba8ba7a66)
-- https://test.data.gov.lt/requests/14310/plans/

Vietoj dviejų mygtukų palikti tik vieną „Įtraukti į planą“. Šis mygtukas turi atidaryti įtraukimo į planą formą:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/49315f46-98e7-4839-9e04-cd74b5c96057)

Formoje, reikia pašalinti šiuos laukus:

- Nuoroda į viešąjį pirkimą
- Pirkimo kaina, EUR
- Projektas

Jei `User.organization` yra Atvėrimo duomenų teikėjas, tada:

- Paslaugų gavėjas - pagal nutylėjimą parinkta `user.organiation`.
- Paslaugų teikėjas - pagal nutylėjimą parinkta `user.organization`.

Jei `User.organization` nėra Atvėrimo duomenų teikėjas, tada:

- Paslaugų gavėjas - lauko nerodome ir saugant formą, priskiriam `user.organization`.
- Paslaugų teikėjas - pagal nutylėjimą parinkta `user.organization`.

Formos pavadinimą „Naujas planas“ keičiam į „Įtraukti į planą“.

Formos submit mygtuką „Sukurti“ keičiam į „Įtraukti“.

Formos apačioje, žemiau submit mygtuko rodome antraštę „Prijungti prie egzistuojančio įrašo plane“ ir žemiau antraštės rodome tokį sąrašą:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/b5b02ce2-60e5-4482-8255-c04a4af8bfd6)
-- https://test.data.gov.lt/requests/14310/plans/include/

Tik plano sąraše prie pavadinimo, skliausteliuose rodome termino datą, jei ji yra nurodyta. Jei termino data nenurodyta, nepaliekame tuščių skliaustelių.

Mygtukas poreikio peržiūroje „Įtraukti į planą“ turi vesti į formą, kuri aprašyta aukščiau.

Mygtukai „Įtraukti į planą“ neturi dingti, jei būsena pakeista į „Patvirtintas“. Mygtukai dingsta tik tuo atveju, jei būsena pakeista į „Atmestas“ arba „Atvertas“.

Įtraukus poreikį į Planą, turi susikurti sisteminis komentaras prie Poreikio, su informacija, kad Poreikis buvo įtrauktas į planą, su nuoroda į Terminą plane.

Analogiškai tą patį reikia padaryti ir Duomenų rinkinio plane.

**Comment by sirex** [comment]
_(originalus aprašymas)_

Kontekstinė informacija apie planavimo procesą:
- Numatomų atverti rinkinių plano duomenis sudaro: Numatyto atverti duomenų rinkinio pavadinimas, numatomas atvėrimo terminas, atverianti organizacija (Valstybinė duomenų agentūra (VDA) arba bet kuri kita institucija/organizacija), Atvėrimo pobūdis (esamo rinkinio duomenų papildymas/Naujo rinkinio atvėrimas)
- planą sudaro įrašai, kai VDA arba institucija, kuriai nukreiptas poreikis, priima sprendimą atverti naują arba papildyti esamą duomenų rinkinį, padarydami atitinkamus įrašus ADP. Tai atlikus, rinkinys/-iai yra įtraukiami į bendrą planą, kuris viešai preinamas ADP;
- Viešai publikuojamas planuojamų atverti rinkinių sąrašas turi filtrus: pagal Valdymo sritis, Institucijas, Numatomą atvėrimo periodą, naujas/papildymas požymius

https://test.data.gov.lt/requests/242/ - nerodo mygtuko „Įtraukti į planą“.


![Image](https://github.com/atviriduomenys/katalogas/assets/297583/39521c97-1f52-4866-9552-77b76663f743)


Nors kitoje vietoje rodo:

https://test.data.gov.lt/requests/241/


Paspaudus mygtuką „Įtraukti į planą“, turėtu iš karto rodyti įtraukimo į planą formą ir formos apačioje pasiūlyti įtraukimą į anksčiau sukurtą planą:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/42b56310-39fb-465b-9cde-b06b71a02757)

Tačiau rodome tik „Įgyvendinimo terminas“, „Paslaugų teikėas“ ir „Paslaugų teikėjo pavadinimas“. Pavadinimas generuojamas automatiškai, naudojant poreikio pavadinimą.

O žemiau formos rodomas sąrašas anksčiau sukurtų planų sąrašas ir pasiūloma įtraukti į jau esamą planą.

Ir turėtu būti trečias pasirinkimas, atsisakyti atverti. Atsisakius atverti, sukuriamas naujas įrašas Planų lentelėje, pažymint, kad atsisakoma atverti duomenis. Planų sąraše tai rodoma, kaip įprastas įrašas, tik nurodoma, kad atsiakoma atverti.

Toks mygtukas rodomas tik organizacijoms, kurios teikia duomenų atvėrimo paslaugas, `Organisation.provider == True`.

**Comment by adp-atea** [comment]
Dingo laukas "Paslaugų gavėjas", @sirex ar jis čia turėtų būti?

**Comment by adp-atea** [comment]
Galbūt atitiko šią vietą - https://github.com/atviriduomenys/katalogas/issues/448#:~:text=Paslaug%C5%B3%20gav%C4%97jas%20%2D%20lauko%20nerodome%20ir%20saugant%20form%C4%85%2C%20priskiriam%20user.organization.

**Comment by sirex** [comment]
Lauką “Paslaugų teikėjas“ rodome tuo atveju, jei yra daugiau nei viena organizacija iš `PlanDataset.dataset.organization` ir `PlanRequest.request.organizations`, kurias atstovauja `Representative`, čia įskaitant Dataset ar Request, kurie tik traukiami į Planą, bet dar neišsaugoti.

Tarkime, jei į Planą traukiame Poreikį, kuris priskirtas 5 skirtingiems Dataset, kurie priklauso 5 skirtingom organizacijom, ir naudotojas yra 3 Poreikio Rinkinių tvarkytojas, tada rodome „Paslaugų teikėjas“ lauką, su 3 organizacijų pasirinkimu, kurių rinkinius tvarko naudotojas.

Jei naudotojas būtų tik vienos organizacijos tvarkytojas, tada jam iš vis nereikia rodyti „Paslaugų teikėjas“ lauko, tiesiog saugant formą priskirti Representative organizaciją, kuri sutampa su Dataset.organization arba Request.organizations.

**Comment by adp-atea** [comment]
Aptarus su Mantu, šiek tiek pakeistos pasirinkimų reikšmės:

Organizacijos plano forma:

- Teikėjo lauko pasirinkimai: pati organizacija + visi teikėjai (organizacijos, pažymėtos kaip "Duomenų atvėrimo paslaugų teikėjas").
- Gavėjo lauko nerodom, priskiriam pačią organizaciją.

Duomenų rinkinio plano forma:

- Teikėjo lauko pasirinkimai: rinkinio organizacija + visi teikėjai.
- Gavėjo lauko nerodom, priskiriam duomenų rinkinio organizaciją.

Poreikio plano forma:

- Teikėjo lauko pasirinkimai: poreikio organizacijos, kuriose prisijungęs naudotojas yra tvarkytojas/koordinatorius (jei naudotojas yra adminas - visos poreikio organizacijos) + visi teikėjai.
- Gavėjo lauko pasirinkimai: poreikio organizacijos, kuriose prisijungęs naudotojas yra tvarkytojas/koordinatorius (jei naudotojas yra adminas - visos poreikio organizacijos). Jei tokia organizacija yra tik viena, lauko nerodom ir ją priskiriam kaip gavėją.
