### ISSUE TITLE
Organizacijos forma

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#451]
Organizacijos Lietuvos sveikatos mokslų universiteto ligoninė Kauno klinikos duomenų redagavimo formoje bandant panaikinti/pakeisti neteisingą logotipą (įdėta IVPK) https://test.data.gov.lt/orgs/12/ 
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/1d4277c0-eb24-4231-9dac-2d89c212d4a4)
https://test.data.gov.lt/admin/vitrina_orgs/organization/12/change/?_changelist_filters=q%3DKauno
 ir paspaudus "Išsaugoti" klavišą išmeta klaidą 500

**Comment by sirex** [comment]
Reikia nuorodos į konkrečią vietą, kurioje pasireiškė klaida.

**Comment by JuliusLADP** [comment]
pridėjau

**Comment by adp-atea** [comment]
Panašu, kad hierarchijos duomenys susigadinę. Reikėtų praleisti `Organization.fix_tree(fix_paths=True)` komandą per shell arba jei reikia galima sukurti skriptą, bet galbūt nelabai apsimoka dėl vienos eilutės.

**Comment by JuliusLADP** [comment]
Aš negaliu patikrinti visos aibės ar čia vienintelis atvejis? Esmė, kad pastebėjus, neleidžia ištrinti ar pakeisti. Kad neleidžia ištrinti/pakeisti, tai čia funkcinis trūkumas

**Comment by sirex** [comment]
Paleidau `Organization.fix_tree(fix_paths=True)`, pabandžiau įkelti paveiksliuką, atrodo klaidų nėra. @JuliusLADP ar galite dar kartą patikrinti, ar veikia?

**Comment by JuliusLADP** [comment]
Ištrinti leido. Tik pastebėjau, kad atsirado du tos pačios organizacijos įrašai - spėju, kad taip neturėtų būti


![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/5c2923e5-ec54-4453-a105-5bd3482dbfe8)

**Comment by sirex** [comment]
Dėl dubliavimo sukurta nauja užduotis:

- https://github.com/atviriduomenys/katalogas/issues/519
