### ISSUE TITLE
Sutvarkyti švieslentės rodiklius

### ISSUE THREAD

**Issue by adp-atea** [atviriduomenys/katalogas#460]
Sutvarkyti reikšmes pasirinkus kitus rodiklius

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/3fab8fa8-5875-421a-908b-960307940116)

Dabar pasirinkus bet kurį kitą rodiklį, nei duomenų rinkiniai, rodo nulį, nors turėtu rodyti realius skaičius.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/402
- https://github.com/atviriduomenys/katalogas/issues/492

**Comment by sirex** [comment]
Čia kaip suprantu eina kalba apie tai, kad pasirinkus modelių, properčių, objektų skaičių visur rodomi nuliai, nes nėra skripto, kuris tuos skaičius atnaujintų?

Taip pat klaidingai rodo poreikių ir projektų skaičių, čia tikriausiai susiję su tuo pačiu skriptu?

**Comment by JuliusLADP** [comment]
kitos švieslenčių problemos: [Švieslentės klaidos#485](https://github.com/atviriduomenys/katalogas/issues/485)
-

**Comment by sirex** [comment]
_(originalus aprašymas)_

Sutvarkyti reikšmes pasirinkus kitus rodiklius


![Image](https://user-images.githubusercontent.com/107176624/261310090-5bd959ea-5a22-46a4-8f80-6707f84af85f.png)

Dabar pasirinkus bet kurį kitą rodiklį, nei duomenų rinkiniai, rodo nulį, nors turėtu rodyti realius skaičius.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/402

**Comment by sirex** [comment]
Skriptas `scripts/create_dataset_stats.py` paleistas, tačiau trumpai užmetus akį, rodo įdomius skaičius, pavyzdžiui:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/1aae08a7-b8ae-48a5-996d-a73b822ef269)
-- https://test.data.gov.lt/datasets/stats/status/?duration=duration-monthly&indicator=distribution-count

Visi duomenų šaltiniai sukurti per paskutinį mėnesį.  Tas pats ir su Poreikiais ir su Panaudojimo atvejais.

Stulpelinė diagrama lyg ir gerai veikia, tačiau skaičių netikrinau, panašu, kad statistika laike rodoma tik už paskutinį mėnesį.

**Comment by adp-atea** [comment]
Prieš leidžiant pataisytą skriptą, turbūt reikėtų išvalyti DatasetStats lentelę, kad nebūtų neteisingų duomenų.
