### ISSUE TITLE
Rinkinio priskyrimas grupei

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#475]
Duomenų rinkinio metaduomenų redagavimo formoje pridėti lauką (neprivalomas), kuriame galima pasirinkti rinkinio priskyrimą kuriai nors Rinkinių grupei ir pogrupiui. Pvz.;
Didelės vertės duomenys**
>Erdviniai duomenys
>Juridinių asmenų duomenys
>Statistiniai duomenys
> ........_

https://test.data.gov.lt/datasets/12/add/?language=lt 
Rinkinių grupių ir jų pogrupių sarašai tvarkomi per vyr.aministratoriaus sąsają administravimo sąsają [Duomenų grupės#467](https://github.com/atviriduomenys/katalogas/issues/467)

**Comment by sirex** [comment]
Priskyrimas grupei gali būti daromas vienu iš dviejų būdų:

1. Priskyrimas kategorijos grupei:

  ![image](https://github.com/atviriduomenys/katalogas/assets/297583/88cdcc9d-75c6-4514-aa3b-1dd41b1444f4)
  -- https://test.data.gov.lt/datasets/12/

  ![image](https://github.com/atviriduomenys/katalogas/assets/297583/cc84ea62-c726-4196-9d29-9e19b4edf259)
  -- https://test.data.gov.lt/datasets/12/category/

2. Duomenų rinkinių grupavimas:

  ![image](https://github.com/atviriduomenys/katalogas/assets/297583/0c0ee48e-a268-4d38-8c72-04886a6d2a1d)
  -- https://test.data.gov.lt/datasets/12/

  ![image](https://github.com/atviriduomenys/katalogas/assets/297583/4daa361c-b0b9-49b4-b238-27621f4a55ea)
  -- https://test.data.gov.lt/datasets/12/relation/add/

**Comment by JuliusLADP** [comment]
Trūksta Filtro "Duomenų rinkinių grupės" Duomenų rinkiniai lange https://test.data.gov.lt/datasets/?selected_facets=organization_exact%3A8

**Comment by sirex** [comment]
Dubliuoja:

- https://github.com/atviriduomenys/katalogas/issues/467
