### ISSUE TITLE
Panaudos atvejai

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#476]
Iš dabartinės versijos neperkelti panaudos atvejų paveiksliukai. Privesta daug testinių rinkinių, kurie susieti su realiais rinkiniais. Ar šalinant pavyzdžius nebus ištrinti ir susiję duomenų rinkiniai
https://test.data.gov.lt/projects/

![Image](https://user-images.githubusercontent.com/69783864/262562437-a295739c-dd6a-4c49-bb64-5fd4f753bfe2.png)

**Comment by sirex** [comment]
Šalinant Panaudojimo atvejus, susiję duomenų rinkiniai neturėtu būti ištrinti, o jei ir būtų ištrinti, tai būtų klaida.

**Comment by sirex** [comment]
O dėl paveiksliukų, pažiūrėsiu. Anksčiau paveiksliukai lyg ir veikė.

**Comment by JuliusLADP** [comment]
- Paveiksliukų nesimato
- registruojant naują panaudos atvejį, patogiausia iš registracijos formos nueiti į rinkinius ir pasinaudojant rinkinių paieškos funkcionalumu, priskirti rinkinius šiam panaudos atvejui .

**Comment by JuliusLADP** [comment]
Panaudos atvejų grafinės iliustracijos naujoje versijoje yra perkeltos ne į pradinį sąrašą, o atskiro atvejo peržiūros formoje. Turėtų būti perkelta taip kaip senoje versijoje (iškarpa).
Paveiksliuko paskirtis yra iliustracinė reklaminė, suteikianti abstraktų panaudos atvejo esmės suvokimą ir padedanti lankytojui susiorientuoti ir atsirinkti kas jam įdomu sužinoti detaliau. Iliustracija neturi detalios informacijos ir jos pateikimas kartu su detalia informacija - netikslingas.
