### ISSUE TITLE
Panaudos atvejo registracijos forma

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#477]
Panaudos atvejo registracijos formoje pridėti lauką, kuris leidžia pridėti pasirinktus duomenų rinkinius - panašiai kaip senoje versijoje:
![Image](https://user-images.githubusercontent.com/69783864/262563601-ce3a744f-b573-400b-ba89-38a8931db0f8.png)

**Comment by sirex** [comment]
Buvo priimtas sprendimas, duomenų rinkinių priskyrimą daryti ne poreikio formoje, o atskirai iš duomenų rinkinių sąrašo.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/f0bffde1-e580-481e-a074-4c3bd76096c7)

Taip padaryta todėl, kad duomenų rinkinių yra labai daug ir juos sudėtinga surasti vien tik pagal pavadinimą. Todėl rinkinių priskyrimas poreikui daromas per rinkinių sąrašą, kur yra paieška, filtrai, rodoma išsami informacija apie rinkinius.

Pirmiausiai sukuriamas poreikis, po to, rinkinių sąraše pasirinkus norimą rinkinį, galima jį priskirti vienam ar keliems poreikiams.

Kitas variantas, galima registruoti poreikį rinkinio peržiūros puslapyje, ko pasekoje, rinkinys iš karto susiejamas su poreikiu:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/a7f6ecc1-915b-43fd-975b-e9e1fe7f6a10)

**Comment by sirex** [comment]
Tik dabar pastebėjau, kad kalba eina apie Panaudojimo atvejus, o ne apie poreikius, tačiau su Panaudojimo atvejais, veikimas lygiai toks pat.

Senoje ADP versijoje, praktiškai nei vienas poreikis neturi priskirtų rinkinių, nes jų priskyrimas formoje yra per daug sudėtingas, pats tai bandžiau daryti su šiuo Panaudojimo atveju:

https://test.data.gov.lt/projects/34

Dabar mano supratimu, padaryta žymiai patogiau, susirandi rinkinį ir gali priskirti Panaudojimo atvejui:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/31b20225-660c-47d6-8a2b-908a4f6193d2)

**Comment by sirex** [comment]
Galima nebent Panaudojimo atvejui priskirtų Duomenų rinkinių sąraše įdėti nuorodą, su kvietimu priskirti Duomenų rinkinius Panaudojimo atvejui. Nuoroda tiesiog vestų į duomenų rinkinių sąrašą.

Gal būt dar nuoroda galėtu turėti veiksmo pavadinimą, kuris nurodo, kad Duomenų rinkinių sąrašas turėtu rodyti mygtuką, pridėti duomenų rinkinį prie Panaudojimo atvejo.
