### ISSUE TITLE
Švieslentės klaidos

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#485]
- Paspaudus ant filtro pavadinimo "Rinkinio būsena" (turi būti "Rinkinių būsena") išmeta 500 klaidą
https://test.data.gov.lt/datasets/stats/status/?
- neatitinka legendos ir pačio grafiko spalvos

![Image](https://user-images.githubusercontent.com/69783864/264036091-34014e60-98d3-4d6d-8081-da6bcb4f7eff.png)

![Image](https://user-images.githubusercontent.com/69783864/264035190-debf0146-bd82-4cce-990e-4577bf851749.png)

- Grafiko pavadinimas (virš legendos) neatitinka pasirinkto filtro tematiką ir pateiktų duomenų turinį: Buvo pasirinktas filtras Organizacijos https://test.data.gov.lt/datasets/stats/organization/?
- Nesutampa viršutinio ir aptinio grafikų turinys https://test.data.gov.lt/datasets/stats/category/? 

![Image](https://user-images.githubusercontent.com/69783864/264038615-6ab73880-a60a-47b7-b333-1b93f08de4b7.png)

![Image](https://user-images.githubusercontent.com/69783864/264039120-06744c2b-28ea-43b4-85b1-2de08e4c424b.png)

**Comment by adp-atea** [comment]
1. Turėtų susitvarkyti su #482.
2. Grafikų biblioteka pati automatiškai parenka spalvas ir jos atitinka reikšmes, tiesiog spalvos yra šiek tiek permatomos ir grafikas yra "stacked", todėl gali atrodyti tamsesnės.


Atnaujinant nepamirškite padaryti rebuild_index ir atsinaujinti stilius.
