### ISSUE TITLE
Neveikia Poreikio priskyrimas Rinkiniui

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#495]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/d4f39012-a451-465d-b6de-ecd096aeee2c)
-- https://test.data.gov.lt/datasets/1241/requests/

Prisijungus paprasto naudotojo teisėmis iš Rinkinio poreikių sąrašo, paspaudus „Pridėti poreikį“ gaunam `403 Forbidden` klaidą.

**Comment by adp-atea** [comment]
**Turi veikti taip:**

- Paprastas naudotojas gali įtraukti poreikius, kuriuos jis pats sukūrė, t.y. tik savo poreikius. (Paprastiems naudotojams mygtukas nerodomas, jei naudotojas neturi sukūręs nei vieno poreikio.)
- Tvarkytojas/koordinatorius poreikį gali įtraukti tik savo tvarkomuose rinkiniuose. 
- Super administratorius gali viską.

**- Veikia:** 

- Paprastiems naudotojams mygtukas nerodomas, jei net naudotojas turi sukūręs poreikį. PVZ: 
Sukūriau poreikį "Poreikis 495 test 2": https://test.data.gov.lt/requests/14322/ 


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/5ee6e4cc-040f-4919-891a-beb6a98c22a8)


Atsidarius bet kurį duomenų rinkinį, skiltį poreikiai, mygtukas "Įtraukti į poreikį" neatvaizduojamas


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/63c497a3-dc2d-4541-a9ec-e6d49670ff62)

**Comment by sirex** [comment]
Rinkinio poreikių sąraše rodomi visi rinkiniai, visiems, registruotiems ir neregistruotiems naudotojams.

Mygtukas „Pridėti poreikį“ prie rinkinio rodomas naudotojui, kuris yra užregistravęs bent vieną poreikį arba super adminui.

Bet kuris registruotas naudotojas (įskaitant ir koordinatorius/tvarkytojus), gali susieti su Rinkiniui tik savo registruotus Poreikius.

Papildomai, koordinatorius/tvarkytojus, gali susieti su savo tvarkomu  Rinkiniu ir ne savo registruotus poreikius, kurie yra adresuoti to koorinatoriaus/tvarkytojo organizacijai.
