### ISSUE TITLE
Priskyrimas organizacijai Poreikio formoje

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#496]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/cacf05c4-0f16-4c81-a55b-cc30a2f4c87c)
-- https://test.data.gov.lt/requests/add/

Pridėti [SELECT2](https://select2.org/) lauką, su Organizacijų sąrašu, sąraše rodyti top 10 organizacijų pagal rinkinių skaičių ir pateikti paiešką, įvedus į paieškos laukelį tris simbolius, sąraše rodo top 10 paieškos žodį atitinkančių organizacijų sąrašą surūšiuotą abėcėlės tvarka.

Reikia SELECT2 tipo lauko, kadangi iš JAR bus importuota daug organizacijų ir sąrašas bus labai ilgas.

### Priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/265

**Comment by Faustasm** [comment]
Tai įgyvendinta, kadangi perpanaudojau tą organizacijų sąrašą priskiriant organizacijas poreikiam iš poreikio organizacijų tabo https://github.com/atviriduomenys/katalogas/pull/521

**Comment by sirex** [comment]
https://github.com/atviriduomenys/katalogas/issues/46 jau įkeltas į test.data.gov.lt, bet formoje niekas nepasiekitė:

https://test.data.gov.lt/requests/add/
