### ISSUE TITLE
Nerodyti „Įtraukti į planą“ mygtuko

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#497]
![Image](https://user-images.githubusercontent.com/297583/264449617-58a6cf0e-566d-4af1-9c5e-046b28b085c6.png)
-- https://test.data.gov.lt/requests/14310/

Nerodyti „Įtraukti į planą“ mygtuko, registruotiems naudotojams, kurie nėra jokios organizacijos Representative ir kurie nėra super administratoriai.

**Comment by JuliusLADP** [comment]
klavišą ![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/867d4e76-9ada-48a0-9ab1-b366c90585a0)padaryti prieinamu tik poreikio autoriui ir institucijos, kuriai nukreiptas poreikis koordinatoriui, pastarajam leidžiant Poreikio registravimo formoje tik keisti organizaciją (t.y. taip įvykdant nukreipimo kitai organizacijai arba kelioms organizacijoms veiksmą).

Nukreipus kitai organizacija, turi išlikti galimybė, poreikio įgyvendinimą įsitraukti į savo institucijos planą.

**Comment by adp-atea** [comment]
Nerodo institucijos, kuriai nukreiptas poreikis koordinatoriui. 

Pridėtame poreikyje (https://test.data.gov.lt/requests/14329/) nurodžiau instituciją "Lietuvos transporto saugos administracija"

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/1c232dc2-efdf-4be8-aed9-736776afe1c6)

Šioje institucijoje kaip koordinatorių nurodžiau savo kitą userį: 


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/f5e4fa96-62d3-4481-8981-4d9f7aad4132)

Iš kito userio (organizacijos koordinatoriaus) atidarau poreikį, tačiau mygtuko keisti nėra

**Comment by adp-atea** [comment]
Aptarus su Mantu, pakeitimai:
1. Į planą gali įtraukti tik poreikio organizacijų nariai.
2. Keisti poreikio informaciją gali tik autorius.
