### ISSUE TITLE
Panaikinti antraštę Poreikio peržiūros puslapyje

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#498]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/35c20039-84e8-4a03-8826-b609909d097f)
-- https://test.data.gov.lt/requests/14310/

Antraštė nereikalinga ir ne visais atvejais atitinka Poreikio paskirtį.

**Comment by sirex** [comment]
@adp-atea kodėl vis dar neuždarytas #506 pull request?

**Comment by adp-atea** [comment]
Pull requestuose dubliavosi kodas, todėl #506 reiktų ignoruoti.
