### ISSUE TITLE
Plano lentelės pakeitimai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#499]
Dabar turime tokią organizacijos plano lentelę:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/dac71e75-4d6f-49e2-a4dd-f302248143ec)
-- https://test.data.gov.lt/orgs/269/plans/

Reikia pertvarkyti lentelę taip:

- Pirdėti stulpelį „Duomenų rinkiniai“, kurioje sąrašą duomenų rinkinių susietų su plano užduotimi, jei yra tik vienas rinkinys, tai rodome ne sąrašą, o tiesiog rinkinio pavadinimą. Paspaudus ant rinkinio pavadinimo, atidaromas rinkinio peržiūros puslapis.
- Perkeliam „Pavadinimas“ po „Terminas“ stulpelio ir keičiam „Pavadinimas“ į „Užduotis“.
- Pašalinti „Projektas“
- Pašalinti „Plano įgyvendinimo kaina“
- Pridėti stulpelį „Poreikis“, kuriame taip pat kaip ir „Duomenų“ rinkiniai, išvardintas sąrašas poreikių, kurie numatomi įgyvendinti,  susietų su užduotimi, jei yra vienas poreikis, tada rodomas ne sąrašas, o rinkinio pavadinimas. Paspaudus ant poreikio pavadinimo, atidaro poreikio peržiūros puslapį.

Pertvarkytos plano lentelės pavyzdys:

| Duomenų rinkinys | Terminas | Užduotis | Įgyvendina | Poreikis |
| --- |--- | --- | --- | --- |
| <ul><li>Atvirų duomenų katalogo duomenys</li><li>Duomenys apie elektronines paslaugas</li></ul> | 2023-06-30 | Naujų duomenų rinkinių atvėrimas | Atea | |
| Registrų duomenys | 2023-09-10 | Klaidų ištaisymai | Savarankiškai | <ul><li>registrai.lt duomenys</li><li>IS/R sąrašai</li></ul> |
| Registrų duomenys | 2023-10-15 | Naujų duomenų atvėrimas | Insoft | Registrų duomenų papildymas |

Atitinkamai pertvarkome plano lenteles ir Rinkinio Plane:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/cdc42b63-47ff-41ec-b888-4e7c89ad4042)
-- https://test.data.gov.lt/datasets/1223/plans/

Ir Poreikio Plane:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/4ae69858-359f-48dc-83de-2c0545f12d72)
-- https://test.data.gov.lt/requests/14307/plans/

Naujo plano formose, Plano užduoties pavadinimas generuojamas ne pagal Rinkinio ar Poreikio pavadinimą, o pagal užduoties pobūdį:

- „Duomenų atvėrimas“ - jei atveriamas naujas duomenų rinkinys, t.y. jei į Planą įtraukiamas duomenų rinkinys, kuris neturi nei vieno duomenų šaltinio.
- „Duomenų rinkinio papildymas“ - jei į Planą įtraukiamas duomenų rinkinys, kuris jau turi vieną ar daugiau duomenų šaltinių.
- „Duomenų rinkinio papildymas“ - jei į Planą įtraukiamas Poreikis.
- „Klaidų duomenyse pataisymas“ - jei į Planą įtraukiamas Poreikis, kuriame nurodyta klaida duomenyse.

**Comment by adp-atea** [comment]
Dar padaryti šią vietą:

"Naujo plano formose, Plano užduoties pavadinimas generuojamas ne pagal Rinkinio ar Poreikio pavadinimą, o pagal užduoties pobūdį:

„Duomenų atvėrimas“ - jei atveriamas naujas duomenų rinkinys, t.y. jei į Planą įtraukiamas duomenų rinkinys, kuris neturi nei vieno duomenų šaltinio.
„Duomenų rinkinio papildymas“ - jei į Planą įtraukiamas duomenų rinkinys, kuris jau turi vieną ar daugiau duomenų šaltinių.
„Duomenų rinkinio papildymas“ - jei į Planą įtraukiamas Poreikis.
„Klaidų duomenyse pataisymas“ - jei į Planą įtraukiamas Poreikis, kuriame nurodyta klaida duomenyse."

**Comment by adp-atea** [comment]
Tai jau buvo padaryta.
