### ISSUE TITLE
Organizacijų sąrašas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#508]
Pataisyti organizacijų sąrašą https://test.data.gov.lt/organizations/ , kad nebūtų painiojama, organizacijų grupės su organizacijomis.

Nevyriausybinęs organizacijos, Verslas, Savivaldybės ir  Ministerijų valdymo sritys ir kti.  yra grupės. Jos neturi būti rodomos organizacijų sąrašuose,. Valdymo sritys ir institucijos (organizacijos) yra skirtingos esybės.  
Organizacijas rikiuoti pagal ABC

**Comment by sirex** [comment]
![image](https://github.com/atviriduomenys/katalogas/assets/297583/a8d6d7e9-97be-4839-9739-a0d1372de9f8)
-- https://test.data.gov.lt/admin/vitrina_orgs/organization/276/change/

Reikia pridėti naują  Rolę, pavadinimu „Grupė“ ir jei organizacija turi rolę „Grupė“, tada jos nerodyti organizacijų sąraše, bet rodyti filtre.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/d7347bc8-6e52-4be1-ba26-45a88104ff92)
-- https://test.data.gov.lt/organizations/

Pavyzdžiui, „Nevyriausybinės organizacijos“, „Verslas“, „Savivaldybės“ turėtu nerodyti organizacijų sąraše dešinėje pusėje, tačiau turėtu rodyti Valdymo sričių filtre, kairėje pusėje.

Kad tai įgyvendinti, per Organizacijų administravimą, „Verslui“, „Savivaldybėms“ ir kitoms grupėms, kurios nėra organizacijos, bus priskirta rolė „Grupė“ ir jei tokia rolė priskirta, tai tokių įrašų dešinėje organizacijų sąrašo pusėje neturi rodyti.
