### ISSUE TITLE
Paveiksliukų rodymo trūkumai

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#518]
- UŽDAROMA, NES IŠSKAIDYTA Į ATSKIRUS APRAŠYMUS
- neperkelta iliustracijos iš senos versijos Panaudos atvejų formoje https://test.data.gov.lt/projects/ PERKELTA Į #546
- Tituliniame puslapyje nukirpta dalis paveikslėlio juostoje "Duomenų panaudojimo atvejai"  PERKELTA Į #547 547
- 
![Image](https://user-images.githubusercontent.com/69783864/265689900-5facfeed-d6f2-495b-9a06-ade2f543ef4f.png)
- mDuomenų paieška. Duomenų rinkiniai. Duomenų rinkinių “box’ai” nevienodo dydžio. https://test.data.gov.lt/

![Image](https://user-images.githubusercontent.com/69783864/265690978-c5d08b9f-29f5-4333-ba71-ae97c2c3b4f7.png)

 
Taisyti: Rodyti vienodo dydžio teksto lauką (Pavadinimas 2 eilutės, Aprašymas 4 eilutės), rodyti daugiausia peržiūrų surinkusius
- Pagrindinis puslapis. Duomenų teikėjai. Duomenų teikėjų “box’ai” nevienodo dydžio. Duomenų teikėjų logotipai, per dideli, kai kurie nevienodos bei prastos kokybės. Reikėtų taikyti tam tikras nuostatas paveiksliukų įkėlimo metu

![Image](https://user-images.githubusercontent.com/69783864/265703067-79bde8c2-7a4e-4489-b286-9f4e3e9f863f.png)

**Comment by sirex** [comment]
> neperkelta iliustracijos iš senos versijos Panaudos atvejų formoje https://test.data.gov.lt/projects/

Tokia užduotis jau yra:
- https://github.com/atviriduomenys/katalogas/issues/476

> Tituliniame puslapyje nukirpta dalis paveikslėlio juostoje "Duomenų panaudojimo atvejai"

https://github.com/atviriduomenys/katalogas/blob/06f5b24ddba4251449720a09a14dba0f6fe278dd/vitrina/settings.py#L287
Matyt reikia pašalinti `crop: true` ir pažaisti su [kitais parametrais](https://github.com/ui/django-thumbnails).

> Duomenų paieška. Duomenų rinkiniai. Duomenų rinkinių “box’ai” nevienodo dydžio.

Subjektyvi nuomonė: Man asmeniškai, gražu, kai nevienodo dydžio. Jei būtų fiksuotas dydis, tada dalis kortelių butų pustuštės ir dirbtinai ištemptos, kas vizualiai, bent jau asmeniškai man atrodo dar blogiau.

> Rodyti vienodo dydžio teksto lauką (Pavadinimas 2 eilutės, Aprašymas 4 eilutės), rodyti daugiausia peržiūrų surinkusius

Reikėtu patikrinti, ar padaryta duomenų migracija į [django-hitcount](https://django-hitcount.readthedocs.io/en/latest/). Jei migracija nepadaryta, gali į titulinį puslapį patekti, bet kokie rinkiniai.

> Pagrindinis puslapis. Duomenų teikėjai. Duomenų teikėjų “box’ai” nevienodo dydžio. Duomenų teikėjų logotipai, per dideli, kai kurie nevienodos bei prastos kokybės. Reikėtų taikyti tam tikras nuostatas paveiksliukų įkėlimo metu

Paveiksliukai ateina iš senos ADP versijos. Ar reikėtų prašyti institucijų, kad iš naujo susikeltų savo organizacijos paveiksliukus?

Tai dar susiję ir su tuo, kad Organizacijos koordinatoriai, neturi galimybės keisti organizacijos duomenų ar paveiksliuko. Ar reikėtų tokios formos koordinatoriams? Dabar organizacijos duomenis gali keiti tik super administratorius.

**Comment by JuliusLADP** [comment]
institucijos koordinatorius turi turėti galimybę įkelti/keisiti organizacjos logotipą

**Comment by sirex** [comment]
> institucijos koordinatorius turi turėti galimybę įkelti/keisiti organizacjos logotipą

Tada reikia sukurti naują užduotį, kurioje nurodyti, kad reikia Organizacijos formos, prie kurios gali prieiti Organizacijos koordinatoriai ir forma leistų keist paveiksliuką ir tikriausiai kitus organizacijos duomenis?

**Comment by JuliusLADP** [comment]
Ar ne paprasčiau leisti prieiti prie šio lauko redagavimo Administravimo aplinkoje?

**Comment by sirex** [comment]
Administravimo aplinka yra skirta tik Portalo vyriausiesiems administratoriams. Organizacijos formos užduotis koordinatoriams jau sukurta:

- https://github.com/atviriduomenys/katalogas/issues/544
