### ISSUE TITLE
Laiko juosta pagal laiko filtrą

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#522]
https://test.data.gov.lt/datasets/stats/publication/?

Rodom tik vieną suminę kreivę.

**Comment by adp-atea** [comment]
Pakeičiau kaip facet date laukas yra paimamas ir parašiau pora testų, kad patikrinti kai neprisijungęs naudotojas atidaro duomenų rinkinių sąrašą, tačiau klaidos atkartoti nepavyko, dabartinėje versijoje projekto viskas veikia. Verta paminėti, kad ši klaida tikriausiai atsiranda tik tokiu atvėju jei nebūna rebuildintas indeksas.
