### ISSUE TITLE
Nereikia kartoti poreikio pavadinimo

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#526]
![Image](https://user-images.githubusercontent.com/297583/265989425-ddfd4b93-6625-48a4-be70-b150a25e1aca.png)

Tas pats atsikartoja ir kitose vietose, Rinkiniai, šaltiniai, poreikiai ir tikriausiai kitur.

**Comment by adp-atea** [comment]
Vis dar atsikartoja prie rinkinių, šaltinių
