### ISSUE TITLE
Paprastas naudotojas mato užduotis apie klaidas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#528]
https://test.data.gov.lt/users/14/tasks/

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/42

**Comment by adp-atea** [comment]
Kokiems naudotojams adresuoti klaidų užduotis?

**Comment by sirex** [comment]
Iš pradinės užduoties https://github.com/atviriduomenys/katalogas/issues/42:

> Užduotys rodomos tokia tvarka, pradedant nuo tvarkytojų ir įtraukiant vis daugiau akių:
>
> - Pirmiausiai užduotis rodoma **tik** duomenų rinkinio tvarkytojui.
> - Jei organizacija neturi duomenų rinkinio tvarkytojo, tada užduotis rodoma koordinatoriui.
> - Jei iki užduoties termino liko 24 valandos, užduotis rodoma koordinatoriui (oranžinė spalva).
> - Jei užduotis vėluoja, t.y. terminas jau baigėsi, užduotis rodoma valdymo srities organizacijai, t.y. aukštesnei organizacijai, pagal pavaldumo hierarchija ir vyriausiems koordinatoriams (super admin).

Jei trumpai, tai užduotis pirmiausiai rodoma rinkinio tvarkytojui (arba koordinatoriui, jei rinkinys neturi tvarkytojo), tada eskaluojama ir papildomai rodoma koordinatoriui, vėliau dar eskaluojama ir rodoma valdymo srities koordinatoriams/tvarkytojams.

Paprastas naudotojas, kuris nėra nei rinkinio tvarkytojas, nei organizacijos koordinatorius, neturi matyti užduočių apie rinkinio klaidas/komentarus/poreikius ir pan.

Taip pat, kiti koordinatoria/tvarkytojai neturi matyti ne savo organizacijos, ar ne savo tvarkomų rinkinių klaidų.

**Comment by sirex** [comment]
Po pataisymo vaizdelis geresnis, tačiau dabar poreikio autoriui registruojama užduotis, nors ji turėtu būti registruojama ne poreikio autoriui, o poreikiui priskirtų organizacijų koordinatoriams.

**Comment by adp-atea** [comment]
Poreikio autoriui vis dar rodomos užduodys apie sukurtą, pakomentuotą poreikį (poreikis: https://test.data.gov.lt/requests/14338/)
Iš autoriaus užduočių lango: 

![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/ac75031c-3ec4-475f-8795-4afb872d3141)

**Comment by sirex** [comment]
Vis dar matau įrašus, pažymėtus raudonai, kurių esu autorius:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/3b8896f4-3ca9-4ce3-9c51-32322fa791f2)
