### ISSUE TITLE
Teksto pritraukimas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#545]
Neprisijungęs vartotojas. Pagrindinis puslapis. Duomenų paieška. Duomenų rinkiniai -> Rodyti daugiau. Pasirinkus duomenų rinkinį, siūlyčiau kortelėje “Poreikiai” pateiktą įrašą pakelti aukščiau, kaip tai padaryta likusiose kortelėse (Projektai, Planai). https://test.data.gov.lt/datasets/1239/requests/  
 
Pritraukti teksta į viršų

![Image](https://user-images.githubusercontent.com/69783864/265692269-a795321d-cf94-4789-8642-7a572c12f181.png)

**Comment by sirex** [comment]
Jei Planas nebus rodomas rinkinio kontekste, tai kaip visuomenė bus informuota apie konkretaus duomenų rinkinio atvėrimo ar papildymo terminus?

**Comment by JuliusLADP** [comment]
**Kol kas žemiau aprašytą optimizavimą atidedam:** 

Prie atskiro rinkinio rodyti atskiros institucijos arba visų institucijų planus būtų perteklinis nesusijusios informacijos rodymas. Jeigu rodyti tik kažiurios institucijos plano eilutę - kaip ir būtų variantas, bet tokiu atveju, reikėtų iš karto ir pateikti tokią informaciją, kuri iš karto pateiktų apie planą ir apie poreikį, jeigu toks buvo.
