### ISSUE TITLE
Objektų istorijos valdymas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#59]
Šiuo metu daugelis objektų turi `created`, `modified`, `deleted` ir `deleted_on` žymes. Šios žymės teoriškai turėtu leisti atstatyti ištrintas versijas ir gal būt dalinai pakeistas. Tačiau tai ne visai veikia.

Todėl siūlymas pakeisti objektų istorijos valdymą naudojant [django-reversion](https://django-reversion.readthedocs.io/).

- [ ] Pridėti [RevisionMixin](https://django-reversion.readthedocs.io/en/stable/views.html#reversion-views-revisionmixin) prie Dataset, Request ir Project formų.
- [ ] Pridėti „Istorija“ tabą, prie Dataset, Request ir Project details puslapių. Matomas tik `user.is_staff`, `(dataset|request).organization == user.organization` ir autoriui. Šiame puslapyje turi būti rodomas keitimų sąrašas.

**Comment by adp-atea** [comment]
1. Kas tiksliai turėtų būti rodoma keitimų sąraše? Pavyzdžiui, jei buvo sukurtas objektas, turėtų rodyti datą, naudotoją kuris sukūrė ir koementarą, kad sukurtas naujas? Jei pakeitė, tai vėlgi datą, naudotoją, kuris pakeitė ir pakeistus laukus? 
2. Ar reikia migracijos, kuri pagal created, deleted_on laukus sukurtų reversion įrašus jau egzistuojantiems duomenims?
3. Jei įrašas ištrintas, ar keitimų sąrašas vis tiek turėtų būti prieinama? Jei taip, kaip tai turėtų atrodyti?

**Comment by sirex** [comment]
> Kas tiksliai turėtų būti rodoma keitimų sąraše?

Tas pats, kas ir [administravimo aplinkoje](https://github.com/etianen/django-reversion/blob/master/reversion/templates/reversion/object_history.html).

- Data/laikas
- Naudotojas
- Veiksmas.

> Pavyzdžiui, jei buvo sukurtas objektas, turėtų rodyti datą, naudotoją kuris sukūrė ir koementarą, kad sukurtas naujas?

Taip.

> Jei pakeitė, tai vėlgi datą, naudotoją, kuris pakeitė ir pakeistus laukus?

Kol kas rodom tik komentarą, kokie laukai buvo pakeisti, bus galima padaryti kažkada vėliau. Ką reikia padaryti dabar, tai nustatyti komentarą, kad buvo padaryta, jei django-reversion to nedaro automatišai.

https://django-reversion.readthedocs.io/en/stable/api.html#creating-revisions

> Ar reikia migracijos, kuri pagal created, deleted_on laukus sukurtų reversion įrašus jau egzistuojantiems duomenims?

Taip migracijos reikėtų, tačiau tik tiems atvejams, kurie turi keitimų istoriją:

- `DatasetEvent`
- `RequestEvent`

> Jei įrašas ištrintas, ar keitimų sąrašas vis tiek turėtų būti prieinama? Jei taip, kaip tai turėtų atrodyti?

Įrašai neturėtu būti trinami, turėtu būti keičiamas tik įrašo statusas, kad jis yra ištrintas. Ir atitinkamai ištrinti objektai neturi niekur matytis, išskyrus duomenų tvarkytojams.
