### ISSUE TITLE
Vertimas į kitas kalbas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#61]
Duomenys į kitas kalbas turėtu būti verčiami naudojant [django-parler](https://github.com/django-parler/django-parler).

Šablonuose neturi būti rašoma jokia dinaminio vertimo logika, vertimai atliekami naudojant `django-parler`.

**Comment by adp-atea** [comment]
I am not able to make factories work with translations, if it is indeed possible a documentation or a way to do it would be helpful.

**Comment by sirex** [comment]
> I am not able to make factories work with translations, if it is indeed possible a documentation or a way to do it would be helpful.

What are the issues?

**Comment by adp-atea** [comment]
I could not figure out how to make it so only a DatasetFactory is needed to create both dataset and translations, so I made two factories for each table.
