### ISSUE TITLE
Nerodo koordinatoriui institucijai adresuoto poreikio

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#622]
Priskyrus poreikį organizacijai, poreikio formoje, neatsiranda poreikios „Mano poreikiai“ sąraše.

Prisijungus paprasto naudotojo (ne tvarkytojo ir ne koordinatoriaus) teisėmis, naujo poreikio formoje
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/3dc3713b-47e6-4a2c-99e3-5f78bac359f7)
-- https://test.data.gov.lt/requests/add/

Nurodau organizaciją.

Tada, prisijungiu, kaip tos organizacijos koordinatorius ir iš savo naudotojo meniu, pasirenku „Mano poreikia“ ir sąraše nematau, poreikio, kuris buvo adresuotas mano organizacijai:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/d7017db2-bdf5-4eed-861c-8d83e87069e1)
-- https://test.data.gov.lt/requests/submitted/?selected_facets=organization_exact:269

Jei einu į bendrą poreikių sąrašą, tada poreikis atsiranda:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/1bb404d8-8a83-4887-893f-fa99c78da5c3)
-- https://test.data.gov.lt/requests/submitted/

**Comment by adp-atea** [comment]
Nepamirskit rebuild_index.

Daliai dėl RequestObject įvesiu atskira task`a
