### ISSUE TITLE
Rinkinio priskyrimas ir kūrimas iš Poreikio puslapio

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#632]
Poreikio duomenų rinkinių puslapyje
![image](https://github.com/atviriduomenys/katalogas/assets/297583/b7c2a256-6d61-4d5b-961d-af2f24548f24)
-- https://test.data.gov.lt/requests/14344/datasets/

Pridėti du mygtukus:
- „Naujas duomenų rinkinys“
- „Priskirti esamą duomenų rinkinį“

Mygtukai rodomi tik jei naudotojas turi `user.organization`.

### Naujas duomenų rinkinys

Paspaudus mygtuką „Naujas duomenų rinkinys“ rodome naujo duomenų rinkinio formą

![image](https://github.com/atviriduomenys/katalogas/assets/297583/69316daf-3cc5-47e5-a55a-aab6a9209373)
-- https://test.data.gov.lt/datasets/269/add/

Tačiau užpildžius ir išsaugojus formą, turi grąžinti atgal į Poreikio rinkinių sąrašą.

### Priskirti esamą duomenų rinkinį

Paspaudus mygtuką „Priskirti esamą duomenų rinkinį“ rodome 

![image](https://github.com/atviriduomenys/katalogas/assets/297583/89ff0d0c-90f9-48ae-a59e-534359feca9a)

Paieškos laukelyje vedant raides, atliekama paieška sąraše, ieškant pagal kiekvieno žodžio pradžią.

Paspaudus ant „Pasirinimas 1“ atidaromas rinkinio puslapis naujame lange (target=_blank).

„Pasirinkimas 1“ turėtu būti Rinkinio pavadinimas.

Paspaudus mygtuką „Priskirti pažymėtus“, pažymėti duomenų rinkiniai priskiriami poreikiui.

Pasirinkimų sąraše rodoma ne daugiau kaip 20 duomenų rinkinių, surūšiuotų pagal pavadinimą.

Rodomi tik `user.organization` organizacijos rinkiniai.

**Comment by sirex** [comment]
Paspaudus „Naujas rinkinys“ pametama navigacijos juosta ir kontekstinis meniu. Tas pats ir su „Priskirti rinkinį“.

**Comment by JuliusLADP** [comment]
Bandant sukurti naują rinkinį "Užregistruotų asmenų informacija" poreikiui ir užpildžius naujo rinkinio registravimo formą, 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/cc4dcf73-7bb9-497f-8969-6d61ade779f2)



https://test.data.gov.lt/datasets/269/add/?next=/requests/11/datasets/


![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/b8f84d63-2749-4fa3-9d5b-4b130fd5977e)
**Paspaudus Išsaugoti gauname:**

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/6d980e8b-ea09-45fd-be1b-f3610bc6d280)
