### ISSUE TITLE
Atidarius naudotojo profilį pasikeičia meniu

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#665]
Prisijungus administratoriaus teisėmis ir atsidarius, kito naudotojo profilį, pavyzdžiui:

https://test.data.gov.lt/user/profile/2000/

Pasikeičia naudotojo meniu į to naudotojo, kurio profilis yra atidarytas.

Taip neturėtu, būti, reikia išsiaiškinti, kodėl taip atsitinka ir pataisyti.

Tik administratorius gali matyti kitų naudotojų profilius. Paprasti naudotojai, gali matyti, tik savo profilius, kitų profilių negali matyti.

**Comment by adp-atea** [comment]
Sitoj formoj buvo imama tokia pat reiksme is context_data, kaip ir request`e, tai sitos formos view pridejau logged_in_user parametra, ir sukuriau nauja tag`a
