### ISSUE TITLE
Neveikia paieška ir filtrai kartu

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#679]
Įvedus paieškos raktinį žodį:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/84ca712d-6bfd-4c23-b8a2-ef9b2ceed21b)
-- https://data.gov.lt/datasets/?q=covid

Ir paspaudus bet kurį filtrą, pavyzdžiui Rinkinio būsena: Atverti duomenys, dingsta paieška pagal raktinį žodį ir filtruojama tik pagal pasirinktą rinkinio būseną:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/11e7adee-b931-4aae-823d-2708a09aad4a)
-- https://data.gov.lt/datasets/?selected_facets=status_exact%3AHAS_DATA

Tada dar kartą įvedus paiešką pagal raktinį žodį, filtras išlaikomas, kas yra gerai, bet nors ir esu pasirinkęs, kad rodytų tik Atvertus duomenis, sąraše matau ir neatvertus:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/8e7e8463-f2ff-4765-ba64-2d26a03da412)
-- https://data.gov.lt/datasets/?q=covid&selected_facets=status_exact%3AHAS_DATA

**Comment by JuliusLADP** [comment]
Su klaidos taisymu susjusio funkcionalumo užduoti perkelta į atskirą užduotį Įgyvendinti korektišką Duomenų rinkiniai filtro veikimą
[#109](https://github.com/atviriduomenys/katalogas/issues/1069)

**Comment by ATEAanalyst** [comment]
Pridedamas šios klaidos taisymo aprašymas, prašome patvirtinti. Papildyta dar viena su sąrašu atsitiktinai rasta klaida. 

[Aprašymas_#679.docx](https://github.com/atviriduomenys/katalogas/files/15483742/Aprasymas_.679.docx)

**Comment by ATEAanalyst** [comment]
Darbus (programavimą, analizę, testavimą ir diegimus) vertiname 16h.

**Comment by JuliusLADP** [comment]
Patvirtinu 16 val.
