### ISSUE TITLE
Dubliuojasi žymės filtre

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#680]
![image](https://github.com/atviriduomenys/katalogas/assets/297583/bf9fc2f3-8731-49a8-ab8f-d50d274d09ad)
-- https://data.gov.lt/datasets/?q=covid&selected_facets=status_exact%3AHAS_DATA

Duomenų bazėje matau tokius įrašus:

| id | name | slug |
| --- | --- | --- |
| 350 | COVID-19 | covid-19 |
| 2793 | COVID-19 | covid-19_1 |

Galbūt problema buvo migracijoje?

Reikia padaryti naują duomenų migraciją, kur žymės būtų palyginamos pagal `name` ir panaikinami dublikatai, paliekant tą, kurio `slug` sutampa su `slugify(name)`.

Lyginant pagal `name` reikia daryti case insensitive palyginimą, tai reiškia, kas `COVID`, `Covi` ir `covid` yra vienas ir tas pats.

Šalinant besidubliuojančias žymes, vietoj šalinamo dublikato, reikia priskirti paliekamą žymę. Pavyzdžiui pirmiausiai vietoj 2793, prie rinkinių priskiriama 350, jei dar nebuvo priskirtas ir tada 2793 pašalinamas nuo visų rinkinių ir galiausiai pašalinama ir pati 2793 žymė.

**Comment by adp-atea** [comment]
Pridėtas scriptas, kuris sutvarko tag'ų dublius, nes su migracija to padaryti nepavyko.

**Comment by sirex** [comment]
Įdomu dėl kokių priežasčių nepavyko to padaryti migracijoje?

Testuojant, reikėtu patikrinti ar yra galimybė suvesti besidubliuojančias žymes, nes pirmiausiai, dublikatų neturėtu praleisti įvedimo metu.

**Comment by sirex** [comment]
Paleidus skriptą, gaunu tuščias žymes:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/7e51df98-c851-4cdf-b0bf-dd72bf444dd8)

**Comment by adp-atea** [comment]
O prieš tai duomenų bazėje ar nebuvo netvarkingų žymių? adp-dev yra vienas įrašas, kuris neturi name, o jo slug yra "_".


![Image](https://github.com/atviriduomenys/katalogas/assets/107176624/70c47699-9aa0-4fe9-937d-0cfdeae0dd41)

Nulinio ilgio "name" reikšmės pašalinamos.

**Comment by sirex** [comment]
Patikrinau dabar lyg ir veikia, bet reikės dar atidžiau patikrinti ar viskas gerai. Pasidedu šitą užduotį kol kas į Review.
