### ISSUE TITLE
Nenurodyta brandos lygis ir atnaujinimo periodiškumas

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#695]
Anstesnėje versijoje buvo nurodytas duomenų atnaujinimo periodiškumas, naujoje - nėra įrašo apie atnaujinimo periodiškumą.
https://data.gov.lt/datasets/1202/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/cce9931a-83e7-447f-b361-42aaa192e4a4)

**Comment by adp-atea** [comment]
Sutaisyta su #709
