### ISSUE TITLE
Nenuasmeninti komentatoriai 

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#696]
Nenuasmeninti duomenų rinkinius komentuojantys asmenys. 

https://data.gov.lt/datasets/1202/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/a5318a2b-f631-467e-891d-4dd33a3f14e5)

Kai kurie komentarai selektyviai nuasmeninti.
https://data.gov.lt/datasets/673/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/69f8b2ed-1ec3-4a71-9824-1feea2ac0fb5)

Pridedamas paaiškinimas:
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f301329c-35fc-4f91-b47b-6834469fcb90)

**Comment by Grigorjeva11** [comment]
Visus vartotojo komentarus nuasmeninti. Rašyti "Sistemos naudotojas" vietoje vardo, pavardės.
Komentaro autorių turi matyti tik pats autorius, organizacijos koordinatoriai ir tvarkytojai (jeigu priskirta organizacija), vyr. koordinatorius. 
Tokius reikalavimus atlikti ir komentaro laukams visur (prie duomenų rinkinių, poreikių, panaudojimoatvejųir kt.).

**Comment by adp-atea** [comment]
Ištestuota. Prisegama ataskaita.
[Klaidu-patikra-1217.pdf](https://github.com/user-attachments/files/18161857/Klaidu-patikra-1217.pdf)
