### ISSUE TITLE
Klaida su poreikiu 14306

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#697]

**Comment by aurjas** [comment]
VLK pranešė apie klaidą su poreikiu 14306:

Portalo klaida:
Prie poreikių paspaudus Organizacijos -> Server error (500)
https://data.gov.lt/requests/14306/orgs/



![Image](https://github.com/atviriduomenys/katalogas/assets/101550789/69b15ee7-488b-44dd-82f4-d08a5769fef8)

Server Error (500)

**Comment by sirex** [comment]
Dubliuoja https://github.com/atviriduomenys/katalogas/issues/684.
