### ISSUE TITLE
Klaida importuojant ADSA ant viršaus

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#707]
Jei įkeli aprašą, kurio dataset reikšmė sutampa su anksčiau įkelti aprašo, tada gaunu klaidą, kad toks aprašas jau egzistuoja.
Neatmeta rinkinio, kurio aprašas importuojamas.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f59d0021-7bc5-40a4-b988-5f961b6bf2ba)

**Comment by sirex** [comment]
Čia svarbu, kad importuojat struktūros aprašą, senasis turi būti pakeistas nauju. Tarkime, jei per klaidą buvo importuotas ne tas aprašas ir po to ant viršaus importuojamas kitas geras aprašas, tada naujasis turi perrašyti senąjį.

Tačiau, jei importuojamas tas pats aprašas ant viršaus, tik jame atsirado tik vienas jaujas property, tada sutampančių laukų ar modelių neturi liesti, t.y. turi išlikti komentarai prie laukų.
