### ISSUE TITLE
Nerodo duomenų brandos lygio

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#709]
Pridėtas ADSA, kuriame nurodyti brandos lygiai, tačiau skiltyje "Informacija", lauke "Brandos lygis" nėra nurodytas brandos lygis.
Duomenų rinkinys pridėtas jau naujoje portalo versijoje.
https://data.gov.lt/datasets/2372/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f4f510c6-8f8f-4ca6-92bf-982f36c56dc9)

**Comment by JuliusLADP** [comment]
https://github.com/atviriduomenys/katalogas/issues/695
