### ISSUE TITLE
Keičiant puslapio kalbą (iš LT į EN ir atvirkščiai) numeta į pagrindinį puslapį

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#710]
https://data.gov.lt/datasets/1239/ pasirinkta kalba EN.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/96a95989-04e9-4a7e-92d7-18ec20f59bc3)

Pakeičiant kalbą į LT, numeta į pagrindinį puslapį, o ne lieki šio rinkinio (https://data.gov.lt/datasets/1239/) kortelėje.

Ši situacija kartojasi visais atvejai (Rinkiniuose, Prašymuose atverti duomenis ir t.t.), kai bandoma pakeisti kalbą.

**Comment by sirex** [comment]
Dubliuoja https://github.com/atviriduomenys/katalogas/issues/390.
