### ISSUE TITLE
Organizacijų filtras pagal valdymo sritis

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#73]
Naikinamas organizacijų filtras pagal apskritis ir savivaldybes, vietoj to, padaromas filtras pagal ministerijų valdymo sritis.

https://data.gov.lt/organizations

Filtras gaunamas agreguojant. Filtruojama per GET query, taip pat, kaip veikia dabar.

**Comment by JuliusLADP** [comment]
Reikia atsižvelgti:

Savivaldybės turi dvejopą prasmę:
-	Savivaldybė kaip administruojama teritorija. Ši prasmė yra svarbi geografinės Duomenų aprėpties požiūriu tuo atveju, kai duomenų rinkinys susijęs ne su visos Lietuvos, o tik savivaldybės aprėptimi
-	Savivaldybė kaip Juridinis asmuo. Ši prasmė yra svarbi kitu aspektu – savivaldybės priklauso Savivaldybių grupei, kuri yra tokio paties lygmens kaip “priklausymas ministerijos sričiai”
