### ISSUE TITLE
Klaida skilties "Duomenys" filtre

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#739]
Saugykloje duomenys yra: https://get.data.gov.lt/datasets/gov/vmi/ja_mokesciai/Moketojas?mm_kodas._id=%22732f1021-d05c-419d-97bb-677d2a005d3d%22

Kataloge, jeigu skiltyje "Duomenys" filtruojama `mm_kodas` stulpelyje `=732f1021-d05c-419d-97bb-677d2a005d3d", atsakymas:
https://data.gov.lt/datasets/673/data/Moketojas/?mm_kodas=732f1021-d05c-419d-97bb-677d2a005d3d
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9ca35b29-0399-41d8-93ff-0c83c04be176)

Kataloge, jeigu skiltyje "Duomenys" filtruojama `mm_kodas` stulpelyje `contains 732f1021-d05c-419d-97bb-677d2a005d3d", atsakymas:
https://data.gov.lt/datasets/673/data/Moketojas/?mm_kodas.contains(%22732f1021-d05c-419d-97bb-677d2a005d3d%22)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/0859e1d3-d0da-45b2-90d7-cd4c7d088413)

Filtruojant nenuskaito ._id ir "".

Per nuorodą filtras veikia:
https://data.gov.lt/datasets/673/data/Moketojas/?mm_kodas._id=%22732f1021-d05c-419d-97bb-677d2a005d3d%22

**Comment by adp-atea** [comment]
1. Su = pataisyta.
2. Su "contains" reikėtų dar pataisyti ir spintos pusėje, nes neveikia panaudojus `mm_kodas._id`:
https://get.data.gov.lt/datasets/gov/vmi/ja_mokesciai/Moketojas?mm_kodas._id.contains(%22732f1021-d05c-419d-97bb-677d2a005d3d%22)

**Comment by sirex** [comment]
> Su "contains" reikėtų dar pataisyti ir spintos pusėje, nes neveikia panaudojus mm_kodas._id:
https://get.data.gov.lt/datasets/gov/vmi/ja_mokesciai/Moketojas?mm_kodas._id.contains(%22732f1021-d05c-419d-97bb-677d2a005d3d%22)

Užregistravau klaidą atskirai:

- https://github.com/atviriduomenys/spinta/issues/538

**Comment by IngaIVPK** [comment]
Nuskaito ._id ir "", 
Bet filtre įvedant `mm_kodas=732f1021' (tik šią įrašo dalį rodo `mm_kodas` stulpelyje) atsakymas vis tiek toks:

https://test.data.gov.lt/datasets/2390/data/Moketojas/?mm_kodas._id=%22732f1021%22


Jeigu filtre vedama pilnas įrašas (`mm_kodas._id="732f1021-d05c-419d-97bb-677d2a005d3d"`), tinkamai suranda
https://test.data.gov.lt/datasets/2390/data/Moketojas/?mm_kodas._id=%22732f1021-d05c-419d-97bb-677d2a005d3d%22

Ar tai susiję su "contain" rūšiavimo tvarkymu Saugykloje?

**Comment by adp-atea** [comment]
"732f1021" yra tik dalis UUID kodo, todėl `=` rezultato negrąžins, taip pat iš spintos pusės grąžinama klaida, kad tai nėra teisingai suformuotas UUID. Šiuo atveju reikėtų naudoti `contains`.
