### ISSUE TITLE
Klaida importuojant struktūrą pametami ref langelyje nurodyti matavimo vienetai

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#744]
Importuota struktūra, kurios `ref` buvo nurodyti matavimai vienetai jie pasimeta.

Importuota struktūra, nuoroda: https://github.com/atviriduomenys/manifest/blob/a1b58384a0a2ddc37d8de408bc99757b92bb7568/datasets/gov/vmi/mm_registras.csv
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/e8139ac2-6a5a-41f1-8810-8476c7369da0)

Importavus "nuskaityta" be `ref=D`
https://test.data.gov.lt/datasets/2385/models/MokesciuMoketojas/

**Comment by sirex** [comment]
@IngaIVPK gal gali patestuoti ar jau veikia? Testinėje aplinkoje.

**Comment by IngaIVPK** [comment]
@sirex patestavau, `ref` rodo matavimo vienetus:
https://test.data.gov.lt/datasets/2380/models/MokesciuMoketojas/
