### ISSUE TITLE
Registruojantis neprašo patvirtinti el. pašto adreso

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#771]
https://test.data.gov.lt/register/

Registruojantis, neprašo patvirtinti nurodyto el. pašto adreso, ko pasekoje pradėjo registruotis spam botai.

Užsiregistravusiam naudotojui, neturi leisti prisijungti, kol nėra patvirtintas el. pašto adresas:

https://docs.allauth.org/en/latest/account/views.html#email-verification

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/85

**Comment by sirex** [comment]
Dar vienas dalykas, naudojant django-allauth, reikėtu nustatyti

    ACCOUNT_PREVENT_ENUMERATION = True

Kad apsaugoti, no naudotojų išvardijimo ataktų.

**Comment by adp-atea** [comment]
Testuojant noreciau, kad pabandytum keturis variantus: (Pats pabandziau, nu bet vistiek, cia tokia kritine vieta)
1. Paimk jau egzistuojantį vartotoją ir pabandyk prisijungt, rezultate turetu prisijungt.
2. Susikurk naują vartotoją, turėtų išsisiųst laiška, bet nepatvirtink email`o. Pabandyk jungtis, rezultate turėtų neprisijungt.
3. Susikurk naują vartotoją, turėtų išsisiųst laiška, patvirtink email`a. Pabandyk jungtis, rezultate turėtų prisijungt.
4. Pabandyk reset password

**Comment by adp-atea** [comment]
Butu galima sita 
https://github.com/atviriduomenys/katalogas/issues/771#issuecomment-1816073176
su atskiru task`u?
