### ISSUE TITLE
Klaida komentaruose kai rinkinys įtrauktas į projektą

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#783]
https://data.gov.lt/datasets/1286/

```python
Traceback (most recent call last):
  File "vitrina/comments/models.py", line 112, in body_text
    f"{self.rel_content_object.get_title()} projektą."
AttributeError: 'NoneType' object has no attribute 'get_title'
```

https://github.com/atviriduomenys/katalogas/blob/4aced4588d728bedd3ece7f3da60379477b7c5ad/vitrina/comments/models.py#L109-L113

Panašu, kad jei rinkinys yra įtrauktas į projektą, tai atvaizduojant komentarus, įvyksta klaida.

Duomenų bazėje matau, kad `rel_conent_object` rodo į `Project(id=22)`, kurio duomenų bazėje nėra. Tai čia gali būti, kad problema susijusi su rašymu, kai projektas priskiriamas duomenų rinkiniui, gal būti klaidingai išsaugomas `Comment.rel_object_id`? Reikia tai patikrinti.

Duomenų bazėje randu apie 40 duomenų rinkinių, kuriuose rodoma į neegzistuojantį projektą. Panašu, kad čia yra duomenų rašymo klaida, kažkurioje vietoje, klaidingai priskiriamas projektas arba supainiotas content_type.

**Comment by adp-atea** [comment]
Su `PROJECT` tipu komentarai atsirado tik migracijos, kuri sukuria komentarus duomenų rinkiniams, metu.
`rel_content_type` ir `rel_object_id` priskirti teisingai pagal buvusius duomenis.

Pavyzdžiui čia viską gerai atidaro: https://test.data.gov.lt/datasets/1286/

Čia panašu, kad `data.gov.lt` puslapyje buvo pašalintas projektas - https://test.data.gov.lt/projects/22

Kol kas padariau, kad tokiu atveju nemestų klaidos ir atidarytų peržiūrą. 
Bet turbūt reikėtų pridėti migraciją, kuri visai pašalina tokius komentarus? @sirex
