### ISSUE TITLE
Filtras "Brandos lygis" rodo neteisingą įstaigų skaičių

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#802]
Pavyzdžiui:
https://data.gov.lt/orgs/83/datasets/?selected_facets=organization_exact:83
Atvertas 21 duomenų rinkinys, kiekvienam iš jų yra importuota struktūra, todėl filtre turėtų rodyti brandos lygis apie visas 21.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/57d3097c-2396-45e5-9c9e-1c403ac167b3)

Atsidarius kiekvieno iš 21 duomenų rinkinio kortelę brandos lygis rodomas:
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/175c335b-0f74-4dd6-b70a-e3c80095bcf9)

**Comment by adp-atea** [comment]
Klaida sutaisyta, tačiau atnaujinant live projekto versiją reikia įsitikinti, kad būtų panaudotas rebuild_index.
