### ISSUE TITLE
Klaida 500 importuojant struktūrą

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#803]
Importuojant struktūrą išmetė klaidą, kad per daug ženklų.
Pataisiau struktūros aprašymą.
Keliant išmeta Server error 500
https://data.gov.lt/datasets/1760/structure/import/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c6f6199e-31d6-49ef-aeb7-9e7506897f15)

**Comment by adp-atea** [comment]
Šitas turėtų susitvarkyt su šituo
https://github.com/atviriduomenys/katalogas/issues/685

Bet ten pakeičiau pačio modelio lauko tipą, tai nenoriu mergint, kol Mantas nepareviewins.

**Comment by Faustasm** [comment]
vitrina-vitrina-1  | Internal Server Error: /datasets/<>/structure/import/
vitrina-vitrina-1  | Traceback (most recent call last):
python<>/site-packages/vitrina/datasets/structure.py", line 373, in last
vitrina-vitrina-1  |     return self.stack[-1]
vitrina-vitrina-1  |            ~~~~~~~~~~^^^^
vitrina-vitrina-1  | IndexError: list index out of range

**Comment by sirex** [comment]
@IngaIVPK gal gali pateikti nuorodą į struktūros aprašą, kurį buvo bandoma importuoti?

**Comment by IngaIVPK** [comment]
@sirex https://github.com/atviriduomenys/manifest/pull/2582/files

**Comment by adp-atea** [comment]
Nevisai gera failo struktūra. Tokią stuktūrą suimportuoti eina.
1. Paskutinio kablelio, headeryje
2. Ir nuėmiau tusčias eilutes.


[ismoketa_advokatams.csv](https://github.com/atviriduomenys/katalogas/files/13543002/ismoketa_advokatams.csv)

**Comment by IngaIVPK** [comment]
Ačiū, įsikėlė.

Kaip ir buvo rašytą, buvo gauta klaida (kurią Jūs irgi pažymėjote i.), tačiau net pataisyto varianto neleido įkelti. 
Per klaidą buvau pridėjusi nepataisytą ADSA.
