### ISSUE TITLE
Nėra galimybės pridėti Mokymo medžiagos naują informaciją (puslapio turinį)

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#805]
Nėra galimybės pridėti, naujo puslapio turinį https://data.gov.lt/admin/cms/page/add/?parent_node=12
, o taip pat redaguoti jau esamą net per administravimo aplinką. Čia nerodo ir turinio nors jis yra publikuojamas

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/fe8dc279-9142-4cae-a309-c0cae4f2708a)

**Comment by adp-atea** [comment]
Aministravimo dalyje dabar galima pridėti/redaguoti:
- Mokymosi medžiagą
- Dažnai užduodamus klausimus
- Kitus portalus
- Ataskaitas

Tiems puslapiams, kuriuose pateikiami ne duomenų bazėje saugomi objektai, kaip šiais atvejais, bet tiesiog tekstas, yra sukurta kita užduotis #432
