### ISSUE TITLE
Organizacijų sąraše neranda, o įvedant rodo kad yra

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#814]
Yra atėjęs iš išorės raštas dėl koordinatoriaus registravimo.

Bandant išspręsti neveikiančią koordinatoriaus registravimo problemą ir registruoti rankiniu būdu per administravimo aplinką, to taip pat neįmanoma  padaryti, nes:

- Registruojant organizaciją duomenų teikėju (nes sąraše jos neranda), išmeta klaidą kad tokia organizacija jau yra

https://data.gov.lt/admin/vitrina_orgs/organization/add/

Užpildžius tokią informaciją, išmeta 500 klaidą

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/8d974b73-175b-41da-8cab-980b83817203)

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/3ab92058-6409-4552-a054-c12f68c7b38b)

- o registruojant per **user** administravimo aplinką, nėra įmanoma surasti pateiktame sąraše tokios organizacijos, nes nėra organizacijų paieškos

**Comment by Faustasm** [comment]
Erroras: django.db.utils.IntegrityError: duplicate key value violates unique constraint "organization_path_9c723b25_uniq"
DETAIL:  Key (path)=(000B) already exists.
@sirex, @JuliusLADP Klaida yra dėl treebeard modulio. Importuojant organizacijas prieš tai leidžiamas fix_tree, kad šito error nebūtų https://github.com/atviriduomenys/katalogas/blob/devel/scripts/import_organizations.py#L27. Kuriant organizacijas tikriausiai reikia kažko panašau.
Klausimas, kada ir kodėl tas metodas leidžiamas ir ar nereiktų taip pat prieš kuriant organizaciją jį naudoti?

**Comment by sirex** [comment]
`fix_tree` nereikėtu leisti, reikėtu žiūrėti, kas konkrečiai yra blogai su duomenimis, greičiausiai kažkokios migracijos arba organizacijos forma, sugadina medį, nekorektiškai išsaugant duomenis.

Tai reikia išsiaiškinti tikrąją problemos esmę.
