### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#818]
Keliant struktūrą, parsiųstą iš Githubo, meta klaidą.
https://data.gov.lt/datasets/1620/structure/import/
[darbo_uzmokestis.csv](https://github.com/atviriduomenys/katalogas/files/13526250/darbo_uzmokestis.csv)

Parefrešinus puslapį, sukrito dalis struktūros: `model=DarboUzmokestis2014` - visas, `model=DarboUzmokestis2018` - vienas laukas.
Skiltis "Duomenys" abiejų modelių atveju - užsildė sėkmingai. 
https://data.gov.lt/datasets/1620/data/DarboUzmokestis2018/

**Comment by IngaIVPK** [comment]
Testinėje aplinkoje šis struktūros aprašas susiimportavo visas sėkmingai.
@adp-atea kodėl nepavyko suimportuoti viso gamybinėje aplinkoje?

**Comment by adp-atea** [comment]
`"update(property: ""type: """")"` vietos parsinimas sukeldavo klaidą.
