### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#828]
Paleidžiant lauko `koordinate` duomenų atvaizdavimą, išmeta "502 Bad gateway"
https://data.gov.lt/datasets/1763/models/IvykiuKoordinates/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/fafd5cca-f565-408f-a6b1-f19a7daedd96)

### Susiję

- https://github.com/atviriduomenys/spinta/issues/770

**Comment by adp-atea** [comment]
Problema, kad iš spintos pusės labai ilgai laukiama duomenų:
https://get.data.gov.lt/datasets/gov/bpc/pagalbos_skambuciai/IvykiuKoordinates/:format/json?summary(%27koordinate%27)

Duomenų nesulaukia, todėl meta klaidą.

Kol kas pataisiau, kad katalogo pusėje aptikus tokią klaidą, atidarytų properčio peržiūros puslapį be žemėlapio, bet šiaip reikėtų arba spintos pusėje greitinti skaičiavimus, arba pailginti serverio timeout laiką, kad leistų ilgiau suktis prieš išmetant klaidą.

**Comment by JuliusLADP** [comment]
Įvertintus, kad galima, neiššaukianti kitų trikdžių prailginti timout laiką taip padaryti, o jeigu tai nepadės - optimizuoti skaičiavimus.

**Comment by JuliusLADP** [comment]
Arba kitu pasirinktu būdu spręsti veikimo pagreitinimą
