### ISSUE TITLE
Klaida 500 registruojant naują duomenų rinkinį

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#839]
Lietuvos hidrometeorologijos tarnyba informavo, kad registruojant naują duomenų rinkinį gavo klaidą 500.

"Laba diena,

niekaip nepavyksta sukurti naujo duomenų rinkinio. Paspaudus „Sukurti“ grąžinamas puslapis su 500 klaida.

Kaip būtų galima sukurti naują duomenų rinkinį?"

![Image](https://github.com/atviriduomenys/katalogas/assets/85924252/493d687b-ee10-4126-b341-40a5685b8b89)

**Comment by adp-atea** [comment]
Pataisyta klaida, galimai kilusi dėl slug generavimo. Jei sukurti vis tiek neleidžia, reikėtų pamatyti su kokiais konkrečiais duomenimis bandoma kurti duomenų rinkinį arba gauti tikslų klaidos pranešimą, kad būtų galima atkartoti situaciją.
