### ISSUE TITLE
Ištrynus duomenų šaltinį nepasikeičia rinkinio būsena

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#840]
https://test.data.gov.lt/datasets/2418/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/20a1d3bc-5822-422e-9fc4-3e457f5b2d75)
Ištrinus duomenų šaltinį būsena nepasikeičia, rodo, kad duomenys atverti, nors nėra duomenų šaltinio. Būsena turėtų būti "Inventorintas".
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/93effdb8-30c4-415b-a760-6814597ae00a)

Taip pat jeigu duomenų šaltinis (Saugykloje publikuojamas) sukuriamas, kai importuojama struktūra ir pašalinus duomenų šaltinį, būseną rodo "Atvertas".

Taa pati situacija ir kai pridedi duomenų šaltinį kaip failą ir vėliau jį pašalini.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/d01a0b4d-751a-4df7-8f98-6ccdbfb7c7cf)

**Comment by adp-atea** [comment]
Pagal tą pačią logiką pataisyta ir statuso pakeitimas, kai duomenų rinkinys pašalinimas iš paskutinio plano.
