### ISSUE TITLE
Klaida nukreipiant į duomenis Saugykloje

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#863]
ADP duomenų rinkinio kortelėje spaudžiant Duomenų šaltiniai "Atidaryti", gaunu tokį atsakymą (2) - nenukreipia į Saugyklą. 
Skiltyje "Duomenys" (3) pačius duomenis, kurie ateina iš Saugyklos rodo. 
Ta pati situacija naudoant Chrome ir Edge naršyklę.
Ta pati situacija ir prie kitų rinkinių.

https://data.gov.lt/datasets/1923/
(1)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/430e8c7f-95d2-4325-ad00-a65e502db097)

(2)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/914509f4-eab2-4bb3-9705-7f23032de910)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/28f2e31a-ad95-4855-8254-46fc26331cf0)

(3)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/7c0b7174-ea22-4c9a-af10-a88111d23996)

Atsisiuntimo nuorodą rodo korektišką:
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/83f2f077-3a31-412f-8a0c-5414b166ebc7)

**Comment by sirex** [comment]
Dubliuoja https://github.com/atviriduomenys/katalogas/issues/808
