### ISSUE TITLE
Pašalinti modelį ir 500 klaida

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#868]
Gal būtų galima pašalinti abu modelius šitam rinkiniui, per klaida ne tas buvo pridėtas, o paskui keliant tinkamą struktūros aprašą išmetė 500 klaidą.

Rinkinys: https://data.gov.lt/datasets/1415/models/

**Comment by adp-atea** [comment]
@aurjas jei galit, pridėkit importuojamos struktūros failą, su kuriuo gaunama 500 klaida.

**Comment by aurjas** [comment]
Pridedu struktūros aprašus:

Pirmas ir klaidingai įkeltas:

[broadcasting.csv](https://github.com/atviriduomenys/katalogas/files/13671782/broadcasting.csv)

Antras, kuris yra teisingas, bet kurį keliant išmetė 500 klaidą. Perkrovus puslapį, rodė, kad sukūrė modelį, bet ne visi laukai importavosi.


[amateurs.csv](https://github.com/atviriduomenys/katalogas/files/13671794/amateurs.csv)

**Comment by adp-atea** [comment]
Problema buvo dėl `enum`, kuris turi `null` reikšmę. Klaida pataisyta ir dabar kai įsiimportuos be klaidų, bus pašalintas ir senas modelis, kurio nėra naujame struktūros faile.
