### ISSUE TITLE
Naujo duomenų teikėjo registracija

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#87]
- [x] Tituliniame lape paspaudus mygtuką „Užpildyti naujo duomenų teikėjo formą“ turėtu atsirasti tarpinis puslapis (dabar iš karto nukreipia į el. valdžios vartus).
- [x] Tarpiniame puslapyje turėtu būti pateikta informacija (žiūrėti žemiau) apie duomenų teikėjo registravimą.
- [ ] Paspaudus mygtuką [Tęsti], nukreipiama į Elekroninius valdžios vartus.
- [ ] Grįžus iš Elektroninių valdžios vartų prašoma užpildyti tokius duomenų laukus:
  - [ ] Organizacijos registracijos numeris (read only), informacija gaunam iš El. vartų.
    - [x] Patikrinam ar tokia organizacija jau nėra registruota.
  - [ ] Organizacijos pavadinimas (read only), informacija gaunam iš El. vartų.
  - [ ] Organizacijos [kodinis pavadinimas](https://atviriduomenys.readthedocs.io/dsa/kodiniai-pavadinimai.html#vardu-erdviu)
    - [x] Pateikti informaciją žemiau lauko: „Organizacijos kodinis pavadinimas yra unikalus organizacijos pavadinimas, mažosiomis raidėmis, naudojant til lotyniškas raides, tai yr kažkas panašaus į interneto adresus, dažniausiai naudojamas organizacijos trumpinys pavyzdžiui `ivpk`“.
    - [x] Patikrinti ar toks trumpinys nėra naudojamas.
    - [x] Patikrinti ar pavadinimas mažosiomis raidėmis ir jame yra tik lotyniškos raidės (a-z).
    - [ ] Automatiškai pasiūlyti kodinį pavadinimą iš El. vartų gauto organizacijos pavadinimo padarant trumpinį imant kiekvieno žodžio pirmą raidę.
  - [ ] Koordinatoriaus el. paštas (užpildyta iš El. vartų).
    - Patikrinama ar naudotojas toliu el. pašto adresu jau nėra užsiregistruoti, jei yra, paprašyti prisijungti.
  - [ ] Koordinatoriaus telefono numeris (užpildyta iš El. vartų).
  - [x] Koordinatoriaus slaptažodis
  - [x] Koordinatoriaus slaptažodis (pakartoti)
  - [x] Raštas (filo įkėlimas).
    - [x] Patikrinam ar tai yra ADOC failas.
      - [ ] Išzipuojam  ADOC ir patikrinam vieną ar kelis metaduomenis esančius archyve.
      - [ ] Pilnos, kriptografinės verifikacijos daryti nereikia.
- Sėkmingia užpildžius ir pateikus formos duomenis:
  - [ ] Nukreipiama į #88.
  - [ ] Sukuriama užduotis, kuri priskiriama `supervisor` grupei #90.
  - [ ] Sukuriamas naudotojas koortinatoriui ir priskiriamas grupei `coordinator`.

URL: `/orgs/register/`

- [ ] Peradresuoti iš `/partner/register/`.
- [x] Šis atvejis turėtu veikti tik jei naudotojas neprisijungęs, jei prisijungęs, rodyti pranešimą, kad naudotojas turi atsijungti.

### Informacija duomenų teikėjo registravimui

Duomenų teikėjais gali būti tiek valstybinio, tiek privataus sektoriaus atstovai.

Prieš registruojantis, jūsų organizacijos atstovas turėtu užpildyti [Raštą dėl koordinatoriaus paskyrimo](https://data.gov.lt/file/9f12acd4-d9ee-423d-85a1-667e52b67941). Šį raštą turėtu pasirašyti jūsų organizacijos, padalinio ar skyriaus vadovas. Elektroniniu būdu pasirašytas raštas ADOC formatu turi būti pateikiamas pildant registracijos formą.

### Priklauso nuo

- #84

**Comment by JuliusLADP** [comment]
Nevisai aiškus perėjimo nuo paprasto ADP lankytojo prie atstovaujančio institiuciją naudotojo profilių?
Nevisai esu tikras ar galime atsisakyti analoginio pasirašyto dokumento, patvirtinančio koordinatoriaus paskyrimą, kopijos ir DVS pdf nuorašo? 
Ne viešojo sektoriaus darbuotojams nebus su organizacija sujungtų paskyrų VIISP. Todėl po autentifikacijos, nebus į ADP grąžinami susieti su organizacija naudotojo duomenys. Ar po autentifikacijos VIISP, būsimas koordinatorius, turės VISP susikurti savo "tarnybinę paskyrą"?
