### ISSUE TITLE
Suapvalinti brandos lygio rodomą reikšmę

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#883]
Visiems duomenų rinkiniams, kurie yra atverti ir publikuojami atvejais, kai brandos lygis yra paskaičiuotas su dešimtainiu ženklu - rodyti suapvalintą sveiko skaičiaus reikšmę detalios rinkinio metaduomenų  peržiūros formoje [data.gov.lt](https://data.gov.lt/datasets/2683/) ir struktūros peržiūros formoje https://data.gov.lt/datasets/2683/models/Patikrinimas/
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/eaed2d4e-b369-49fa-b371-d68470d94265)

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/98c83114-d140-4c98-b9a4-c96cd27ce962)

**Comment by adp-atea** [comment]
Ištestuota. Prisegama ataskaita.
[Klaidu-patikra-1217.pdf](https://github.com/user-attachments/files/18161857/Klaidu-patikra-1217.pdf)
