### ISSUE TITLE
Organizacijos narių peržiūra

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#89]
Organizacijos peržiūra ir jos narių peržiūra pasiekiama iš organizacijos meniu, organizacijos meniu, panašus į GitHub repozitorijos meniu: https://github.com/atviriduomenys/katalogas/, kuri meniu rodoma Code | Issues | ...

- [x] Narių sąrašo lentelėje turėtu būti rodoma:
  - Vardas ir Pavardė kol kas iš `users:User` arba `orgs:Representative` vėliau iš `auth.User`.
    - Jei naudotojas dar neužsiregistravęs #91 , tada skliausteliuose rodoma "(laukiama)".
  - Rolė `orgs:Representative.role`.
- [x] Sąrašas turi būti rūšiuojamas pagal:
  - Role
  - Vardą ir Pavardę
- [x] Sąraše rodomi tik tai organizacijai priklausantys nariai.

URL: `/orgs/<orgs:Organization.kind>/<orgs:Organization.slug>/members/`

Model: `orgs:Representative`.

### Priklauso nuo

- #83 
- #91
- #85

**Comment by adp-atea** [comment]
As far as I see this task was done fully in #91, so I added the ordering requested by this task and created a pull request.
