### ISSUE TITLE
Užduočių sąrašas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#90]
Į užduočių sąrašą patenkama iš naudotojo kontekstinio meniu (puslapio viršuje dešinėje pusėje esančio iškrentančio meniu) „Užduotys“.

URL kelias: `/users/<auth:User>/tasks/`

- [ ] Užduočių sąrašo lentelėje rodoma:
  - Užduoties pavadinimas
  - Prieš kiek laiko užduotis buvo sukurta
- [ ] Užduočių sąrašas rūšiuojamas pagal:
  - Užduoties sukūrimo laiką pradedant naujausiomis
- [ ] Užduočių sąraše rodomos užduotys kurios yra priskirtos
  - Tiesiogiai naudotojui
  - Rolei, kuri suteikta naudotojui
    - `supervisor` - Vyr. koordinatorius
    - `coordinator` - organizacijos koordinatorius
    - `manager` - organizacijos tvarkytojas
  - Organizacijai, kuriai priklauso naudotojas
- [ ] Po prisijungimo naudotojas nukreipiamas į savo užduočių sąrašą. Tai galioja tik, jei useris yra kokios nors organizacijos narys.

**Comment by JuliusLADP** [comment]
Tai galioja tik, jei useris yra kokios nors organizacijos narys.

Tikslinu: tai galioja tik, jei useris yra kokio nors duomenų tiekėjo (organizacijos) narys.
