### ISSUE TITLE
Oranizacijos nario pridėjimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#91]
URL:

- `/orgs/<orgs:Organization.kind>/<orgs:Organization.slug>/members/add/` - naujo nario pridėjimas
- `/orgs/<orgs:Organization.kind>/<orgs:Organization.slug>/members/<orgs:Representative.id>/change/` - esamo nario keitimas

Pridėti naują `orgs:Representative`, formos laukai:

- el. pašto adresas
- rolė:
  - `coordinator` - Koordinatorius
  - `manager` - Tvarkytojas

Jei nurodytu el. pašto adresu naudotojas jau užsiregistravęs, jis pridedamas prie organizacijos.

Jei naudotojas tokiu el. pašto adresu dar nėra užsiregistravęs, jam išsiunčiamas laiškas, su prašymu užsiregistruoti. Po to, kai naudotojas sėkmingai užsiregistruojam jis automatiškai pridedamas prie organizacijos narių, su nurodyta role.

Sėkmingai išsaugojus formą, peradresuojama į `/orgs/<orgs:Organization.kind>/<orgs:Organization.slug>/members/`.

- [x] Šio metu naudotojo rolė yra pridėta prie `users:User`, tačiau ji turėtu būti prie `orgs:Representative`. Laikinai, `orgs.Representative` turėtu turėti dinaminį `@property`, kuris `role` paimtų iš `users:User`.
- [ ] Tarp organizacijos narių privalo būti bent vienas `coordinator` rolės narys. Negalima panaikinti `coordinator` rolės naudotojui, jei tai yra vienintelis `coordinator` rolės atstovas.
- [ ] `manager` rolės naudotojai negali pridėti ar keisti organizacijos narių, ši funkcija prieinama tik `coordinator` roei.
- [x] Sukurti naują lentelę, userio narystei organizacijoje.

**Comment by adp-atea** [comment]
Keli klausimai:
1. Kokie laukai turėtų būti redagavimo formoje? Ar neturėtų atsirasti vardo, pavardės, tel. numerio laukų?
2. Kaip suprantu rolės prie Representative dabar nesaugom. Tokiu atveju nėra būdo naudotojui užsiregistravus priskirti jam rolės, kuri buvo nurodyta nario formoje, nes ji prie nario neišsaugoma. Ar dabar taip ir paliekam?
3. Kas turėtų būti saugoma userio narystės organizacijoje lentelėje?

**Comment by sirex** [comment]
> 1. Kokie laukai turėtų būti redagavimo formoje? Ar neturėtų atsirasti vardo, pavardės, tel. numerio laukų?

Redaguojant rodyti tik rolę.

Visi kiti duomenys keičiami pačio naudotojo, per naudotojo profilį arba pateikiami naudotojo registracijos metu.
 
> 2. Kaip suprantu rolės prie Representative dabar nesaugom. Tokiu atveju nėra būdo naudotojui užsiregistravus priskirti jam rolės, kuri buvo nurodyta nario formoje, nes ji prie nario neišsaugoma. Ar dabar taip ir paliekam?

Reikia pridėti prie `Representative` naują  rolės lauką.

> 3. Kas turėtų būti saugoma userio narystės organizacijoje lentelėje?

Saugoma:

- `user` - tokio lauko nėra reikia pridėti `ForeignKey(User)`.
- `organization`
- `role`

Taip pat reikės padaryti migraciją, kuri susieja `User` su `Representative`, per `email`.

**Comment by adp-atea** [comment]
Reikėtų dar patikslinimo dėl 3 punkto. Mes sukuriam naują modelį, su nurodytais laikais ir kas paskui su juo daroma ir kur naudojama? Nes narių sąraše rodomi Representative modelio objektai, pridėjimas, redagavimas taip pas su jais. Tai ar reikėtų pakeisti į naujai sukurtą modelį? 

Ir kas tiksliai turėtų būti padaryta migracijoje, kuri susieja User su Representative per email?

**Comment by sirex** [comment]
>Mes sukuriam naują modelį

Naujas modelis nekuriamas, naudojamas esamas `Representative`.

> kas paskui su juo daroma ir kur naudojama?

Bus naudojama daugelyje vietų:

- teisių valdyme, organizacijos koordinatorius ir tvarkytojai turi teisė tvarkyti visus organizacijos rinkinius ir prašymus atverti duomenis priskirtus organizacijai.
- užduočių valdyme, organizacijos tvarkytojai gaus užduotis, kai kažkas klausia dėl duomenų arba prašo duomenis atverti.

Iš esmės organizacijos nariai, yra sistemoje registruoti naudotojai, kurie daro veiksmus priskirtus organizacijos valdymo sričiai.

> Nes narių sąraše rodomi Representative modelio objektai, pridėjimas, redagavimas taip pas su jais. Tai ar reikėtų pakeisti į naujai sukurtą modelį?

Naujo modelio nereikia, naudojam tą patį `Representative`.

> Ir kas tiksliai turėtų būti padaryta migracijoje, kuri susieja User su Representative per email?

`Representative` lentelėje nėra `user = ForeignKey(User)` lauko, migracijos metu, reikia pridėti tokį lauką į esamą `Representative` lentelę ir susieti esamus registruotus naudotojus `User` su `Representative.user`, tai galima daryti pagal el. pašto adresą, jei susiejimo padaryti nepavyksta, tada `Representative.user = None`.
