### ISSUE TITLE
robots.txt failas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#915]
Reikia sukurti `robots.txt` failą, su galimybe jo turinį keisti administravimo aplinkoje, gal būt panaudojant [django-extra-settings](https://pypi.org/project/django-extra-settings/).

Jei per django-extra-settings nėra pateiktas `robots.txt` turinys, tada reikia grąžinti tiesiog tuščią failą.

Dabar loguose gauname daug `Not Found: /robots.txt/` žinučių.

**Comment by aurjas** [comment]
Geraldai, gal gali prie progos pažiūrėti ar čia dar aktualu ir apie ką čia?

**Comment by kastger** [comment]
`robots.txt` egzistuoja https://data.gov.lt/robots.txt, tačiau jo turinio neina keisti per administracinę aplinką. Mano manymu turėti tokį funkcionaluma nėra būtina, kadangi `robots.txt` dažnai keistis neturėtų.
