### ISSUE TITLE
Vertimo į anglų kalbą problemos

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#927]
- Nėra galimybės pridėti anglišką tekstą "For data providers" puslapyje 
LT pasirinkime rodoma 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/441a307e-d613-47ce-a183-2be315123b53)

Pakeitus kalbą į EN - vertimo nėra ir nėra galimybių parengti ir publikuoti vertimą.
https://data.gov.lt/opening-tips/
- tokia pati situacija yra ir kituose More ir News puslapiuose. Nors visur turėtų būti angliško teksto parengimo ir redagavimo galimybė
- duomenų rinkinio peržiūros puslapyje neišverčiama https://data.gov.lt/datasets/2528/ Kategorijų ir Atnaujinimo periodiškumo reikšmės: 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/08d24a3e-069e-4626-91c0-9a2120ac4633)

nors per administravimo aplinką matau, kad vertimai yra padaryti:   

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/044f2c49-e4d1-48a5-8cf9-117bf6ebdb93)

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/ec5209ea-a52e-4be1-9a2f-974563d45bed)

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/268
- https://github.com/atviriduomenys/katalogas/issues/61

**Comment by adp-atea** [comment]
Pridėti vertimą galimybė yra:

Reikia prisijungti prie su administratoriaus teisėmis. Nueiti į norimą puslapį: https://test.data.gov.lt/opening-tips/, pakeisti kalbą į EN ir spausti "Redaguoti" mygtuką:
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/6489fae9-39fb-4b09-a31f-ac4ba78ac2e4)

Tada reikėtų du kartus paspausti ant teksto. Turėtų atidaryti redagavimo langą:
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/8f942207-786e-46ae-9b1f-a9e2f02f2ae3)

Jame pakeičiate ką norite, išsaugote ir spaudžiate "Publikuoti puslapio pakeitimus"
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/0a425ac0-d49b-4c5d-9240-15c8198c304f)

Gali būti, kad anglų kalbos puslapyje nėra jokio turinio, pvz. https://test.data.gov.lt/opening-tips/saugykla/

Tokiu atveju jį galima pridėti per meniu:
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/fefd8904-3a0f-4575-8c67-48a6c7a472f8)

Prie Side_Menu parinkite "Šoninis meniu" įskiepį:
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/e57c9bdc-100c-4d48-aff1-724b53221d47)

Prie Body pasirinkite "Tekstas" įskiepį:
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/e84925f7-054c-4d23-a835-a754a52785fe)

Ir vėl publikuokite puslapį.

----

Dėl naujienų, tai jos redaguojamos per admin dalį:
https://test.data.gov.lt/admin/djangocms_blog/post/

**Comment by sirex** [comment]
Dėl vertimų, reikia įtraukti šiuos modelius į django-parler ir padaryti migracijas, kad perkeltu senuosius vertimus į django-parler, kaip tai buvo padaryta su duomenų rinkiniais.

Modelių sąrašas, kuriuos reikia versit:

- Žymės - su žymėmis gali būti problemų, jei paprastai nepasidarys, matyt galima palikti be vertimų.
- Kategorijos
- Licencijos
- Atnaujinimo dažnumas (Frequency)
