### ISSUE TITLE
Duomenų šaltinių sąrašas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#93]
Įgyvendintas sąrašas rodomas duomenų rinkinio peržiūros puslapyje: `/datasets/<orgs:Organization.kind>/<orgs/Organization.slug>/<datasets:Dataset.slug>/` .

---

URL:

- `/datasets/<orgs:Organization.kind>/<orgs/Organization.slug>/<datasets:Dataset.slug>/` - sąrašas rodomas duomenų rinkinio peržiūros puslapyje.

Pavyzdžiai:

- https://data.gov.lt/dataset/atviru-duomenu-katalogo-api - Duomenų šaltiniai

- [ ] Atkartoti tokią pačią lentelę.
- [ ] Padaryti peradresavimą iš `/dataset/<datasets.Dataset.slug>` į `/datasets/<orgs:Organization.kind>/<orgs/Organization.slug>/<datasets:Dataset.slug>/`.

**Comment by adp-atea** [comment]
Reikėtų patikslinimo dėl duomenų šaltinių failų saugojimo būdo. Kaip išsaugoti, kad būtų galima dirbti su failais, nes Django turi FileField, kuris išsaugo kelią iki failo, tačiau dabar panašu, kad saugojamas failo vardas ir identifikatorius ir nelabai aišku kaip su tuo dirbti. Ar čia patys failai iš viso bus nesaugojami, o paimami iš spintos?

**Comment by sirex** [comment]
Patys failai bus saugomi failų sistemoje ir prieiname per [MEDIA_URL](https://docs.djangoproject.com/en/3.2/ref/settings/#media-url) kaip statiniai failai.

Dabar matau, kad failai saugomi taip:

```java
Path.of(dataPath, byId.get().getIdentifier())
```

Tai jei neklystu, failai yra saugomi viename kataloge `data`, kas mūsų atveju turėtu būti `MEDIA_ROOT / 'data'`, o patys failo pavadinimai yra distribucijos id?

Todėl reikia išlaikyti tą pačią struktūrą, dėl backwards compatibility. [FileField.upload_to](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.FileField.upload_to) leidžia gan lanksčiai apibrėžti kur ir kokiu pavadinimu saugomi failai.

Perkopijavus visus failus, su tokiais pavadinimais kokie yra  dabartiniame data.gov.lt, jei turėtu veiktų ir naujoje versijoje.
