### ISSUE TITLE
Klaida 500 registruojantis portale

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#941]
Nuoroda, kuri grąžino klaidą 500: https://data.gov.lt/register/account-confirm-email/%3FPMTM5:1rPiPo:mDdYrfgw54Smv5v-YB1WMp6Wzfoxt9FaxqJ_5I2Vbu0%5Cw+

Veiksmai, kuriuos atliekant gaunama klaida 500.
1. Vartotojas bando užsiregistruoti kaip viešas vartotojas, pildo šią formą: https://data.gov.lt/register/
2. Užildžius formą, registruotu el. paštu gaunama patvirtinimo žinutė.

![Image](https://github.com/atviriduomenys/katalogas/assets/85924252/f1c2493f-7aaf-4313-bab6-58b3f34da98f)

3. Paspaudus el. laiške nurodytą nuorodą, kuria turi būti patvirtinta registracija, gaunama klaida 500

**Comment by JuliusLADP** [comment]
Faustas turi įdėti logus

**Comment by Faustasm** [comment]
Dubliuojasi su https://github.com/atviriduomenys/katalogas/issues/933, logai  ten, ji jau pataisyta testinėje aplinkoje.
