### ISSUE TITLE
Portalo klaidos susijusios su raktų išdavimu ir leidimais

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#943]

**Comment by aurjas** [comment]
Atsiprašau, ne tam repozitoriume buvo priskirta užduotis, kuri buvo susijusi su saugykla, tai pataisysiu šią užduotį su pastebėtomis portalo klaidomis:

Keletas pastabų testuojant raktų išdavimą leidimams:

Testavau su duomenų rinkiniu https://test.data.gov.lt/datasets/916/, kurį priskyriau panaudojimo atvejui
https://test.data.gov.lt/projects/435.

1. Prie panaudojimo atvejo "Leidimai" skiltyje, kada buvo susietas su duomenų rinkiniu ir išduotas raktas paspaudus "Prašyti leidimų" https://test.data.gov.lt/projects/435/permissions/, turėtų rodyti rakto ID.
2. 
![image](https://github.com/atviriduomenys/katalogas/assets/101550789/bab4735f-5ad1-4e6e-b720-744e4f807acf)

3. "Leidimas" stulpelyje rodo žymę - juodas kvadratėlis. Šis statusas/žymė turėtų keistis kai leidimas yra suteiktas iš Organizacijos pusės. (paveiksliukas prie 1 užduoties dėl žymės/statuso)
4. Nuėjus į organizaciją (šiam panaduojimo atvejui buvo pasirinktas Miškų tarnybos duomenų rinkinys) ir pasirinkus "Raktai" skiltį rodo, kad prie išorinių raktų yra panaudojimo atvejis, tačiau paspaudus pavadinimą ir atidarius puslapį "Rakto peržiūra", rodo tuščią langą.
https://test.data.gov.lt/projects/435/permissions/868/

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/6732455e-3427-4777-8f4e-aea325ef4d0b)

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/db3b416e-8e3a-4290-ad8d-94aa254d150b)


Pavyzdys kaip turėtų būti https://test.data.gov.lt/projects/6/permissions/856/

**Comment by adp-atea** [comment]
O čia klaida, kad kataloge neišsaugoma kažkokia reikšmė?
Kaip atkartoti klaidą?

**Comment by aurjas** [comment]
Ši užduotis yra susijusi su 261 ir 262 užduotimis

https://github.com/atviriduomenys/katalogas/issues/261

https://github.com/atviriduomenys/katalogas/issues/262

Šios užduoties (943) tikslas buvo patikrinti ar su išduodamu leidimo raktu galima pasiekti access=public duomenis, kas nepavyko padaryti.

**Comment by aurjas** [comment]
Dar keletas pastebėtų klaidų testuojant access=public duomenis:
1. Prie panaudojimo atvejo "Leidimai" skiltyje, kada buvo susietas su duomenų rinkiniu ir išduotas raktas paspaudus "Prašyti leidimų", turėtų rodyti https://test.data.gov.lt/projects/435/permissions/ rakto ID.
2. "Leidimas" stulpelyje rodo žymę - juodas kvadratėlis. Šis statusas/žymė turėtų keistis kai leidimas yra suteiktas iš Organizacijos pusės.
3. Nuėjus į organizaciją (šiam panaduojimo atvejui buvo pasirinktas Miškų tarnybos duomenų rinkinys) ir pasirinkus "Raktai" skiltį rodo, kad prie išorinių raktų yra panaudojimo atvejis, tačiau nuspaudus pavadinimą ir atidarius puslapį "Rakto peržiūra", rodo tuščią langą.
https://test.data.gov.lt/projects/435/permissions/868/

**Comment by adp-atea** [comment]
1. Rakto id rodyti virš lentelės, kurioje nurodytas duomenų rinkinys ir būsena?
3. O organizaciją raktą patvirtino? Prašant sukurti raktą turėtų būti sukurta užduotis rakto patvirtinimui.
4. Gal tokių raktų, kurie dar nėra patvirtinti sąraše tiesiog nerodyti? Arba rakto peržiūroje, esant nepatvirtintam raktui rodyti pranešimą, kad raktas laukia patvirtinimo?

**Comment by aurjas** [comment]
1. Rakto id gali būti ir viršuje rinkinio bei būsenos.
2. Užduotis nebuvo sukurta, bet paspaudus "Prašyti leidimų" ir išdavus raktą ekrane, su tuo raktu galėjau jungtis prie organizacijos duomenų.
3. Manau pranešimas dėl patvirtinimo būtų kaip variantas, bent jau būtų aišku kas vyksta.

**Comment by aurjas** [comment]
Pakartojus žingsnius pirminiame užduoties aprašyme, t.y. sukūrus naują panaudojimo atvejį, priskyrus jį duomenų rinkiniui, paprašius leidimų ir nuėjus į organizacijos išorinius raktus, ten raktų peržiūroje išduodama žinutė "Šiuo metu raktas galiojančių leidimų neturi.". O kur yra galimybė leisti/išjungti leidimą, kaip tai yra čia https://test.data.gov.lt/projects/434/permissions/756/?

**Comment by aurjas** [comment]
Mygtukas Įjungti/Išjungti leidimą buvo pridėtas, bet savo funkcijos neatlieka.

Pridėti mygtukai:
https://test.data.gov.lt/orgs/269/apikeys/

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/44ee60ee-f673-47a2-b821-2b50c303baa1)

Iš paveiksliuko matosi, kad visiems išoriniams raktams leidimai yra įjungti, tačiau paspaudus ant pavadinimo prie AJ panaudojimo atvejis 2, atsidariusiame lange rašo "Šiuo metu raktas galiojančių leidimų neturi."

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/2a99c4e7-512e-4d99-9a4d-59b04ecd239f)

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/4926b07b-8b3b-4714-886b-787f77fd41e5)

Taip pat, nuėjus į panaudojimo atvejį ir pasirinkus skiltį "Leidimai", ten prie duomenų rinkinio yra juodas kvadračiukas, indikuojantis, kad leidimas nėra suteiktas.

![image](https://github.com/atviriduomenys/katalogas/assets/101550789/c5dfbc09-1854-4b47-b438-9f21ca1d711f)

**Comment by adp-atea** [comment]
#262 Aprašyme buvo nurodyta, kad leidimai kuriami tik duomenų rinkiniams, kurie turi access:public laukų.
Šiuo atveju kvadratas rodo, kad leidimų visai nėra, kitu atveju būtų rodoma kita ikona.

Pakeistas mygtuko išorinių raktų įjungimo/išjungimo funkcionalumas, tuo pačiu įjungiami ir išjungiami esamo rakto scopes.
