### ISSUE TITLE
Klaida siunčiant žinutę apie pateiktą poreikį: siunčiama ne organizacijos koordinatoriui, o organizacijos bendruoju el. paštu

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#984]
Viešas naudotojas organizacijai (Informacinės visuomenės plėtros komitetas) pateikė naują poreikį:  https://test.data.gov.lt/requests/14387/
El. žinutė apie pateiktą naują poreikį išsiųsta bendruoju IVPK el. paštu (1), nurodytu prie organizacijos kontaktų (2): 
(1)
https://test.data.gov.lt/admin/vitrina_messages/sentmail/236/change/?_changelist_filters=all%3D%26o%3D
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9925ecc0-7b0c-44f3-b164-42f07ae5c36f)

(2)
https://test.data.gov.lt/orgs/269/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/468b585a-84e5-4f2f-a252-e7e307473074)

Prašome pataisyti: 
1. Žinutė apie viešo naudoto pateiktą poreikį pirmiausia turi būti išsiųsta organizacijos koordinatoriui/-iams, kurie yra nurodyti skiltyje Organizacija -> Tvarkytojai. 

2. Taip pat pagal nutylėjimą kiekvienam organizacijos koordinatoriui/ tvarkytojui turi būti sukuriama prenumerata, kuri apima "Prašymai"/"Susijusių poreikių prenumerata".

Šiuo metu:
-  savarankiškai registruojantis naujam organizacijos koordinatoriui/ tvarkytojui per šią formą: https://data.gov.lt/login/?next=/ jo jokia organizacijos prenumerata pagal nutylėjimą  nesukuriama. Turi būti sukuriama pilna organizacijos prenumerata, apimanti standartinį paketą
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/ec8a95eb-5ea3-4fc5-8692-f7d60b1c83cb)

- Organizacijos koordinatoriui pridedant koordinatorių/ tvarkytoją per šią formą https://test.data.gov.lt/orgs/269/members/add/ ir pasirinkus "Prenumeruoti pranešimus", sukuriama prenumerata, kuri neapima "Prašymai" (3). Turi apimti ir "Prašymai".
(3)
https://test.data.gov.lt/user/profile/152/#sub
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c9ad47c8-9b04-49da-ad28-2e004baee5f6)

- Patikrinus iš ankstesnės ADP versijos perkeltų organizacijos koordinatorių/ tvarkytojų prenumeratą, matyti, kad visiems pagal nutylėjimą sukurta prenumerata, kuri neapima "Prašymai"="Susijusių poreikių prenumerata".
Pvz. https://data.gov.lt/admin/vitrina_messages/subscription/2994/change/?_changelist_filters=p%3D3
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/b47f9291-93b6-4fdb-992a-4b3e8929d7cd)
Šiems organizacijos koordinatoriams, tvarkytojams, pagal nutylėjimą turi būti automatizuotai uždėta prenumerata, kuri apima "Prašymai"="Susijusių poreikių prenumerata".

**Comment by IngaIVPK** [comment]
### Susiję

- https://github.com/atviriduomenys/katalogas/issues/39
- https://github.com/atviriduomenys/katalogas/issues/764

**Comment by IngaIVPK** [comment]
Testavimo rezultatas

2024-02-14 pateikta užduotis:
savarankiškai registruojantis naujam organizacijos koordinatoriui/ tvarkytojui per šią formą: https://data.gov.lt/login/?next=/ jo jokia organizacijos prenumerata pagal nutylėjimą nesukuriama. Turi būti sukuriama pilna organizacijos prenumerata, apimanti standartinį paketą
image
Rezultatas: negalime pratestuoti, nes susiję su 500 klaida
### Susiję

- https://github.com/atviriduomenys/katalogas/issues/981

2024-02-14 pateikta užduotis:
Patikrinus iš ankstesnės ADP versijos perkeltų organizacijos koordinatorių/ tvarkytojų prenumeratą, matyti, kad visiems pagal nutylėjimą sukurta prenumerata, kuri neapima "Prašymai"="Susijusių poreikių prenumerata".
Pvz. https://data.gov.lt/admin/vitrina_messages/subscription/2994/change/?_changelist_filters=p%3D3
image
Šiems organizacijos koordinatoriams, tvarkytojams, pagal nutylėjimą turi būti automatizuotai uždėta prenumerata, kuri apima "Prašymai"="Susijusių poreikių prenumerata".

Rezultatas: negalime pratestuoti, nes susiję su 500 klaida
### Susiję

- https://github.com/atviriduomenys/katalogas/issues/994

**Comment by IngaIVPK** [comment]
Prašome pataisyti pagal aprašytas situacijas:

### Situacijas Nr. 1.
Viešas naudotojas pateikia poreikį/ prašymą per šią formą https://test.data.gov.lt/requests/add/
**-jeigu organizacija nenurodyta, pranešimas išsiunčiamas vyr.koordinatoriui**
**-jeigu pateiktame poreikyje yra nurodyta organizacija, arba poreikis buvo perskirtas koordinatoriaus ar kitos institucijos koordinatoriaus, vykdomas pagal toliau aprašytą nuoseklų procesą:** 

1. El. žinutė pirmiausiai siunčiama TIK organizacijos koordinatoriui/ -ias ir bendruoju organizacijos el. paštu.
2. Jei organizacija nesureaguoja per 5 d.d. nuo poreikio/ prašymo pateikimo dienos, siunčiamas priminimas tam pačiam koordinatoriui.
3. Jei organizacija nesureaguoja per 10 d.d. nuo poreikio/ prašymo pateikimo dienos, siunčiamas laiškas ministerijos koordinatoriui.

Pavyzdžiui:
Pateiktas poreikis: https://test.data.gov.lt/requests/14395/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/24d3cd8b-2d58-4882-8d58-0c6d9c3f3dd5)
Poreikyje nurodyta organizacija: Informacinės visuomenės plėtros komitetas https://test.data.gov.lt/requests/14395/orgs/
El. paštu žinutė turėtų būti siunčiama:
- TIK IVPK koordinatoriams https://test.data.gov.lt/orgs/269/members/ 
IVPK koordinatoriai yra šie:
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c8757243-8182-42b0-989d-c1c72fdee160)
- ir bendruoju IVPK el. paštu https://test.data.gov.lt/orgs/269/#info
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/6ef8fa03-5425-497d-9645-42d54b494be4)
Jeigu organizacija (IVPK)/ koordinatorius per 5 d. d. nuo poreikio/ prašymo pateikimo dienos nepateikia atsakymo čia https://test.data.gov.lt/requests/14395/, siunčiamas priminimas tiems patiems IVPK koordinatoriams. T. y. jeigu nepakeista būsena į vieną iš galimų ir/ ar nėra organizacijos atsakymo, tokio kaip nurodyta pavyzdyje, reikia pakartotinai siųsti pranešimą tiems paties koordinatoriams.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/090ac263-235a-4b01-b2f0-f9dd42c3c238)

Jei organizacija (IVPK) nesureaguoja per 10 d. d. nuo poreikio pateikimo dienos, siunčiamas laiškas prie organizacijos kontaktų nurodytos ministerijos koordinatoriui, šiuo atveju - Lietuvos Respublikos ekonomikos ir inovacijų ministerijos koordinatoriui Viktorija.Zevakinaite@eimin.lt.
https://test.data.gov.lt/orgs/269/#info
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/caac43a4-416e-42db-970c-2a3df613a293)

https://test.data.gov.lt/orgs/178/members/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/e6a21b8f-c483-4bef-9124-ca6546b46932)


Pagal nutylėjimą kiekvienam organizacijos/ rinkinio koordinatoriui/ tvarkytojui registruojantis ar koordinatoriui pridedant tvarkytoją/ kt. koordinatorių visose skirtingose formose (1) turi būti automatiškai sukuriama organizacijos / rinkinio (2) prenumerata, kuri apima (3):
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/4fca9c14-72e1-4835-8f4f-e068573c9145)

(1)
Registravimosi formos/ tvarkytojo pridėjimo formos:
https://test.data.gov.lt/partner/register-info/ 
https://test.data.gov.lt/orgs/269/members/add/
https://test.data.gov.lt/datasets/2473/members/add/

(2)
Turi būti privalomai pažymėta "Prenumeruoti pranešinus" , kurios negalima nupaukščiuoti registracijos/ pridėjimo metu, tačiau turi likti galimybė atsisakyti šios "priverstinės" prenumeratos skiltyje Profilis - > Prenumerata (3))
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/402fe08d-3862-4d3d-bd2c-1f204a5c5d53)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/06761ae3-9131-4182-aeb2-29dbaabb0e1e)

(3)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/dc63efac-5b90-42c8-9261-5186da4108ba)

Jeigu organizacijos koordinatorius/ tvarkytojas **turi ir organizacijos prenumeratą, ir atskirų rinkinių prenumeratą**, tokiam naudotojui turi būti siunčiama viena žinutė pagal vieną objektą. 
Pavyzdžiui: 
IVPK koordinatorius Vardenė Pavardenė (ismolskaite@yahoo.com) turi ir organizacijos, ir rinkinio prenumeratą (3).
Jeigu viešas vartotojas rinkiniui "Naujas 02-12 pirmas" pateikia prašymą, Vardenei Pavardenei turi būti išsiunčiama viena el. žinutė apie organizacijos rinkiniui pateiktą prašymą, nepriklausomai, kad Vardenė Pavardenė turi 2 prenumeratas, kurių abi apima dalinai tas pačias prenumeratas. 
Valstybinės mokesčių inspekcijos atstovas Teisutis Simonaitis mus informavo, kad jis turi ir organizacijos ir atskirai kiekvieno rinkinio prenumeras. Kai viešas naudotojas parašo komentarą/ pateikia prašymą, jis gauna 2 tokio pačio turinio el. žinutes.

**Comment by IngaIVPK** [comment]
### Susiję

- https://github.com/atviriduomenys/katalogas/issues/39
- https://github.com/atviriduomenys/katalogas/issues/764

**Comment by IngaIVPK** [comment]
Prašome pataisyti pagal aprašytas situacijas:

### Situacijas Nr. 2.
Viešas naudotojas pateikia poreikį/ prašymą per šią formą prie rinkinio: https://test.data.gov.lt/datasets/2473/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/e27be7f2-52c8-4ffd-afa3-0fb6ccc5c4d8)
El. žinučių siuntimas, informuojant, kad **organizacijos rinkiniui** pateiktas poreikis, turėtų vykti pagal tokį nuoseklų procesą:

- pirmiausia el. žinutė siunčiama TIK nurodytiems rinkinio tvarkytojams/ koordinatoriams ir bendruoju organizacijos el. paštu;
- jeigu nurodytas rinkinio tvarkytojas/ -ai ir/ar koordinatorius per 5 d. d. nuo poreikio/ prašymo pateikimo dienos nesureaguoja, siunčiamas tas pats el. laiškas organizacijos koordinatoriui;
- Jei organizacija/ organizacijos koordinatorius nesureaguoja per 10 d.d. nuo poreikio/ prašymo pateikimo dienos, siunčiamas laiškas ministerijos koordinatoriui.

2. Pateiktas prašymas/ poreikis šiam organizacijos rinkiniu: https://test.data.gov.lt/datasets/2475/ 
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/11036cc8-28df-4ae1-9f49-34aded038610)

Rinkinys turi nurodytą rinkinio tvarkytoją ir koordinatorių (1), tuomet **pirmiausia** el. žinutė siunčiama TIK šio rinkinio nurodytiems tvarkytojams ir koordinatoriui (1) bei organizacijos bendruoju el. paštu (2).

(1) https://test.data.gov.lt/datasets/2475/members/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/21e65dc4-ed39-4d68-a888-a6cb4bfcc12e)

(2)  https://test.data.gov.lt/orgs/269/#info arba https://test.data.gov.lt/datasets/2475/#info
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/2378d2ff-94ca-4863-a0d6-3b1729ca3352)

- Nurodytas rinkinio tvarkytojas ar koordinatorius į pateiktą poreikį turi atsakyti šios poreikio kortelės skiltyje "Komentarai", pakeisdamas "Būseną" ir/ ar pateikdamas komentaro tekstą: https://test.data.gov.lt/requests/14397/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/4c0a28f5-d0c3-46f3-bec1-cb33cce9de86)

Rinkinio kortelėje veiksmas "Atsakyti" turi būti neleidžiamas (nerodyti), kai yra  "Pateiktas naujas prašymas"
https://test.data.gov.lt/datasets/2475/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/0db5a41b-0a66-4f2e-a8d0-e0bf30ae96ce)

-Jeigu nurodytas rinkinio tvarkytojas ar koordinatorius per 5 d. d. nuo poreikio/ prašymo pateikimo dienos nepateikia atsakymo čia https://test.data.gov.lt/requests/14397/, siunčiamas priminimas IVPK koordinatoriams. T. y. jeigu nepakeista būsena į vieną iš galimų ir/ ar nėra organizacijos atsakymo, tokio kaip nurodyta pavyzdyje, el. žinutę reikia siųsti IVPK koordinatoriams.
https://test.data.gov.lt/orgs/269/members/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9b017647-85dd-4794-a399-677a1ee745b6)

- Jei organizacijos (IVPK) koordinatoriai nesureaguoja per 10 d. d. nuo poreikio pateikimo dienos, siunčiamas laiškas prie organizacijos kontaktų nurodytos ministerijos koordinatoriui, šiuo atveju - Lietuvos Respublikos ekonomikos ir inovacijų ministerijos koordinatoriui [Viktorija.Zevakinaite@eimin.lt](mailto:Viktorija.Zevakinaite@eimin.lt).
https://test.data.gov.lt/orgs/269/#info
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c4cca299-ed0e-4cda-8fa1-4d3e6f99255b)

https://test.data.gov.lt/orgs/178/members/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/bd03e4ca-0c48-4a9d-a4ce-35d700dcc51f)

Dėl prenumeratų sukūrimo organizacijos/ rinkinio koordinatoriui galioja Situacija Nr. 1 aprašyti reikalavimai.

Per šią formą pateiktas prašymas rodomas dviejose vietose:
- prie rinkinio skiltyje "Komentarai" : https://test.data.gov.lt/datasets/2473/#info;
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f85c4bbc-8ea3-4081-bc70-8db9f025044b)
- bendrame "Poreikiai ir pasiūlymai" sąraše: https://test.data.gov.lt/requests/submitted/.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/e9a89e89-17cb-4583-9d73-d5ce38428b61)

**Comment by IngaIVPK** [comment]
Prašome pataisyti pagal aprašytas situacijas:

### Situacijas Nr. 3.
Viešas naudotojas pateikia prašymą/ poreikį ištaisyti pastebėtą klaidą duomenyse šioje formoje: https://test.data.gov.lt/datasets/2433/data/Parama/
https://test.data.gov.lt/datasets/2433/data/Parama/a7d10aa2-f39c-482c-88d3-030e01504496/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/8e8f4fb4-473b-4993-9c35-693d71476c62)

Šioje formoje registruotas prašymas ištaisyti klaidą duomenyse rodomas dviejose vietose:

- prie duomenų lauko, kuriame pastebėta klaidą skiltyje "Komentarai" : https://test.data.gov.lt/datasets/2433/data/Parama/a7d10aa2-f39c-482c-88d3-030e01504496/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c0329e87-33c8-45dd-8933-fd1466379437)

- bendrame "Poreikiai ir pasiūlymai" sąraše: https://test.data.gov.lt/requests/14400/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c9154220-7c12-4a55-81d6-c75fa6272a65)

El. žinučių siuntimas, informuojant, kad organizacijos rinkinio duomenims registruotas prašymas/ poreikis ištaisyti klaidą duomenyse, turėtų nuosekliai vykti pagal situacija Nr. 2 aprašytą procesą:
- pirmiausia el. žinutė siunčiama TIK nurodytiems rinkinio tvarkytojams/ koordinatoriams ir bendruoju organizacijos el. paštu;
- jeigu nurodytas rinkinio tvarkytojas/ -ai ir/ar koordinatorius per 5 d. d. nuo poreikio/ prašymo pateikimo dienos nesureaguoja, siunčiamas tas pats el. laiškas organizacijos koordinatoriui;
- Jei organizacija/ organizacijos koordinatorius nesureaguoja per 10 d.d. nuo poreikio/ prašymo pateikimo dienos, siunčiamas laiškas ministerijos koordinatoriui.

Pavyzdžiai galioja iš Situacijos Nr. 1 ir Situacijos Nr.2, todėl nekartojami.

### Susiję
- https://github.com/atviriduomenys/katalogas/issues/998

**Comment by JuliusLADP** [comment]
### Į čia pateiktą informaciją nekreipti dėmesio:
1. Jeigu rinkinio kortelėje skiltyje "Tvarkytojai" yra **nenurodyti** rinkinio koordinatoriai/ tvarkytojai, el. žinutės siuntimo procesas turėtų nuosekliai vykti pagal **situacija Nr. 1** aprašytą procesą. 

**Pastaba (reikalinga įvertinti ir nuspręsti)** dėl situacijos: kai prie duomenų rinkinio nėra priskirto duomenų tvarkytojo (įrašo autorius) nėra korektiška, nes neatitinka veiklos logikos  ar ji tik nepateikiama formose? 
Veiklos logika yra tokiame ryšyje: 
- duomenų teikėjų organizaciją registruoja koordinatorius, kuris yra automatiškai susietas su savo organizacija;
- Organizacijos duomenis registruoja tvarkytojas arba jo funkciją atliekantis koordinatorius, 
- tvarkytoją registruoja koordinatorius.
 Organizacija, Koordinatorius, Tvarkytojas ir rinkinys yra susiję!
Reikia įvertinti kiek sudėtinga tai pataisyti ir kokias ADP vietas tai gali paveikti neigiamai? Jeigu šis pataisymas reikalauja daugiau pastangų, nei tai sutaupytų - tektų kol kas atsisakyti.

Pavyzdžiui:
1. Pateiktas prašymas/ poreikis šiam organizacijos rinkiniu: https://test.data.gov.lt/datasets/2473/#info
    Rinkinys neturi nurodyto rinkinio tvarkytojo/ koordinatoriaus (tuščia) https://test.data.gov.lt/datasets/2473/members/,  el. žinutės siuntimas vyksta pagal situacija Nr. 1 aprašytą procesą.
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/fc09911f-1c07-4262-878a-330299255dc5)

**Comment by adp-atea** [comment]
Tik pridėjus poreikius, laiškai turėtų siųstis gerai, čia bus galima testuoti. 

Norint testuoti ar laiškai nueina po 5/10 d.d. reikia į cron job'us pridėti skriptą `send_request_emails.py`, kuris būtų praleidžiamas vieną kartą per dieną.

Taip pat jei nebuvo dar praleistas `add_holiday_dates.py` skriptas, taip pat reikėtų praleisti, kad duomenų bazėje būtų įvestos
švenčių datos.
