### ISSUE TITLE
Nekorektiškai veikia poreikio perskyrimas kitai institucijai

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#989]
Po uždučių https://github.com/atviriduomenys/katalogas/issues/973  ir https://github.com/atviriduomenys/katalogas/issues/975 įgyvendinimo Poreikių perskyrimo kitai organizacijai klaidos:
1) pridėjus naują organizaciją, bet nepašalinus "pirminės" (o tokia situacija taip pat galima), nors poreikio sąrašo formoje yra abi organizacijos, "pirminės" organizacijos koordinatoriaus "Mano poreikiai" sąraše "pirminės" jau nebėra.  

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/70d06db4-add8-47f8-a5f6-80420109a9c0)
"pirminės" organizacijos koordinatoriaus perskyrė šius poreikius RC, ir nors savosios nepašalino pagal "Mano poreikiai" sąrašo išrankoje šių poreikių jau nemato:
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/9d14c308-14e4-4d20-8eff-00690ab4513a)
o suradus šiuos poreikius iš RC adresuotų sąrašo ir atidarius, matosi, kad prie šio poreikio priskirtos abi organizacijos:
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/d031b0ad-676b-4fdf-84ee-aacc8029f2a8)

2) Atlikus poreikio perskyrimą korektiškai neveikia "Organizacijos" filtras poreikių formoje:
Kai iš RC sąrašo surastą testuojamą poreikį pakartotinai perskiriu sąraše esančiai SAM: 
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/f866fc29-4928-4ff4-a4cf-2443eac1a3e8)
poreikis Mano poreikiai sąraše atsiranda, bet išnykst RC sąraše (nors iš ten nepašlainta), bei "nusimuša" Poreikių formos filtro "Organizacijos" veikimas:
- organizacijos Lietuvos Respublikos sveikatos apsaugos ministerija (SAM) organizacijų sąraše (https://test.data.gov.lt/requests/submitted/) iš viso nepateikia, bet jeigu panaudojant Filtrą "Valdymo sritis" pasirenkama SAM, tai pastaroji jau atsiranda ir Organizacijų filtro sąraše:
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/f25afd10-6e79-47ea-9b70-ada5969fb171)
3)Kadangi po perskyrimo kitai organizacijai, Poreikis tampa "nematomas" "pirminės" organizacijos koordinatoriui, tai jis jau netenka galimybės"pašalinti" savo organizaciją iš sąrašo pateikiamo Poreikio>Organizacija formoje, o naujai priskirtos organizacijos koordinatorius neturi galėti pašalinti ne savo organizacijos.

**Comment by JuliusLADP** [comment]
Vėl testinėje aplinkoje dingo galimybė N institucijos koordinatoriui pridėti kitą organizaciją ir pašalinti sąvają

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/e4955bf6-5711-4252-9f72-5613aaf85b7c)
Pridėti kitą organizaciją gali organizacijos, gavusios nukreiptą jai Poreikį. Koordinatorius gali šalinti tik savo organizaciją.

Panaudojus perskyrimą organizacijai (ministerijai) ir jai pavaldžioms įstaigoms Poreikių puslapyje atsiranda "tušti" poreikiai:

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/8e32eaad-9dbc-41bc-911e-c2a761002f71)

**Comment by JuliusLADP** [comment]
Grąžinu pataisymui, nes vėl testinėje aplinkoje dingo galimybė N institucijos koordinatoriui pridėti kitą organizaciją ir pašalinti sąvają

https://test.data.gov.lt/requests/14387/orgs/
keitimą turi galėti daryti Sveikatos apsaugos ministerijos koordinatorius (julius.belickas@gmail.com)
![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/e4955bf6-5711-4252-9f72-5613aaf85b7c)

**Comment by adp-atea** [comment]
Jūsų naudotojas nėra pridėtas kaip organizacijos koordinatorius.
![image](https://github.com/atviriduomenys/katalogas/assets/107176624/1e7958c6-e731-410a-87f1-951bf38818c8)
