### ISSUE TITLE
Nenurodyta Organizacija, kai registruojamas prašymas/ poreikis dėl klaidos duomenyse

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#998]
Kai viešas naudotojas registruoja prašymą/ poreikį ištaisyti klaidą jau esančio rinkinio duomenyse (1), "Poreikiai ir pasiūlymai" (2) formos skiltyse "Duomenų rinkiniai"  ir "Organizacija" turi būti automatiškai pateikiami atitinkami duomenys.
"Duomenų rinkiniai" - turi būti nurodytas duomenų rinkinys, kurio duomenims registruotas prašymas ištaisyti klaidą (3).
"Organizacija" - turi būti nurodyta organizacija, kurios duomenų rinkinio duomenims registruotas prašymas ištaisyti klaidą (4).

(1)
https://test.data.gov.lt/datasets/2433/data/Parama/
https://test.data.gov.lt/datasets/2433/data/Parama/a7d10aa2-f39c-482c-88d3-030e01504496/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/698bf383-e193-43fe-bfdd-3b18c599744a)

(2)
 https://test.data.gov.lt/requests/14400/
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/12f1b668-14ef-469c-96c5-e41ad02e3627)

(3)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/9cabd901-7fb8-48c7-a22e-9e66ab8715e9)

(4)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/c75e0c6e-3712-4715-a53c-41211fd1e736)

**Comment by ATEAanalyst** [comment]
Pasižiūrėjau registruojant poreikį per modelį ir peržiūrint poreikį iš "Poreikiai ir pasiūlymai" skilties nėra ne tik organizacijos, bet ir duomenų rinkinio. Ar čia taip turi būti? Ar ir čia reikia pataisyti ir taisyti peržiūrint visus poreikių teikimo būdus?

**Comment by JuliusLADP** [comment]
Tai sisteminis trūkumas, taikytinas visais atvejais - nes kalba eina apie esamą rinkinį, nesvarbu ar poreikis registruotas viso rinkinio, ar DSA, ar atskiro lauko kontekste. Tai yra įvardinta aprašymo pradžioje, o logine prasme išplaukia iš ryšio, kad poreikis registruojamas rinkiniui, kuris priskirtas organizacijai, kuri turi koordinatorių ir konkretų šio rinkinio tvarkytoją (duomenų vientisumo principas).

**Comment by ATEAanalyst** [comment]
Taip Juliau, klausimai yra, kad išsigryninti klaidos apimtis, kad pataisyti visus atvejus, o ne dalinai. Aprašysiu visas mano rastas situacijas, kurias manau reikia taisyti ir kurias taisysime. Jeigu situacija nebus pateikta aprašyme ir jau būsime atlikę darbus, ją įsivertinsime atskirai.

**Comment by ATEAanalyst** [comment]
Dar turiu klausimą, pridėjus organizaciją pridėti turėtume pridėti ir visas pavaldžias jai organizacijas?

**Comment by JuliusLADP** [comment]
Ne. Konkretus rinkinys daugeliu atvejų, yra vienos organizacijos, kuri turi koordinatorių ir tvarkytoją, tai su jais ir siejasi. Gal būti atvejų, kai vienas rinkinys yra susiejamas su daugiau organizacijų, kurios buvo šio rinkinio bendraautoriai (contributor). Nesu tikras, bet DB modelyje tas turėtų būti numatyta. Šiuo atveju, svarbiau kad poreikis, būtų susietas su ta organizacija, kurios tvarkytojas ir/ar tik koordinatorius tvarko su poreikiu susijusį rinkinį

**Comment by ATEAanalyst** [comment]
[Aprašymas_#998.docx](https://github.com/atviriduomenys/katalogas/files/15150261/Aprasymas_.998.docx)

Pridedamas aprašymas, laukiame pastabų ar patvirtinimo.

**Comment by JuliusLADP** [comment]
Esminių pastabų aprašymui neturiu, tik siekdamas tikslesnio ir vienareikšmiškesnio teksto išdėstymo -  pateikiau alternatyvų pridedamame faile [Aprasymas_.998 JB.docx](https://github.com/atviriduomenys/katalogas/files/15183971/Aprasymas_.998.JB.docx)

Gal būt reikėtų susitikimo metu tiksliai susitarti kaip tekstuose įvardiname naudotojo aplinkas: formomis?langais?, meniu pasirinkimus? meniu juostas? ir pan. ?

Taip pat reikia pastebėti, kad būtų tikslinga įvertinti ar netikslinga kartu modifikuoti poreikio prie rinkinio (galbūt, modelio ir lauko) pateikimo formą, kaip aprašyta https://github.com/orgs/atviriduomenys/projects/10/views/1?pane=issue&itemId=61632062  
Prie rinkinio gali būti registruojami tokių tipų poreikiai: ištaisyti klaidą arba netikslumą duomenyse, papildyti trūkstamais duomenimis, pakeisti atnaujinimo periodiškumą.

**Comment by ATEAanalyst** [comment]
Dėl tvarkos siūlau prie šios užduoties tikrai nieko neaptarinėti. Kiekviena užduotis turi būti skirta tik vienam esminiam dalykui, funkcionalumui. Jeigu funkcionalumas yra platesnis, jį reikia skirstyti į atskiras mažesnes užduotis. Aprašymuose pridedami yra ir ekranvaizdžiai, kad būtų aišku apie kurias vietas kalbama, todėl manau, kad nesusipratimų neturėtų būti. Kad ir kaip pavadinsime, pridėjus ekranvaizdį aišku apie kurias vietas kalbame.

**Comment by ATEAanalyst** [comment]
Pridedu atnaujintą aprašymą, pagal jūsų pastabas. Jeigu jį patvirtinate, galėsime pradėti užduoties vertinimą. 
[Aprašymas_#998 (2).docx](https://github.com/atviriduomenys/katalogas/files/15218034/Aprasymas_.998.2.docx)

**Comment by JuliusLADP** [comment]
Ištaisymams pastabų neturiu

**Comment by ATEAanalyst** [comment]
Darbus (programavimą, analizę, testavimą ir diegimus) vertiname 20h. Ar patvirtinate vertinimą ir galime pradėti vykdyti užduotį?

**Comment by JuliusLADP** [comment]
20 val. apimtis užduoties įgyvendinimui patvirtinu
